### ISSUE TITLE
Chrome Web Store and Opera add-ons URL are missing

### ISSUE THREAD

**Issue by NatoBoram** [dessant/buster#1]
In the following paragraph, the link on the Chrome Web Store and the Opera add-ons images are missing.

```html
<p align="center">
	</br>
	</br>

	<a href="">
		<img src="https://i.imgur.com/q6E8SOD.png" alt="Chrome Web Store">
	</a>

	<a href="https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-solver/">
		<img src="https://i.imgur.com/dvof8rG.png" alt="Firefox add-ons">
	</a>

	<a href="">
		<img src="https://i.imgur.com/wK10qEV.png" alt="Opera add-ons">
	</a>

	</br>
	</br>
</p>
```

https://github.com/dessant/buster/blob/master/README.md#buster-captcha-solver-for-humans

**Comment by dessant** [comment]
They were submitted, but not yet reviewed. I'll update the download buttons once the listings get published.

**Comment by dessant** [comment]
The Opera listing is live now.
https://addons.opera.com/en/extensions/details/buster-captcha-solver-for-humans/

**Comment by dessant** [comment]
The Chrome listing was also published.
https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl
