### ISSUE TITLE
solvemedia extension

### ISSUE THREAD

**Issue by ceweiss** [dessant/buster#101]
It would be amazing if this could be extended to handle SolveMedia captchas as well. 

Fully aware that a similar request was made in early 2019 and that at the point you did not plan to extend it to other sources than Recaptcha, but given that SolveMedia is used a whole lot and builds on essentially the same audio challenge, it would be interesting to have the feature.

Thanks for considering

**Comment by dessant** [comment]
SolveMedia does not appear to show hostility towards users, and it does not lock them out of services like reCAPTCHA does, so I do not see a pressing need for supporting it.

**Comment by bmn001** [comment]
I have seen several cases now where just _clicking_ on the text entry box for Solve Media captcha will open a pop-up ad window.  That feels fairly user-hostile to me.  Please reconsider adding support for SolveMedia captchas.

**Comment by skanga** [comment]
AFAIK - Solve media does lock users out of services ...
