### ISSUE TITLE
Is this OK by Google?

### ISSUE THREAD

**Issue by JobaDiniz** [dessant/buster#103]
I mean, Google could block these kind of extensions. As matter of fact, it's weird that it allows such extensions in the Chrome Store, don't you think? It's breaking its reCaptcha service.

What are you thoughts on the subject?

**Comment by dessant** [comment]
This is an accessibility tool that helps people access services and information on the web, and requires manual action to solve the challenge, it does not break or bypass the challenge.

The extension respects Chrome Web Store policies, so there is no reason for it to be taken down.
