### ISSUE TITLE
Bug with Firefox 68.0.1 and Mac

### ISSUE THREAD

**Issue by hentai-kamen** [dessant/buster#107]
OS Name: Mac OS
OS Version: 10.14.4
Browser: Firefox
Browser Version: 68.0.1

Extensions: Buster 0.6.0
Client App Installed: 0.2.0

Not sure how to find the Buster Client Logs with the Mac.

I am getting two different issues with Firefox. One before I installed the client app, and one after.

The one before, it give me the error "Cannot contact reCAPTCHA. Check your connection and try again."

I tried disabling adblock, and privacy badger, but it still gives me the same error. It even appears to solve the captcha, but gives me the error.

The second error that I receive is when I install the Buster Client. It clicks off of firefox, and then and never solves the captcha. These are the logs, sorry, I don't know how to make it more organized.

Error processing windowTypes: This property is deprecated global.min.js:250
    makeError resource://gre/modules/Schemas.jsm:459
    logDeprecation resource://gre/modules/Schemas.jsm:1109
    checkDeprecated resource://gre/modules/Schemas.jsm:1121
    normalizeBase resource://gre/modules/Schemas.jsm:1236
    normalize resource://gre/modules/Schemas.jsm:1924
    r resource://gre/modules/Schemas.jsm:1666
    withPath resource://gre/modules/Schemas.jsm:544
    checkProperty resource://gre/modules/Schemas.jsm:1666
    normalize resource://gre/modules/Schemas.jsm:1727
    normalize resource://gre/modules/Schemas.jsm:1366
    fixedArgs resource://gre/modules/Schemas.jsm:2256
    map self-hosted:291
    checkParameters resource://gre/modules/Schemas.jsm:2251
    stub resource://gre/modules/Schemas.jsm:2334
    a moz-extension://8f606041-d1f4-5246-a794-a5717003de2c/global.min.js:250
    apply self-hosted:4417
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:539
    fire resource://gre/modules/ExtensionChild.jsm:1004
    receiveMessage resource://gre/modules/ExtensionChild.jsm:1007
    _callHandlers resource://gre/modules/MessageChannel.jsm:876
    _callHandlers resource://gre/modules/MessageChannel.jsm:875
    promise resource://gre/modules/MessageChannel.jsm:952
    _handleMessage resource://gre/modules/MessageChannel.jsm:949
    _handleMessage self-hosted:1005
    receiveMessage resource://gre/modules/MessageChannel.jsm:218
    forEach self-hosted:266
    receiveMessage resource://gre/modules/MessageChannel.jsm:211
TypeError: s is undefined script.js:1:57751
TypeError: s is undefined script.js:1:55318
Error processing windowTypes: This property is deprecated 2 global.min.js:250
a is undefined global.min.js:250
    a moz-extension://8f606041-d1f4-5246-a794-a5717003de2c/global.min.js:250
    apply self-hosted:4417
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:539
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:752
    withLastError resource://gre/modules/ExtensionCommon.jsm:676
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:744
Unchecked lastError value: Error: Invalid window ID: 112 global.min.js:250
    a moz-extension://8f606041-d1f4-5246-a794-a5717003de2c/global.min.js:250
Error processing windowTypes: This property is deprecated 2 global.min.js:250
    makeError resource://gre/modules/Schemas.jsm:459
    logDeprecation resource://gre/modules/Schemas.jsm:1109
    checkDeprecated resource://gre/modules/Schemas.jsm:1121
    normalizeBase resource://gre/modules/Schemas.jsm:1236
    normalize resource://gre/modules/Schemas.jsm:1924
    r resource://gre/modules/Schemas.jsm:1666
    withPath resource://gre/modules/Schemas.jsm:544
    checkProperty resource://gre/modules/Schemas.jsm:1666
    normalize resource://gre/modules/Schemas.jsm:1727
    normalize resource://gre/modules/Schemas.jsm:1366
    fixedArgs resource://gre/modules/Schemas.jsm:2256
    map self-hosted:291
    checkParameters resource://gre/modules/Schemas.jsm:2251
    stub resource://gre/modules/Schemas.jsm:2334
    a moz-extension://8f606041-d1f4-5246-a794-a5717003de2c/global.min.js:250
    apply self-hosted:4417
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:539
    fire resource://gre/modules/ExtensionChild.jsm:1004
    receiveMessage resource://gre/modules/ExtensionChild.jsm:1007
    _callHandlers resource://gre/modules/MessageChannel.jsm:876
    _callHandlers resource://gre/modules/MessageChannel.jsm:875
    promise resource://gre/modules/MessageChannel.jsm:952
    _handleMessage resource://gre/modules/MessageChannel.jsm:949
    _handleMessage self-hosted:1005
    receiveMessage resource://gre/modules/MessageChannel.jsm:218
    forEach self-hosted:266
    receiveMessage resource://gre/modules/MessageChannel.jsm:211
a is undefined global.min.js:250
    a moz-extension://8f606041-d1f4-5246-a794-a5717003de2c/global.min.js:250
    apply self-hosted:4417
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:539
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:752
    withLastError resource://gre/modules/ExtensionCommon.jsm:676
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:744
Unchecked lastError value: Error: Invalid window ID: 112 global.min.js:250
    a moz-extension://8f606041-d1f4-5246-a794-a5717003de2c/global.min.js:250

**Comment by dessant** [comment]
The first issue can be somewhat mitigated by using the client app.

Have you enabled privacy.resistFingerprinting? Fingerprint protection prevents the extension from discovering the scale of your display, so it will move the mouse to the wrong place on HDPI screens.

**Comment by hentai-kamen** [comment]
Hey,

What do you mean by using the "client app"? I installed the buster extension and buster-client-setup-v0.2.0-macos-amd64. Not sure if that's what you mean.

Secondly, I did enable resist fingerprinting. Looks like when I disable fingerprinting, the extension does work. Would there be a workaround where I can disable fingerprinting as well as use buster?

Anyway around this error? The one before, it give me the error "Cannot contact reCAPTCHA. Check your connection and try again."

**Comment by dessant** [comment]
There is no workaround, this is a Firefox bug. Extensions run priviledged code, and they should receive accurate data about their environment in order to function as expected.

I suggest you open a bug report for Firefox, extensions must be given the correct value of window.devicePixelRatio when privacy.resistFingerprinting is enabled.
