### ISSUE TITLE
Idea against blocks: don't actually solve the captcha

### ISSUE THREAD

**Issue by My1** [dessant/buster#108]
**Is your feature request related to a problem? Please describe.**

the blocks people are getting

**Describe the solution you'd like**

don't mess with recaptcha directly, just pull the sound and tell the user the solution outside the scope of recaptcha surveillance

for example don't put the button inside the captcha or screw with the dom, but rather for example light up a toolbar icon.

**Describe alternatives you've considered**

are there any to avoid blocks? I am not sure, but this definitely can be optional.

**Comment by drenex28** [comment]
hey sorry am i deaf yes ...i don't know about things how get fix it by first time here ...i hard think !!! not easy :(

**Comment by dessant** [comment]
Buster will change in the coming months. The current behavior will only be enabled when the client app is installed.

When user input simulation is not enabled, users will need to visit the audio challenge manually, the extension will fill out the audio transcription, and users will need to manually submit the solution.

This change is being delayed because the client app needs further adjustments to work on Windows 32bit, and the extension will need to have a welcome screen that explains the two different behaviors, and guides users to install the client app.

**Comment by My1** [comment]
Well as long as auto filling out doesn't trigger any warnings, i would have thought that while captcha can't really check who transcribed the audio, only how it is interacted with. And well obviously if a human does the typing it might help, was my idea

**Comment by dessant** [comment]
Yes, alternatively the user will also be able to copy over the solution that is shown in a popup or something similar.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
shouldn't this input simulation be more human than to copy over solutions

**Comment by dessant** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software, it already does. We're talking about the introduction of a new manual mode for those who do not want to install the client app (which provides user input simulation).

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
the other example is, users that can´t install because used platform not supported by the client app. You can run buster extension in Android Devices. Improvements would benefit this scenario also.
By Definition of robot, copy/paste should be very robotic like, as no normal human user could have the right captcha solutions already in clipboard i guess.

**Comment by dessant** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software, the current automatic mode will no longer exist when the client app is not installed, a solution will be presented in some way for the user, and it is up to them to type it in manually, they do not have to copy and paste it.

**Comment by dessant** [comment]
@Chris-Devine, your experience with reCAPTCHA can wildly differ based on the network you connect from, your browser settings, Google account activity etc.

When a visitor is already (sometimes wrongly) treated with suspicion, they have a higher chance of being blocked from solving the audio challenge, especially when the client app is not installed and user input simulation is not used. These block can also appear without using the extension.

You may get away for a while without using the client app, until temporary blocks beging to appear. This is why in the future the extension will stop automatically switching to the audio challenge and submitting the solution when user input simlation is not enabled.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> @4-FLOSS-Free-Libre-Open-Source-Software, the current automatic mode will no longer exist when the client app is not installed, a solution will be presented in some way for the user, and it is up to them to type it in manually, they do not have to copy and paste it.

Please don't do this, don't remove the automatic mode, it save me time everyday in Android devices.
See proof:

**Comment by My1** [comment]
what proof?
but honestly. I think an automatic solving kinda hinders everything, typing in the code manually or whatever has 2 big advantages
1) google will see it less likely as a bot -> less blocking
2) google has less of a motivation to make it deliberately not work with this and in process they probably would make it much harder for normal humans with impaired vision

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
@My1 
i have added a recording of automatic mode working to solve multiple captchas in a row. with of course no user simulation app existing on this.

i vote for not remove this useful feature. but if you want to change it's default behaviour. please let the user choose by selecting an option for use old way of captcha solving. as the current mode is working fast and without too many false positives for me. Both in smartphone & tablet devices.

**Comment by My1** [comment]
but honestly typing in the solution doesnt take THAT much time and if the autosolver leads to google making the lives harder for everyone, well please not.

**Comment by dessant** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software, it's possible that the current behavior will be preserved on platforms that do not support native messaging, such as Android, but it will no longer be enabled by default.

**Comment by dessant** [comment]
Thanks for contributing with ideas, I'll make use of them in the next few releases.
