### ISSUE TITLE
Addon tries the wrong language?

### ISSUE THREAD

**Issue by zingmars** [dessant/buster#11]
On Firefox 64.0 (64-bit) using Windows 10. The website affected is https://www.nic.lv/whois. Despite the fact that the captcha gives me english audio files the addon incorrectly tries to interpret the audio as if it was in Latvian and inputs Latvian words which are obviously incorrect. 

![20181214-154252](https://user-images.githubusercontent.com/917126/50006623-fdae7600-ffb6-11e8-838f-6c6fd8ea5214.gif)

**Comment by dessant** [comment]
Thanks for the bug report! Yes, sometimes the audio is in English despite the different locale. This was fixed in commit https://github.com/dessant/buster/commit/f13d1eaace28681975806b36f28e09d2a5dae420 and it will be part of the next release.
