### ISSUE TITLE
Multiple correct solutions required - please solve more.

### ISSUE THREAD

**Issue by minanagehsalalma** [dessant/buster#111]
can you automate this pls ?
i am not using an kind of vpn and it happens sometimes

**Comment by dessant** [comment]
Tracked at https://github.com/dessant/buster/issues/22.

**Comment by minanagehsalalma** [comment]
@dessant  but it been open 7 months ago!

**Comment by dessant** [comment]
@minanagehsalalma, this is an open source project that is freely available for everyone, and for which anyone can submit improvements. If this issue is important to you, please submit a fix for it, or wait patiently until some finds the time to fix your issue.

**Comment by minanagehsalalma** [comment]
Fine .
