### ISSUE TITLE
I continue to see Captcha boxes as before...

### ISSUE THREAD

**Issue by rafikiphoto** [dessant/buster#117]
I'm using Vivaldi latest stable version on Windows 10. After installing Buster from the Chrome Web Store I continue to see the Captcha boxes as before. What could be wrong? Is there a setup step I'm missing somewhere?

**Comment by dessant** [comment]
reCAPTCHA widgets will still show up, and you can solve them by clicking on the extension icon. Is there a new icon at the bottom of the reCAPTCHA widget, like here?

![](https://camo.githubusercontent.com/91158c1be4bfc236972e157d167e1d080befd551/68747470733a2f2f692e696d6775722e636f6d2f685471654e347a2e706e67)

**Comment by rafikiphoto** [comment]
I think there is Armin. I'll check on the next one.

Thanks,

Brian.

------ Original Message ------

**Comment by dessant** [comment]
Make sure to also install the client app for user input simulation, otherwise you might be temporarily blocked from solving the audio challenge, see the details here: https://github.com/dessant/buster/issues/56#issuecomment-481655521
