### ISSUE TITLE
Required Resources

### ISSUE THREAD

**Issue by mustaqimM** [dessant/buster#12]
What's required for this to work? I can only get it to work after disabling uBlock Origin and uMatrix? I get
a 'Something went wrong' error with this in the console:
```
undefined is not a valid URL. background.js:335

    onBeforeRequest moz-extension://3ca37ddd-63fb-4c31-b134-959bbbb82ce5/background-scripts/background.js:335 apply self-hosted:4632 applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:539 applySafe resource://gre/modules/ExtensionCommon.jsm:526 sync resource://gre/modules/ExtensionCommon.jsm:2227 listener chrome://extensions/content/child/ext-webRequest.js:27 next self-hosted:1210 

TypeError: NetworkError when attempting to fetch resource. script.js:1:16572 
```
I have all reCaptcha resourses checked

**Comment by dessant** [comment]
It should work with uBlock Origin, I have not tested uMatrix. Does it work if you disable uMatrix?

**Comment by mustaqimM** [comment]
@dessant It works on easy mode but not on advanced. Is there a domain I'm supposed to whitelist?

**Comment by dessant** [comment]
uMatrix does not seem to have easy and advanced modes, iI think you're talking about uBlock Origin.

For uMatrix there is an addon icon in the extension popup, you can load the reCAPTCHA rules there. As for uBlock, it depends on your exact settings, and you will have to experiment with whitelisting both reCAPTCHA and extension requests.

You can find the hosts the extension could connect to by searching for `https:` [here](https://github.com/dessant/buster/blob/master/src/utils/data.js#L310) and [here](https://github.com/dessant/buster/blob/master/src/solve/main.js). uBlock will show you the blocked hosts in the popup if advanced mode is enabled, and they can be whitelisted there.

**Comment by mustaqimM** [comment]
@dessant I finally figured it's one of these settings under advanced mode:
```
            assetFetchTimeout 30
   autoUpdateAssetFetchPeriod 120
             autoUpdatePeriod 7
             benchmarkingPane false
cacheControlForFirefox1376932 no-cache, no-store, must-revalidate
      cacheStorageCompression true
              debugScriptlets false
           disableWebAssembly false
        ignoreRedirectFilters false
    ignoreScriptInjectFilters false
 manualUpdateAssetFetchPeriod 500
                popupFontSize unset
  requestJournalProcessPeriod 1000
 strictBlockingBypassDuration 120
        suspendTabsUntilReady true
        userResourcesLocation unset
```
