### ISSUE TITLE
[Discussion] Buster missing from the Chrome Web Store

### ISSUE THREAD

**Issue by dessant** [dessant/buster#120]
[Buster](https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl) has disappeared last night from the Chrome Web Store.

I have not received any communication from Google, and the extension is marked as published in the developer dashboard, with no visible sign of a problem.

It's possible that this is a bug, it would be highly unusual to take down a Chrome extension without notifying developers.

Updates on the issue will also be shared here: https://github.com/dessant/buster/issues/121

![](https://user-images.githubusercontent.com/7513068/66200839-97602480-e6aa-11e9-8c8d-9869edaed0b0.png)

**Comment by Kein** [comment]
Pretty convenient bug, dont you think?

**Comment by dessant** [comment]
@Kein, we'll have to wait things out. Do you have an existing Buster installation in Chrome? I'm wondering if current installations are still working.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
it is still working and is there: https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl

**Comment by dessant** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software, yes, it seems to be back, though it's still missing from search results.

https://chrome.google.com/webstore/search/buster%20captcha?_category=extensions

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
i didn't notice this while installed. confirming from direct query it is indeed missing out. in similar addons view it also appears. 
![image](https://user-images.githubusercontent.com/46166740/66253568-e1a8da80-e76a-11e9-8673-8a5d1eed7fc0.png)

**Comment by dessant** [comment]
It looks like the extension is now fully restored everywhere.
