### ISSUE TITLE
"Cannot contact Recaptcha. Check your settings and try again." on Firefox

### ISSUE THREAD

**Issue by rainbowjose** [dessant/buster#122]
**System**

* OS name: Windows 
* OS version: 10
* Browser name: Firefox
* Browser version: 69.0.2

**Extension**

* Extension version: 0.6.0

* User input simulation: no

**Bug description**

**Logs**
https://i.imgur.com/jZbDjFj.png

**Comment by dessant** [comment]
Visit the extension's options and enable user input simulation, then follow the instructions which will appear to download and install the client app.

**Comment by rainbowjose** [comment]
I dont want install strange exe. In chrome if works good. Installing exe - is not a solution.

**Comment by dessant** [comment]
The client app is an essential part of this project, and it is the only effective way to simulate native user input event across platforms, which in turn reduces the chance of errors and temporary blocks.

**Comment by rainbowjose** [comment]
Okay, but can you implement setting to control speed of input? Clieint
typing is too slow.

**Comment by dessant** [comment]
I don't think it's slow, it seems faster to me than average human typing. These parameters won't be configurable, because some may increase the speed too much and trigger the same errors they are trying to avoid.

**Comment by Riajyuu** [comment]
@dessant Can you pin this again?
It takes me some time to find here since I got the same problem today.
