### ISSUE TITLE
Can't install client app in TorBrowser

### ISSUE THREAD

**Issue by aliceric27** [dessant/buster#126]
How can i install buster on torBroswer?
I'm trying install add-on from firefox but always get this error
thanks

![image](https://user-images.githubusercontent.com/30149653/69489733-ff1b3a80-0eb7-11ea-8341-c846cdbfe4b0.png)

**Comment by dessant** [comment]
The extension will rarely work on Tor Browser, because the reCAPTCHA audio challenge is usually blocked over Tor, even when you don't use the extension.
