### ISSUE TITLE
No option window on firefox 56

### ISSUE THREAD

**Issue by Janaue** [dessant/buster#129]
I have stock firefox 56b12 portable on w10 1809 and the option window at moz-extension://a3e6e5d1-1fc0-44bd-8566-3a22eb14bd63/src/options/index.html
remains blank after a restart of firefox

buster works though, at least on the test page https://patrickhlauke.github.io/recaptcha/

**Comment by dessant** [comment]
The unique ID you see in the URL is assigned by Firefox for a single browser session. I'm not aware of a way to bookmark the options page of a WebExtension.
