### ISSUE TITLE
Error: API response: 429

### ISSUE THREAD

**Issue by hanacchi** [dessant/buster#130]
**System**

* OS name: Windows
* OS version: 7
* Browser name: Firefox
* Browser version: 71

**Extension**

* Extension version: 0.6.0
* User input simulation: yes
* Client app version: 0.2.0
* Client app installed successfully: yes

**Bug description**

1. Try to solve captcha with buster
2. Get a notification saying "Something went wrong. Open the browser console for more details."

This happens every once in a while but when it does it usually happens a few times in a row.

**Logs**

Browser:
```
Error: API response: 429, {
  "code": "rate-limit",
  "error": "You have exceeded the limit of 400 requests per minute for your app"
}
```

Client app:
```
2019/12/21 04:05:35.516331 Starting client (version: 0.2.0)
2019/12/21 04:05:35.516331 Receiving message
2019/12/21 04:05:35.516331 Processing message
2019/12/21 04:05:35.516331 Command: ping
2019/12/21 04:05:35.516331 Sending response
2019/12/21 04:05:35.516331 Receiving message
2019/12/21 04:05:35.536332 Processing message
2019/12/21 04:05:35.536332 Command: moveMouse
2019/12/21 04:05:35.536332 X: 916, Y: 896
2019/12/21 04:05:35.538332 Sending response
2019/12/21 04:05:35.538332 Receiving message
2019/12/21 04:05:35.640338 Processing message
2019/12/21 04:05:35.640338 Command: clickMouse
2019/12/21 04:05:35.651339 Sending response
2019/12/21 04:05:35.651339 Receiving message
2019/12/21 04:05:37.341436 Processing message
2019/12/21 04:05:37.341436 Command: moveMouse
2019/12/21 04:05:37.341436 X: 1111, Y: 586
2019/12/21 04:05:37.359437 Sending response
2019/12/21 04:05:37.359437 Receiving message
2019/12/21 04:05:37.465443 Processing message
2019/12/21 04:05:37.465443 Command: clickMouse
2019/12/21 04:05:37.476443 Sending response
2019/12/21 04:05:37.476443 Receiving message
2019/12/21 04:05:37.977472 Closing client
```

**Comment by dessant** [comment]
Try again, it seems to work now. There are too many people using the extension with the default speech recognition service, I'll add a couple more API keys in the next release and rotate them.

You can also use your own API key from https://wit.ai, it is a free service.

**Comment by Cyberavater** [comment]
I'm having the exact same problem here.

**Comment by dessant** [comment]
Visit the extension's options if the error comes back, and switch to the `Wit Speech API` service, then add this API key for English: EQAXGAJVZIMI3YMILN2XQZY7IWGUPKGL

**Comment by hanacchi** [comment]
Thanks for the quick reply! That seems to have fixed it for now. If the issue comes up again I'll get my own API key.

**Comment by coaxial** [comment]
Could you detail how to get my own API key? When I go to wit.ai all I see is a very minimalistic page with three lines of text describing what the company does and no way to sign up.

**Comment by Cyberavater** [comment]
> I'll add a couple more API keys in the next release and rotate them.

Can you add some more? I'm having this problem again recently.

**Comment by coaxial** [comment]
@Cyberavater you can get your own key and add it yourself then you most likely won't run into that issue ever again.

> You can also use your own API key from https://wit.ai, it is a free service.

**Comment by dessant** [comment]
4 keys should be plenty for the current user base. It's also possible that someone is taking the keys to abuse the service, so the quota is sometimes depleted.

**Comment by bncdemo** [comment]
"API quota exceeded: Try again later" error.  Is this end of the story? The error is permanent.
