### ISSUE TITLE
xinput fails when only text is zoomed

### ISSUE THREAD

**Issue by Janaue** [dessant/buster#132]
Xinput competently fails when I make only the text to t zoom in firefox 56

when the zoom applies to text+pictures, buster works.

**Comment by dessant** [comment]
In what sense does it fail?

**Comment by Janaue** [comment]
It is on windows 1809 and firefox 56. With zoom for only text, the mouse misses the ''play'' button, the text area and so on.

when text+pictures are zoomed, it works.
