### ISSUE TITLE
xinput fails when only text is zoomed

### ISSUE THREAD

**Issue by Janaue** [dessant/buster#133]
It is on windows 1809 and firefox 56. With zoom for only text, the mouse misses the ''play'' button, the text area and so on.

when text+pictures are zoomed, it works.

**Comment by Kelvino9** [comment]
Reproducible on Linux with Firefox 73.0.1 and only text is zoomed.

**Comment by dessant** [comment]
@Kelvino9 how are you zooming the text?

**Comment by Kelvino9** [comment]
@dessant I'm using the zoom option in the Firefox settings under _General > Languages and Appearance > Zoom (110% and Zoom text only enabled)_
