### ISSUE TITLE
Problems with Firefox

### ISSUE THREAD

**Issue by Jorge9811** [dessant/buster#134]
**System**

* OS name: Windows
* OS version: 8.1
* Browser name: Mozilla Firefox
* Browser version: v71.0 (32bit)

* Extension version: v0.6.0 I guess. That's what about:addons says. I got it from AMO just a while ago.
* User input simulation: No?

**Bug description**

For whatever reason, Buster or Google or idk what thinks that I'm sending fifty million requests or something.

**Logs**

https://pastebin.com/nXRwVNNi

** Other details **

I'm using a custom user.js with about:config parameters that I crafted myself, and a few addons.

The addons can be seen in this video I recorded showcasing the entire problem: https://streamable.com/wf14u

My user.js is the following: https://pastebin.com/aLnyDLEh

**Could you please help me pinpoint what is causing the addon to malfunction?**

I wish ReCaptcha just didn't exist at all tbh. I hate Google for ruining my web browsing experience like this and every single page that uses it.

**Comment by dessant** [comment]
See this issue for details: https://github.com/dessant/buster/issues/130

You should also enable user input simulation and install the client app, it makes it less likely to be temporarily blocked from accessing the audio challenge.
