### ISSUE TITLE
Error: Unable to decode audio data

### ISSUE THREAD

**Issue by facetoface10101980** [dessant/buster#138]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Chrome
* Browser version: 79.0.3945.130 (Offizieller Build) (64-Bit)

**Extension**

* Extension version: 0.6.0

* User input simulation: yes

* Client app version: yes
* Client app installed successfully: yes

**Bug description**

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by facetoface10101980** [comment]
Error: Unable to decode audio data no matter which API i'm using.

**Comment by dessant** [comment]
Can your browser play audio with this example?

https://mdn.github.io/webaudio-examples/decode-audio-data/

**Comment by facetoface10101980** [comment]
Hi Armin,

yes, it works.

Meanwhile, I made furtehr tests. So it seems that i get this error when the
proxy in my corporate network is enabled.
But what is much more strange when disable the proxy and click on the
buster button it just happens nothing and no error anymore in the console.

Best

Dave


Am Di., 28. Jan. 2020 um 13:19 Uhr schrieb Armin Sebastian <
notifications@github.com>:

**Comment by dessant** [comment]
I don't have a way to reproduce the error you're seeing. When the mp3 file cannot be decoded, it's usually because of an issue with codecs, which may be solved by updating Windows.
