### ISSUE TITLE
Doesn't work in Opera

### ISSUE THREAD

**Issue by Coloruts** [dessant/buster#14]
Addon doesn't work in Opera 57.0.3098.110. Literally nothing happens after installing, no button in recaptcha window

**Comment by dessant** [comment]
Starting Opera 57 the "Allow access to search page results" option must be checked for the extension on the chrome://startpage/extensions page. I have updated the extension description some time ago but it has not been approved yet, and newer versions of the extension are also waiting for moderation.

**Comment by xispit4** [comment]
We can run with addon for Chrome using the Install Chrome Extensions [1] on Opera till have the updated version approved by Opera Team.

[1] https://addons.opera.com/en/extensions/details/install-chrome-extensions/

**Comment by conceptualspace** [comment]
opera has abandoned their addons platform and instead direct users (inconsistently) to the the install-chrome-extension link above

**Comment by volia2** [comment]
+1 for Brave too.

**Comment by dessant** [comment]
The latest version of Buster is now live on Opera, visit the extension's options to try out user input simulation.
