### ISSUE TITLE
Waterfox Classic: workaround for Buster showing an error

### ISSUE THREAD

**Issue by dessant** [dessant/buster#141]
On Waterfox Classic an error is shown with the latest version (0.7.0) of Buster. Open the browser console to check the logs.

There may be an error, such as `TypeError: promise.then is not a function`. This issue can be solved by visiting about:config and switching on a Firefox preference.

Set the `dom.promise_rejection_events.enabled` preference to `true` and restart the browser to fix the issue.

Waterfox Classic support will be dropped in the near future, everyone is advised to migrate to Waterfox Current.

**Comment by hockeymikey** [comment]
> 
> 
> On Waterfox Classic an error is shown with the latest version (0.7.0) of Buster. Open the browser console to check the logs.
> 
> There may be an error, such as `TypeError: promise.then is not a function`. This issue can be solved by visiting about:config and switching on a browser preference.
> 
> Set the `dom.promise_rejection_events.enabled` preference to `true` and restart the browser to fix the issue.
> 
> Waterfox Classic support will be dropped in the near future, everyone is advised to migrate to Waterfox Current.

Why?

**Comment by dessant** [comment]
I've dropped support for outdated browsers for all my extensions, they are a maintenance burden, and show bugs like this one.

Waterfox Classic should maintain its own extension store with compatible extension versions.

**Comment by dessant** [comment]
In any case I'd prefer for at least this issue to be solved, so that Waterfox Classic is left with a working version, but I have very little time. If anyone would like to take a shot at fixing the bug, please let me know and I can reopen the issue. The guides to build the extension are in the wiki.

https://github.com/dessant/buster/wiki

**Comment by hockeymikey** [comment]
> 
> 
> I've dropped support for outdated Firefox versions for all my extensions, they are a maintenance burden, and show bugs like this one.
> 
> Waterfox Classic should maintain its own extension store with compatible extension versions.
Maintenance burden if you're lazy and bad. Hate developers that drop support because "it's too hard". I've withdrawn my support as a Patreon, better to spend it elsewhere. I'm going to add this to my docket for sure.

**Comment by dessant** [comment]
> Maintenance burden if you're lazy and bad. Hate developers that drop support because "it's too hard". I've withdrawn my support as a Patreon, better to spend it elsewhere. I'm going to add this to my docket for sure.

@hockeymikey, I can give you $1 a month if you'd like to support Waterfox Classic in your free time.

Then abuse you on GitHub if your work does not please me.

I honestly don't understand how can you justify behaving in such an abusive and entitled way. Do you feel like you're a good person during this chat?

**Comment by dessant** [comment]
Seriously, in the last few days there was a flock of people like you messaging me in private to do free work for them, such as rewrite the extension for Pale Moon and similar requests. I don't understand how are you not ashamed to be this abusive.

Just to offer you the workaround above I've spent my afternoon yesterday to discover it, and I don't even use Waterfox. And if you care to check the changelog, you'll discover that client app installation was added for Waterfox Current in a recent version.

Then all of that effort is topped off by a person like you giving me the finger. It's easy to see why open source developers abandoning their projects is a regular occurrence, the abuse you get is simply not worth it.

**Comment by dessant** [comment]
The above workaround no longer helps with the latest version of Waterfox Classic, there seems to be a new issue with how the audio is processed.

The next version of the extension will no longer support Waterfox Classic. If someone steps up to provide patches for the browser, we could reenable support for Waterfox Classic in the future.
