### ISSUE TITLE
Installation of client not working

### ISSUE THREAD

**Issue by hockeymikey** [dessant/buster#144]
* OS name: Windows 7
* Browser name: Waterfox classic 
* Browser version: 2020.01

**Extension**

* Extension version:  71.0

* User input simulation: both
* Client app version: 0.3.0
* Client app installed successfully: no

**Bug description**
Client app isn't installing. Get the following screenshot and error in the browser console.
![image](https://user-images.githubusercontent.com/1435185/74296941-eed26900-4d0a-11ea-8138-9365269453ca.png)

**Logs**
Browser:
```
Error: Client app response:   App.vue:129:8
```

Client app:
```
2020/02/12 02:44:56.085755 Starting client (version: 0.2.0)
2020/02/12 02:44:56.085755 Receiving message
2020/02/12 02:44:56.086755 Unsupported client version (requested: 0.3.0, supported: 0.2.0)
2020/02/12 02:44:56.086755 Sending response
2020/02/12 02:44:56.086755 Receiving message
2020/02/12 02:44:56.092755 Closing client
```
I feel like the cache or something with the client is stale and it's not refreshing leading to it running the 0.2 client instead of the 0.3. Happens to me on react sometimes too at work.

**Comment by dessant** [comment]
I'm not sure which cache are you referring to. If automatic client app updates are enabled in options, you could try solving a challenge, and the extension will notify you that the client app is being updated before moving on with solving. Alternatively, try installing again.

**Comment by hockeymikey** [comment]
> 
> 
> I'm not sure which cache are you referring to. If automatic client app updates are enabled in options, you could try solving a challenge, and the extension will notify you that the client app is being updated before moving on with solving. Alternatively, try installing again.

No idea, just spitballing. I never had the browser extension installed. You were right, updated after trying a challenge but still doesn't work on it.
