### ISSUE TITLE
Error: Attempting to use a disconnected port object

### ISSUE THREAD

**Issue by PsySc0rpi0n** [dessant/buster#149]
**System**

* OS name: [e.g. Windows, Ubuntu]
Debian
* OS version: [e.g. 10]
Buster
* Browser name: [e.g. Chrome, Firefox]
Chromium
* Browser version: [e.g. 60]
Version 80.0.3987.132 (Developer Build) built on Debian 10.3, running on Debian 10.3 (64-bit)
**Extension**

https://github.com/dessant/buster

* Extension version: [e.g. 1.0.0]
Version
0.7.0

* User input simulation: [e.g. yes, no]

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

When I try to use the Extension it asks me to download an install some application. I do so, following the instructions (make the downloaded app executable) and when I try to execute it, it opens a new Chromium tab and shows the following:
[ScreenShot](https://i.ibb.co/56Bt4h3/recaptcha.png)

Then I hit Install and I get the error in Chromium console:
Error: Attempting to use a disconnected port object
**Logs**

Browser:
```
Error: Attempting to use a disconnected port object
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
I think Chromium uses the Google Chrome user agent on Debian, so the extension does not correctly identify the browser it is running in. Before you click `INSTALL APP`, replace `google-chrome` with `chromium` in the manifest path, and it should install correctly.

**Comment by PsySc0rpi0n** [comment]
Yes, it fixed the problem. Thank you.
