### ISSUE TITLE
IBM Watson STT API Endpoint URL Likely Got Changed

### ISSUE THREAD

**Issue by hyunh90** [dessant/buster#152]
**System**

* OS name: Windows 10
* OS version: 10
* Browser name: Firefox
* Browser version: 74.0

**Extension**

* Extension version: 0.7.1

* User input simulation: yes

* Client app version: 0.3.0
* Client app installed successfully: yes

**Bug description**

Set to use IBM Watson STT API, Buster fails immediately with NetworkError.
![buster error](https://user-images.githubusercontent.com/1912333/77816609-21e57780-7081-11ea-826d-6c2333490892.png)
Using other services (tried Wit Managed) did not fail.

On Watson service page, API endpoint URL is now: `https://stream.watsonplatform.net/speech-to-text/api`.

**Logs**

Browser:
```
Error: NetworkError when attempting to fetch resource.
```

Client app:
```
2020/03/28 06:14:06.923500 Starting client (version: 0.3.0)
2020/03/28 06:14:06.923500 Receiving message
2020/03/28 06:14:06.923500 Processing message
2020/03/28 06:14:06.923500 Command: ping
2020/03/28 06:14:06.923500 Sending response
2020/03/28 06:14:06.923500 Receiving message
2020/03/28 06:14:06.926517 Closing client
```

**Comment by dessant** [comment]
`https://stream.watsonplatform.net/speech-to-text/api` is the old API URL. Make sure to select the correct region for the API key in the extension's options.

It's also possible that Firefox tracking protection blocks requests to IBM WATSON. If that's the case, please report the bug to Mozilla.
