### ISSUE TITLE
Something went wrong, Open the browser console for more details - Waterfox/Firefox

### ISSUE THREAD

**Issue by mdelane7** [dessant/buster#153]
**System**

      * OS name: Windows
      * OS version: 10
      * Browser name: Waterfox
      * Browser version: 2020.03.1 (64-bit)

**Extension**

     * Extension version: 0.7.1
     * Client app version: 0.3.0
     * Client app installed successfully: Yes

**Bug description**

     

> First of all Thanks for this wonderful extension. I tried on Chrome Latest Version with latest version of extension, It WORKED.. BUT I need to work in Waterfox. So when I press the Solver Button, It shows exactly like this : http://prntscr.com/rt2to1 ...
> I searched much but couldn't helped it out. 
>      Also tried on Firefox 56. Here is the log : https://pastebin.com/raw/ZZ1YJPHy ( Same Machine )
> Also tried on other fresh machine with Windows Server 2016. Chrome works great but Waterfox or Firefox is giving me the same error everytime.
>     Last of all, Please try to help me to rid from this error and make the extension to be working.
> Sorry For my extreme bad English. Thanks for any kind of suggestions and help.

**Logs**

   Link: https://pastebin.com/raw/zDDsqP1y  (Waterfox 2020.03.1 (64-bit))
   Link 2: https://pastebin.com/raw/ZZ1YJPHy  (Firefox 56)
   Screenshot: http://prntscr.com/rt2rc1  (Waterfox 2020.03.1 (64-bit))
   Screenshot: http://prntscr.com/rt34ew (Firefox 56)

**Comment by dessant** [comment]
Follow this workaround to fix the issue: https://github.com/dessant/buster/issues/141
