### ISSUE TITLE
Request for Buster: Captcha Solver for Humans Windows PC software Tools 64bit.exe file

### ISSUE THREAD

**Issue by Fatema1214** [dessant/buster#156]
**Hello My Dear @dessant Armin Sebastian sir,
I Request for Buster: Captcha Solver for Humans Windows PC software Tools 64bit.exe file.. Please Sir..
I hope you'll consider my request. advance Thanks to you sir.**

**Comment by dessant** [comment]
I'm sorry but I don't understand what you're asking.
