### ISSUE TITLE
Google detected automatic activity

### ISSUE THREAD

**Issue by Cyberavater** [dessant/buster#158]
**System**

* OS name: Android
* OS version: 9
* Browser name: Firefox
* Browser version: 68.7

**Extension**

* Extension version: 0.7.1

* User input simulation: no

**Bug description**

Goggle detects a robot activity.
link: https://gplinks.co/yJxQMms
It doesn't happen on the PC tho.

![Screenshot_20200415-131831](https://user-images.githubusercontent.com/32187927/79310037-1a491e00-7f1d-11ea-9046-d4b614708b13.png)

**Logs**

Browser:
```
Don't know how to get them on android.
```

**Comment by FaySmash** [comment]
I have this problem since two days ago, but only in Waterfox Classic, not Waterfox Current. Seems like Google is testing out a detection system?

**Comment by dessant** [comment]
@FaySmash install the client app as explained on AMO. Search this issue tracker for possible workarounds for temporary blocks.

@Cyberavater, unfortunately Firefox does not support native messaging on Android, nor sending trusted events, so user input cannot be properly emulated there. If you see a temporary block, try clearing browsing data and changing your IP address. If possible for your use case, logging into a Google account may also help.

https://bugzilla.mozilla.org/show_bug.cgi?id=1348213
