### ISSUE TITLE
Please add bypass to hCaptcha system

### ISSUE THREAD

**Issue by ilan0098** [dessant/buster#159]
So my suggestion is , if it's possible please add hCaptcha bypass aswell , since alot of websites started using this service and it will probably be the next generation of captchas , thanks in advance.

**Comment by patrickdrd** [comment]
+1

**Comment by dessant** [comment]
reCAPTCHA abuses users by sometimes gaslighting them into thinking the challenge has not been correctly solved, and serves them new challenges until they abandon the site.

hCAPTCHA so far does not seem to be an abusive service. If that changes, I will consider adding support for it in Buster.

**Comment by Cyberavater** [comment]
> reCAPTCHA abuses users by sometimes gaslighting them into thinking the challenge has not been correctly solved, and serves them new challenges until they abandon the site.
> 
> hCAPTCHA so far does not seem to be an abusive service. If that changes, I will consider adding support for it in Buster.

But it's still annoying tho. Recently hCaptcha replaced almost all Re-captchas.

**Comment by duraki** [comment]
@dessant can we help you with this one? `hCaptcha` is inaccessible for blind people since all we <see> is images captcha and no way to listen to captcha voice and solve the thing. Your extension would help to a great extent.

**Comment by Unknown78** [comment]
hCaptcha challenge is much more difficult than reCaptcha. It expires quickly in terms of hours, need to pay attention more and look very closely to the screen. The image just look very similar to each other. It takes time and concentration unlike reCaptcha,

The most easiest challange on hCaptcha is much more easier in reCaptcha. It's the point that I'm trying to make.
What about the Privacy Pass extension? It has limited number. It quickly runs out.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Issue is tracked at #319.
