### ISSUE TITLE
doesn't work in Ungoogled Chromium

### ISSUE THREAD

**Issue by leedoyle** [dessant/buster#16]
Sorry for this issue, but since your extension can be considered a privacy one (which is also the goal of the Ungoogled  project) and their combination totally makes sense I figured I should leave the feedback.

Apparently it fails to create service workers, there might also be problems with websocket. Possible fixes: enabling needed flags in chrome://flags or patching browser's source code to enable the features needed by Captcha Buser. 
Attaching browser console logs. 

![2019-01-08-030212_470x646_scrot](https://user-images.githubusercontent.com/25978190/50800625-06fadc00-12f2-11e9-97cf-e1aba5cfadc0.png)
![2019-01-08-030202_440x611_scrot](https://user-images.githubusercontent.com/25978190/50800628-09f5cc80-12f2-11e9-80fb-66bdcfde17bb.png)

**Comment by dessant** [comment]
Thanks for the bug report! The service worker errors are not related to the extension, they appear to originate from reCAPTCHA code.

Please describe how the issue manifests itself. Does the reCAPTCHA widget work when you manually solve a challenge? Is the extension button visible? Do you see an error notification? Is there an error in the console originating from script.js?

**Comment by leedoyle** [comment]
1. it does work when solved manually, including the audio mode
2. the extension button is visible, but clicking on it results in what you can see in the picture:
![2019-01-08-070446_618x335_scrot](https://user-images.githubusercontent.com/25978190/50809293-b98f6680-1313-11e9-93ef-8634551cf510.png)
3. yes, there is a warning (see picture) 
![2019-01-08-070618_563x337_scrot](https://user-images.githubusercontent.com/25978190/50809330-ee032280-1313-11e9-9979-c9af2bed29f0.png)

**Comment by dessant** [comment]
I cannot reproduce this issue with Ungoogled Chromium 67 on Windows. Have you changed any default settings or installed extensions that might block fetch requests to google.com? If yes, try with a default browser profile and see if the issue is still reproducible.

**Comment by leedoyle** [comment]
Issue disappeared in 71.0.3578.98, closing.
