### ISSUE TITLE
Try again later!! error or detected

### ISSUE THREAD

**Issue by hieunhoo** [dessant/buster#161]
Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit "our help page"
![image](https://user-images.githubusercontent.com/48126508/79680177-02cca680-8237-11ea-80c2-d99f4c816142.png)

**System**

* OS name: Windows 10
* OS version: 1909
* Browser name: Cent Browser (Chromium)
* Browser version: Version 4.1.7.182 (The official version) (64 bit) (Chromium 78.0.3904.108)

**Extension**

* Extension version: 0.7.0

* User input simulation: yes

* I don't know which client

**Bug description**

I used Buster to get that warning
**Logs**

```
Browser:gpt.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
openchrome.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
plugin.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
apu.php:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
gpt.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v3.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by Bluejanis** [comment]
I have the same issue.
It looks like it Googles ReCaptcha audio challenge is broken.
The visual challenge works, but the audio challenge never did as far as I know.

In [this issue ](https://github.com/dessant/buster/issues/56#issuecomment-481655521) it looks like _dessant_ only had a temporary block, while mine seems permanent.

**Comment by icynstant** [comment]
> In [this issue ](https://github.com/dessant/buster/issues/56#issuecomment-481655521) it looks like _dessant_ only had a temporary block, while mine seems permanent.

Did you fix that?
