### ISSUE TITLE
Crashing entirely 

### ISSUE THREAD

**Issue by PhabeJewell** [dessant/buster#162]
buster is no longer working I tried reinstalling but it still keeps crashing

![image](https://user-images.githubusercontent.com/34112085/79698074-0f0f2e80-824c-11ea-88d2-907f0387f34d.png)

**Comment by dessant** [comment]
Sounds like a browser bug, there was no recent update that would have suddenly caused a startup crash in the background script.

**Comment by Bluscream** [comment]
Translation to simple-man-language: Stop using secure browsers and start giving your sensitive data to the devs of supported browsers

**Comment by dessant** [comment]
@Bluscream, this nonsense is not welcome here. The extension works with Brave, and if there is a bug within the browser that has started to cause a crash, you should notify them by opening a bug report.

**Comment by Bluscream** [comment]
As if they wouldn't say "contact the addon dev to fix his addon" instead and @PhabeJewell ends up in a "who is responsible" loop

**Comment by dessant** [comment]
This bug has been fixed in Brave, learn more about the issue here: https://github.com/dessant/buster/issues/165#issuecomment-624219437
