### ISSUE TITLE
hCaptcha Compatibility 

### ISSUE THREAD

**Issue by paultommy** [dessant/buster#163]
I've been seeing hCaptcha a lot recently (official site here https://www.hcaptcha.com/) and I was wondering if hCaptcha compatibility could be added to Buster.

**Comment by ste03** [comment]
I found that if you click on accessibility on the bottom of the hCaptcha it will add a cookie to your browser that bypasses the check

**Comment by rickninja765** [comment]
> I found that if you click on accessibility on the bottom of the hCaptcha it will add a cookie to your browser that bypasses the check  

Thanks Man It works.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Issue is tracked at #319.
