### ISSUE TITLE
Buster crashed on windows server 2019

### ISSUE THREAD

**Issue by mastermks** [dessant/buster#164]
**System**

* OS name: [ Windows server 2019]
* Browser name: [e.g. Chrome, Firefox and Brave]
* Browser version: [last version]

**Extension**

* Extension version: [ Buster 0.7]

**Bug description**
* hi and thank you very much for your nice addon.

i have a issue on windows server 2019, i have tested with chrome, brave and firefox and with 3 differents VM. all time Buster start and after 1 or 2 seconds  hi have a popup ( buster: Captcha for Humains has crashed. Click this balloon to reload the extension )

can you help me to find a solution or make a fixe.

best regards

**Comment by dessant** [comment]
Which Firefox version are you using exactly? Please make a sreenshot when you see that error message in Firefox.

**Comment by dessant** [comment]
This bug has been fixed in Brave, learn more about the issue here: https://github.com/dessant/buster/issues/165#issuecomment-624219437
