### ISSUE TITLE
Error: AudioContext is not defined

### ISSUE THREAD

**Issue by talhaprogrammer** [dessant/buster#167]
**System**

* OS name: Linux Lite 4.8 (based on Ubuntu 18.04-bionic)
* OS version: Ubuntu 18.04-bionic
* Browser name: Firefox
* Browser version: 68.7.0esr 64-bit

**Extension**

* Extension version: 0.7.1 (Updated May, 8, 2020)

* User input simulation: no

**Bug description**
I am receiving this exception while solving captcha using your awesome Buster Extension for firefox.

**Logs**
Unhandled promise rejection Error: "AudioContext is not defined".

Browser:
![image](https://user-images.githubusercontent.com/46928648/81374013-a06d1480-9117-11ea-9459-0af6691a0a17.png)

**Comment by dessant** [comment]
It's possible that you've disabled the Web Audio API in about:config, or you're hitting a bug in Firefox. It's unlikely that this is a bug within the extension, AudioContext is a browser API that should always be available in the background script.

You can test the Web Audio API with this demo to see if you get similar errors: https://codepen.io/Rumyra/pen/qyMzqN/

Try asking for help on https://discourse.mozilla.org.

**Comment by talhaprogrammer** [comment]
Thanks brother for your time and valuable insight.

I really appreciate your efforts,
