### ISSUE TITLE
Firefox 76.0 : Module does not work in if resistfingerprinting is enabled

### ISSUE THREAD

**Issue by thebigmira** [dessant/buster#168]
* OS name: Windows
* OS version: Version 10.0.18363 Numéro 18363
* Browser name: Firefox
* Browser version: 76.0
* Extension version: 0.7.1
* User input simulation: yes
* Client app version: 0.3.0
* Client app installed successfully: yes

**Bug description**
Module does not work in Firefox 76.0 if resistfingerprinting is enabled. By clicking on the yellow logo, the mouse arrow points to the upper left corner of the screen. It is necessary to temporarily disable resistfingerprinting for the captcha resolver to work. 

**Logs**
Invalid chrome URI: / 3
TypeError: PrecompiledScript.executeInGlobal: Argument 1 is not an object. 3 ExtensionContent.jsm:567:25
target is null MessageManagerProxy.jsm:171
    addListeners resource://gre/modules/MessageManagerProxy.jsm:171
    MessageManagerProxy resource://gre/modules/MessageManagerProxy.jsm:34
    ProxyContextParent resource://gre/modules/ExtensionParent.jsm:573
    ContentScriptContextParent resource://gre/modules/ExtensionParent.jsm:659
    recvCreateProxyContext resource://gre/modules/ExtensionParent.jsm:871
    recvCreateProxyContext self-hosted:844
    _recv resource://gre/modules/ConduitsChild.jsm:78
    receiveMessage resource://gre/modules/ConduitsParent.jsm:333
sender.tab is undefined 2 MessageChannel.jsm:1019
    promise resource://gre/modules/MessageChannel.jsm:1019
this.window.gBrowserInit is undefined 2 ext-browser.js:1130
    get activeTab chrome://browser/content/parent/ext-browser.js:1130
    candidates chrome://extensions/content/parent/ext-tabs-base.js:1969
    InterpretGeneratorResume self-hosted:1151
    next self-hosted:1099
    query chrome://extensions/content/parent/ext-tabs-base.js:1988
    next self-hosted:1099
    from self-hosted:505
    query chrome://browser/content/parent/ext-tabs.js:960
    query self-hosted:844
    result resource://gre/modules/ExtensionParent.jsm:960
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:592
    result resource://gre/modules/ExtensionParent.jsm:960
    callAndLog resource://gre/modules/ExtensionParent.jsm:922
    recvAPICall resource://gre/modules/ExtensionParent.jsm:959
    InterpretGeneratorResume self-hosted:1151
    AsyncFunctionNext self-hosted:693
XHRPOSThttp://127.0.0.1:23119/connector/ping
XHRPOSThttp://127.0.0.1:23119/connector/ping
XHRGEThttps://github.com/settings/replies?context=new_issue
[HTTP/1.1 200 OK 935ms]

GEThttps://profile.accounts.firefox.com/v1/profile
[HTTP/1.1 304 Not Modified 574ms]

XHRGEThttps://sync-804-us-west-2.sync.services.mozilla.com/1.5/136561457/info/collections
[HTTP/1.1 200 OK 688ms]

XHRGEThttps://sync-804-us-west-2.sync.services.mozilla.com/1.5/136561457/info/configuration
[HTTP/1.1 200 OK 172ms]

XHRGEThttps://sync-804-us-west-2.sync.services.mozilla.com/1.5/136561457/storage/clients?full=1&limit=1000
[HTTP/1.1 200 OK 173ms]

XHRPOSThttps://sync-804-us-west-2.sync.services.mozilla.com/1.5/136561457/storage/tabs?batch=true&commit=true
[HTTP/1.1 200 OK 175ms]

XHRPOSThttp://127.0.0.1:23119/connector/ping
XHRPOSThttp://127.0.0.1:23119/connector/ping

**Client app:**
2020/05/08 07:25:06.934987 Starting client (version: 0.3.0)
2020/05/08 07:25:06.934987 Receiving message
2020/05/08 07:25:06.934987 Processing message
2020/05/08 07:25:06.934987 Command: ping
2020/05/08 07:25:06.934987 Sending response
2020/05/08 07:25:06.935987 Receiving message
2020/05/08 07:25:06.976990 Processing message
2020/05/08 07:25:06.976990 Command: moveMouse
2020/05/08 07:25:06.976990 X: -59, Y: 1
2020/05/08 07:25:07.183091 Sending response
2020/05/08 07:25:07.183091 Receiving message
2020/05/08 07:25:07.294752 Processing message
2020/05/08 07:25:07.294752 Command: clickMouse
2020/05/08 07:25:07.316755 Sending response
2020/05/08 07:25:07.316755 Receiving message
2020/05/08 07:25:17.329874 Closing client

**Comment by JimmyBardon** [comment]
Yup the same problem i am facing.

**Comment by MrGeorgen** [comment]
Me too

**Comment by diogo098** [comment]
you need to update to version 0.72 and you will be fine 😊

**Comment by thebigmira** [comment]
Still the same problem, even after updating to version 0.72

**Comment by dessant** [comment]
The feature masks the screen size, window size, scale and zoom level, so the extension cannot reliably calculate the button position relative to the screen. This can be fixed by checking if resistFingerprinting is enabled, and switching to keyboard navigation instead of moving the mouse.

Checking if the option is enabled requires a new permission: privacy.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites

**Comment by dessant** [comment]
Since resistFingerprinting is still experimental, we won't be requesting a new permission for it. A new option was added that needs to be turned on from the extension's options to always navigate using a keyboard.

The description of the add-on on AMO will be expanded with this paragraph:
> Anti-fingerprinting prevents the client app from moving the mouse as expected. If privacy.resistFingerprinting has been turned on from about:config, make sure to also enable keyboard navigation from the extension's options.
