### ISSUE TITLE
Hope it will support capture on Greasy Fork

### ISSUE THREAD

**Issue by Smoke-N-Mirrors** [dessant/buster#169]
**Is your feature request related to a problem? Please describe.**

On <a href='https://greasyfork.org/en'>Greasyfork</a>, When you sign up or post a script, it will ask you to do a capture, however, this extension doesn't display an icon on it, namely, it doesn't work. **Worse still, capture on Greasyfork is Extremely difficult to pass, I usually do three times until it lets me pass!**

Hope it will auto-complete capture on <a href='https://greasyfork.org/en' target='_blank'>Greasyfork</a>

**Comment by dessant** [comment]
I've just checked, it does work on Greasyfork. Are you using Opera?
