### ISSUE TITLE
Request based?

### ISSUE THREAD

**Issue by iosdeveloper** [dessant/buster#17]
Did you look into accessing a new mp3 and submitting the answer using requests instead of using the DOM? Then the only DOM manipulation would be setting the value of `g-recaptcha-response`. This would possibly avoid #2 (automation detection).

**Comment by dessant** [comment]
The block does not seem to be triggered by DOM manipulation, and it also happens without the extension. I don't see how submitting the response using requests would help, blocking usually happens way before that, and the user input events would also be missing.
