### ISSUE TITLE
Something went wrong, the extension has stopped working

### ISSUE THREAD

**Issue by dessant** [dessant/buster#173]
The error is caused by a breaking change in Wit Speech API, and it has been fixed in version 0.7.2. The latest version has been published for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-solver/) and [Edge](https://microsoftedge.microsoft.com/addons/detail/admkpobhocmdideidcndkfaeffadipkc).

The update was also submitted to the Chrome Web Store, but it could take from days to months before it is reviewed by Google.

If you must use Chrome, you could grab the latest release and install it in developer mode until the extension listing is updated on the Chrome Web Store.

Latest release: https://github.com/dessant/buster/releases/tag/v0.7.2

Guide for installation in Chrome: https://stackoverflow.com/a/24577660

**Comment by duraki** [comment]
Thank you! That was faaaaast haha :) <3

**Comment by UltraSaiyajin** [comment]
Hello,is it possible to have a crx file for your extension plz?

**Comment by feby08** [comment]
Something went wrong and it can't solve captcha anymore please help

**Comment by hbarsaiyan** [comment]
> Something went wrong and it can't solve captcha anymore please help

working fine here update to the latest version

**Comment by diegoan99** [comment]
> Something went wrong and it can't solve captcha anymore please help

upgrade to latest version is ok

**Comment by dessant** [comment]
@UltraSaiyajin, a crx file is just a zip file, follow the instructions above to download the zip package of the latest release for Chrome, then change the file extension.

**Comment by UltraSaiyajin** [comment]
@dessant Thanks a lot man!! Your extension is lit! Keep going!!

**Comment by MoatazNassar** [comment]
I installed the add-on manually on Google Chrome temporarily and it works great now ... We are awaiting the addition of version v0.7.2 on the Chrome market ... Thanks to the developer for the speedy response

**Comment by MoatazNassar** [comment]
Waiting for the new version to be added to the Google Chrome Market until we install the extension on the Android phone in a browser yandex
Thanks again to the developer for his effort to benefit people ☺☺☺

**Comment by hbarsaiyan** [comment]
> Waiting for the new version to be added to the Google Chrome Market until we install the extension on the Android phone in a browser yandex
> Thanks again to the developer for his effort to benefit people ☺☺☺
PS: If i were you i would use Kiwi Browser which is an open source chromium browser for Android with extension support

**Comment by headcreep** [comment]
There is still no way to download the crx file for Chrome users, that is why UltraSaiyajin, myself included came here to ask for a link to the crx file.

**Comment by headcreep** [comment]
The zip file downloads from this site will.not install for kiwi, and the fine size seems peculiar. On the kiwi discord server a user there repackaged the file and the difference in size of the 0.7.2 version that does install is significantly larger.  The one downloaded here is 240kb vs the one that does install from discord is 845kb. Needless to say I was not able to install the package from the link provided here on github on the latest kiwi browser.

**Comment by dessant** [comment]
@headcreep, you have downloaded the wrong zip file from the packages listed on the release page, this is the correct package for Kiwi Browser: https://github.com/dessant/buster/releases/download/v0.7.2/buster_captcha_solver_for_humans-0.7.2-chrome.zip

**Comment by headcreep** [comment]
This is precisely why I cannot stand/hate github, there's always confusion surrounding the correct file for download. The link provided at the top of the post brought me to the core page yesterday, where you select either clone or download zip. It's settled then, thanks for the help getting us the proper extension and appreciate you having maintained the extension.

**Comment by headcreep** [comment]
Had I see this ![May-19,-2020-9-37-05-PM](https://user-images.githubusercontent.com/58980201/82395204-00699200-9a19-11ea-846f-14354a95fadf.jpg)
yesterday, I suppose I would not have had any problems. Oh well. Chalk it up to a glitch in the matrix.

**Comment by kevin1One** [comment]
You can also change Speech Service to IBM Watson and register and get a free API key and it works.

**Comment by rzumer** [comment]
It is still broken for me on Waterfox with the console message "Error: (intermediate value).text is undefined".

**Comment by dessant** [comment]
@rzumer, the API does not seem to provide the `text` property when there is no detected speech, you've most likely got an audio challenge that could not be solved. Buster 0.7.3 will correctly show a notification about the missing solution instead of an error: https://github.com/dessant/buster/commit/8a54f1fdcec03b2860a60e4f4bb521e80f441b10

**Comment by rzumer** [comment]
That's wrong, I have to solve everything manually because it fails every single time.

**Comment by dessant** [comment]
@rzumer, are you using Waterfox Classic?

**Comment by rzumer** [comment]
Yes.

**Comment by dessant** [comment]
@rzumer, that's an old Firefox bug that is not related to this issue, see this issue for a workaround: https://github.com/dessant/buster/issues/141#issue-562983753

**Comment by rzumer** [comment]
I do have `dom.promise_rejection_events.enabled` set to true, so I don't think it's the same issue, but I guess it is likely some other regression on older Firefox.

**Comment by dessant** [comment]
@rzumer, I have just tested 0.7.2 and 0.7.3 with Waterfox Classic. For some reason the latest version of the browser does not correctly process the audio file, and Wit cannot detect any speech in it. 0.7.3 no longer throws an exception due to the fix linked above, but always notifies you that the challenge could not be solved. In Waterfox Current the extension works as expected and solves the challenge.

Is there a specific extension that is keeping you on Waterfox Classic? In any case, I'm going to drop support for Firefox 56, it has been broken for a long time, and there is no longer a usable workaround for it. If someone steps up to provide patches, we could reenable support for Waterfox Classic in the future.

**Comment by rzumer** [comment]
Thanks for looking into it. I don't have any more XUL extensions so will probably upgrade to the "current" branch to fix it.

**Comment by apfsx** [comment]
@dessant Finally not crashing anymore, thank you so much for the update. but I can't get Simulate User Input to work, unchecking Simulate User Input will make it solve & fill captchas but this tends to fail more often (requires multiple solves). I have reinstalled the latest client app companion. Any ideas?

**Comment by dessant** [comment]
@apfsx, I don't know why would it work without the client app better on your part, it should be the opposite.

**Comment by dessant** [comment]
Version 0.7.3 is now live on the Chrome Web Store. Opera has not published any of my extensions in the past 6 months, so it's best to install it directly from the Chrome Web Store if you're using Opera.

**Comment by apfsx** [comment]
> @apfsx, I don't know why would it work without the client app better on your part, it should be the opposite.

My bad I did a bad job explaining. Simulating user input does not work, unchecking simulate user input works as in it will fill quickly.

**Comment by phocks** [comment]
Still broken for me. Firefox latest version, on Arch Linux.
