### ISSUE TITLE
Support for Hcaptcha

### ISSUE THREAD

**Issue by Ignaciox** [dessant/buster#176]
Recently there has been this wave of websites switching to Hcaptcha and obviously this is more of an haggle to solve captcha's on then google ironically. the thing designed to keep bots out keeps humans at bay. I wanted to see if it were possible for you to implent some sort of way to get buster to work on hcaptcha aswell. I understand that this is something you work on in your free time and that you don't have a obligation to provide these sort of services to the community,

**Comment by diegoan99** [comment]
> Recently there has been this wave of websites switching to Hcaptcha and obviously this is more of an haggle to solve captcha's on then google ironically. the thing designed to keep bots out keeps humans at bay. I wanted to see if it were possible for you to implent some sort of way to get buster to work on hcaptcha aswell. I understand that this is something you work on in your free time and that you don't have a obligation to provide these sort of services to the community,

you can't because buster captcha uses api voice audio technology

**Comment by Ignaciox** [comment]
ah crap didn't know that i thought there was a voice option on hcaptcha. my bad

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Issue is tracked at #319.
