### ISSUE TITLE
 Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by Marius-Sheppard** [dessant/buster#181]
**System**
* OS name: Windows 
* OS version: 10 
* Browser name: Chrome
* Browser version: 83.0.4103.61 (Official Build) (64-bit)

**Extension**
* Extension version:  0.7.0
* User input simulation: no

**Bug description**
I installed the extension on Chrome and tested it, then this happened:
![image](https://user-images.githubusercontent.com/49373200/82592946-5883ce00-9baa-11ea-921e-8be7deb1c77d.png)
![image](https://user-images.githubusercontent.com/49373200/82592852-34c08800-9baa-11ea-93f2-749800fd21d2.png)

**Comment by dessant** [comment]
The bug has been fixed in version 0.7.2, see this issue for details: https://github.com/dessant/buster/issues/173
