### ISSUE TITLE
Buster client installer doesn't recognize Buster extension as being installed on Ubuntu 18.04

### ISSUE THREAD

**Issue by Xenoslyce** [dessant/buster#183]
**System**

* OS name: Ubuntu
* OS version: 18.04
* Browser name: Firefox Developer Edition
* Browser version: 77.0b8

**Extension**

* Extension version: 0.7.2

* User input simulation: yes

* Client app version: 0.3.0
* Client app installed successfully: no

**Bug description**

The Buster client installer isn't recognizing Buster as installed, and just gives me a message of "Open this page in a browser with the latest version of Buster installed."
1. Install Firefox Developer Edition
2. Install Buster
3. Install Buster client
4. Set Buster client as executable
5. ./buster-client-setup-*
6. Profit
**Logs**

Browser:
```
// Unable to get logs
```

Client app:
```
//  Unable to locate log file (despite searching entire drive for buster-client-log.txt)
```

**Comment by dessant** [comment]
I have tested with Firefox Developer Edition 77.0b8 and the installation page was shown as expected. Buster opens the installation page in the default browser, and if needed, you can visit that URL from a different browser and profile. Are you sure the installation page was opened with a browser profile where Buster was installed?

**Comment by Xenoslyce** [comment]
Yes. All it does is send me to the URL "file:///home/Procyon/.cache/kioexec/krun/13677_0/setup"

**Comment by Xenoslyce** [comment]
Turns out this is a KDE issue but I'm unsure how to fix it.

**Comment by dessant** [comment]
Sorry, but I don't know how to help you either with KDE bugs.
