### ISSUE TITLE
Buster "Something went wrong, Open the browser console for more details."

### ISSUE THREAD

**Issue by KingStan8989** [dessant/buster#188]
**System**

* OS name: Debian
* OS version: Kali GNU/Linux Rolling
* Browser name: Chrome
* Browser version: 79.0.3945.117

**Extension**

* Extension version: 0.7.0

* User input simulation: no

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

when I press the orange button after I clicked a reCAPTCHA it gave me this response:
Buster "Something went wrong, Open the browser console for more details."

**Logs**

Browser:
```
Error: Cannot read property 'trim' of undefined
script.js:1 Uncaught (in promise) Error: Cannot read property 'trim' of undefined
    at g (script.js:1)
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
https://github.com/dessant/buster/issues/173
