### ISSUE TITLE
[Feature Request] Focus click elements

### ISSUE THREAD

**Issue by narcolepticinsomniac** [dessant/buster#19]
I get that throwing too many automated clicks at it will get you blocked, plus leaving the user interaction probably helps adhere to the TOS. Short of auto-clicks, it'd be much more convenient if the initial checkbox to launch the captcha was auto-focused (probably utilizing `preventScroll: true`), and also the subsequent buster buttons. Not only would it be quicker in general, but it'd be even more accessibility friendly in terms of users navigating with on-screen keyboards or remote controls.

**Comment by narcolepticinsomniac** [comment]
Making assumptions that don't pan out is kinda my specialty, but I get what you're saying. Focusing the buttons would be great though, so I'm glad you're considering it. Great extension btw, thanks.

**Comment by devcline** [comment]
Any news on this request? It would be good to add some delay to the resolve, automate clicking and some anti google blocking preventions. thanks

**Comment by devcline** [comment]
How to make a `solver-button` Id autoclick?

**Comment by SebTota** [comment]
Similar question as devcline. Would it be possible to start the solve once someone has clicked the captcha checkbox or would that trigger Googles bot detection?

**Comment by dessant** [comment]
Hi folks, please don't post unrelated or already answered questions in issues. The feature request template may also answer some of them.

**Comment by dessant** [comment]
I thought sometimes about this issue in the past year, and my current stance is that it would be better to not touch the focus at all, not even in the challenge widget. Moving the mouse to reach the extension button or navigating to it using the keyboard creates natural user input events that help increase the success rate of the extension.
