### ISSUE TITLE
Opera extension is outdated and broken

### ISSUE THREAD

**Issue by floppyD** [dessant/buster#191]
Did you guys drop official support for Opera? The extension from Opera addons is stuck on 0.6.0 (just a few days from being a year old build) and is now broken by the looks of it.

**Comment by dessant** [comment]
See this comment for details: https://github.com/dessant/buster/issues/173#issuecomment-636020450

**Comment by floppyD** [comment]
Maybe you should remove it from the readme since it's no longer working and could cause confusion.
