### ISSUE TITLE
Always fail to add a button

### ISSUE THREAD

**Issue by Smoke-N-Mirrors** [dessant/buster#194]
**System**

* OS name: windows 10
* OS version: 1909
* Browser name: chrome & firefox
* Browser version: 83.0.4103.97 (Official Build) (64-bit) & 77.0.1

**Extension**

* Extension version: [e.g. 1.0.0]

* User input simulation: yes

* Client app version: 0.3.0
* Client app installed successfully: yes
**Bug description**

This add-on is powerful but it doesn't work on all sites, such as greasyfork.org, https://www.52pojie.cn/member.php?mod=logging&action=login, and so on... can you change a method to detect reCAPTCHA?

**Comment by Smoke-N-Mirrors** [comment]
The extension is not working, so I have no logs

**Comment by Smoke-N-Mirrors** [comment]
I found that it always appears in an iframe with an <input id='recaptcha-token'>, can you detect it per second? It doesn't take many resources.

**Comment by dessant** [comment]
Are you visiting these sites from Mainland China without a VPN? Though if that would be the cause, the extension should never work, not just on some sites.

Please check if reCAPTCHA is loading correctly on the pages below, it should only work for the second link.

https://jsfiddle.net/kqb198eo/

https://jsfiddle.net/kqb198eo/1/

**Comment by Smoke-N-Mirrors** [comment]
In https://jsfiddle.net/kqb198eo/1/ it worked and in https://jsfiddle.net/kqb198eo/ it failed. Why? By the way, I always use a VPN

**Comment by dessant** [comment]
Visit https://jsfiddle.net/kqb198eo/ in Firefox and open the reCAPTCHA challenge, but do not solve it. Open the Inspector (Ctrl+Shift+C) and type `bframe` in the small search box, then press enter. It should find and highlight an iframe element. Please copy the URL (src attribute) of the iframe or screenshot it.

I'm guessing Google serves the challenge from a different host for you, and we need to see which one is it.

**Comment by Smoke-N-Mirrors** [comment]
<code>src="https://www.recaptcha.net:443/recaptcha/api2/bframe?hl=en&v=2diXFiiA9NsPIBTU15LG6xPf&k=6LcgSAMTAAAAACc2C7rc6HB9ZmEX4SyB0bbAJvTG&cb=jkmp2mz9xzfs"</code>

**Comment by dessant** [comment]
52pojie.cn loads the reCAPTCHA JS from recaptcha.net to bypass the firewall, as it is [recommended](https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally) by Google. When visited from the EU, the challenge iframe will still load from google.com, as usual, but for some reason for you it loads as if the service would detect that google.com is being blocked, so it loads the assets from recaptcha.net instead, and the extension is not configured to work on that host.

I'll release a fix today. Btw, which VPN service did you use and in which country was the VPN server located?

**Comment by Smoke-N-Mirrors** [comment]
Thanks, I really appreciate your help. I use <a href="https://github.com/baacloud/url">Baacloud</a>, it has servers such as the USA, Taiwan, Honk Kong, Russian, and so on.

**Comment by dessant** [comment]
The issue has been fixed in version 1.0.1. The update has been published for Firefox, and it should also be reviewed and published for Chrome in the next few days.
