### ISSUE TITLE
Not available in China

### ISSUE THREAD

**Issue by GreatWriter** [dessant/buster#197]
![A16B103E-4F25-4A6C-BC64-ECAA97FCD74A](https://user-images.githubusercontent.com/57381087/84567059-b9b55080-ada8-11ea-8e42-e204052fe097.png)
<img width="595" alt="QQ20200613-190216@2x" src="https://user-images.githubusercontent.com/57381087/84567062-bfab3180-ada8-11ea-8065-f6ff59baf14d.png">

**Comment by GreatWriter** [comment]
Domain name problem. Please join www.recaptcha.net

**Comment by dessant** [comment]
Hi, this issue has been fixed in master, a new version will be released in the next few days.

https://github.com/dessant/buster/issues/194

**Comment by dessant** [comment]
The issue has been fixed in version 1.0.1. The update has been published for Firefox, and it should also be reviewed and published for Chrome in the next few days.
