### ISSUE TITLE
Artificial blocking of pre-Firefox 68 versions

### ISSUE THREAD

**Issue by asdf2345** [dessant/buster#200]
**System**

* OS name: Windows
* OS version: 7
* Browser name: Waterfox Classic (Firefox 56 fork)
* Browser version: 2020.06

**Extension**
* Extension version: 1.0.1
* User input simulation: No

**Bug description**
On the Firefox addons site, it says "Works with Firefox 68.0 and later", despite this, I installed the addon on Waterfox Classic, which is a Firefox 56 fork, and it works fine

**Comment by dessant** [comment]
I have received several bug reports about the extension not working on Waterfox Classic, and last time I've tested, it was still broken. See this issue for details: https://github.com/dessant/buster/issues/173#issuecomment-635426985

**Comment by asdf2345** [comment]
> I have received several bug reports about the extension not working on Waterfox Classic, and last time I've tested, it was still broken. See this issue for details: [#173 (comment)](https://github.com/dessant/buster/issues/173#issuecomment-635426985)

It works fine for me, I could set up a new browser profile and see if it works there, but it worked with my old profile without issue.

**Comment by asdf2345** [comment]
Apparently Google says this about my VM "Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page"

So I can't test right now

**Comment by asdf2345** [comment]
Tried it again on a fresh profile, and it worked, all I did was change the promise rejection boolean, install the addon, restart the browser, and try the captcha, and it worked
