### ISSUE TITLE
Development Question

### ISSUE THREAD

**Issue by tonebiclas** [dessant/buster#202]
Hello, i just cloned the repo to practice little bit, build and start works but when it comes to see my code changes i need to build:chrome for example in another console and reload manually pressing R in the other? Seems a bit boring for me, am i missing something? Im relative new to this setups.

**Comment by dessant** [comment]
Yes, that's how I test changes too. You could experiment with [this](https://github.com/rubenspgcavalcante/webpack-extension-reloader) reloader or something similar, but I don't know how well it works, and the extension is only partially built by webpack, there are other tasks executed by gulp.
