### ISSUE TITLE
Can't download .xpi version 0.7.2 anymore

### ISSUE THREAD

**Issue by lost2time** [dessant/buster#203]
Hi, wasn't sure where else to put this, but I collect Firefox addons and I originally had a copy of buster_captcha_solver_for_humans-0.7.2-an+fx.xpi but my flash drive died on me and I lost a bunch of stuff, this being one of the items. I checked the original link ([here](https://addons.cdn.mozilla.net/user-media/addons/1013715/buster_captcha_solver_for_humans-0.7.2-an+fx.xpi)) but I get a 404, and it's not listed in the versions on the [FFox addon page](https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-solver/versions/).

I looked at the releases here but did not see any .xpi files. Please forgive me, I'm not a programmer so I am not at all familiar with compiling things to make a finished product. The most I could do was rename the .zip to .xpi, but then I noticed it was considered an unsigned extension.

I am just wondering if any of you still have a copy of buster_captcha_solver_for_humans-0.7.2-an+fx.xpi that you could send me. This is a great extension, hence why I try to save every version of it.

Thanks

**Comment by dessant** [comment]
Older versions are usually disabled to prevent people from installing broken versions. I have temporarily reenabled 0.7.2 for you to archive it, please download the package in the next 24 hours.

**Comment by lost2time** [comment]
Thank you for that. I was almost about to pay for data recovery! Is it that much of an issue that the older versions are still available in the Firefox addons store? I think their message warns most users pretty well:

> Be careful with old versions! These versions are displayed for testing and reference purposes.
> 
> You should always use the latest version of an add-on.

**Comment by dessant** [comment]
Many people don't read warnings or understand the difference, and the burden of support usually falls on me when things go wrong, so it's best to limit the possibility of mistakes.

Checking out GitHub releases is also useful for preservation purposes, you can find the extension packages attached as assets. The same packages are uploaded to extension stores, and they only modify packages to add a signature before publishing.

https://github.com/dessant/buster/releases

**Comment by lost2time** [comment]
Is there a way to add this signature myself? I don't really know much about signatures, and if I were to guess, I would not be able to replicate the same signature Mozilla/Google/etc. is using.

Sorry if this is straying from the topic, I just was curious if you happened to know.

**Comment by dessant** [comment]
No, only they have the private key to sign the extension.

**Comment by lost2time** [comment]
Thanks for the reply
