### ISSUE TITLE
Firefox 53.0 and Buster Captcha Version 0.7.3

### ISSUE THREAD

**Issue by Marketoftrade** [dessant/buster#205]
Hello, i have a problem with Firefox 53.0 and Buster Captcha Version 0.7.3.
How can i solve it?
[https://hostr.co/file/970/JBq4TCdADurh/prob.png](https://hostr.co/file/970/JBq4TCdADurh/prob.png)
I can't update my firefox i have to use only firefox 53.0
Thanks

**Comment by dessant** [comment]
This workaround may help: https://github.com/dessant/buster/issues/141
