### ISSUE TITLE
Something went wrong...

### ISSUE THREAD

**Issue by SWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMI** [dessant/buster#206]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Chromium
* Browser version: 83.0.4103.116 

**Extension**

* Extension version: 1.0.1

* User input simulation: no

**Bug description**

I know #173 has this same problem but it doesn't seem to have been entirely fixed (at least on my machine running Chromium 83). I get the "Something went wrong..." popup. Console shows:
```
Uncaught (in promise) Error: Failed to fetch
    at g (script.js:1)
```
This is with the Wit Speech API (Managed) option. 

With the IBM Watson API (Dallas) using an API key I generated myself, I get
```
Uncaught (in promise) Error: API response: 401, {"code":401, "error": "Unauthorized"}
    at g (script.js:1)
```
I assume this means my API key didn't work and I also need my auth token. How do I input my token?

**Comment by dessant** [comment]
I can't reproduce the issue. Chromium stable is not distributed by Google for Windows. Could you point to a download link for the browser you installed? It's also possible that a different extension is interfering with the requests.

**Comment by SWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMI** [comment]
Ah, if this isn't reproducible then I know the reason it doesn't work. It's my pi-hole (wit.ai pings facebook). Thanks for letting me know that it's on my end.

**Comment by ltGuillaume** [comment]
Really? I need to allow a connection to Facebook in order to get this working again (with Wit)? Ugh... Isn't SpeechRecognition via Web Speech a possibility? No need for an API key... https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

**Comment by dessant** [comment]
It think they were using an overzelaous filter list in Pi-hole. Wit.ai is owned by Facebook, but the API request is a single call to https://api.wit.ai, there are no requests to facebook.com. For example, the built-in tracking protection in Firefox blocks https://*.speech-to-text.watson.cloud.ibm.com/ for some reason, making the extension fail when the IBM Watson Speech to Text API is used. The Web Speech API is only available on Chrome, and it uses a remote Google service under the hood.

**Comment by ltGuillaume** [comment]
Thanks for the info, that should be enough to make it work for me again 😃 As for the Web Speech API, I should've researched it more, sounds like it's not a viable alternative (yet). Thanks!

**Comment by dessant** [comment]
@ltGuillaume, do you know which filter list blocks wit.ai? I'd like to document it in the wiki.

**Comment by ltGuillaume** [comment]
Unfortunately, no. In my case, my VPN's DNS filter blocks it, but these lists are not publicly available. The problem isn't api.wit.ai, though, it's the wit-edge.c10r.facebook.com etc. (probably CNAME cloaking).

**Comment by dessant** [comment]
They indeed CNAME it to wit-edge.c10r.facebook.com. @ltGuillaume, thanks for the pointer!

**Comment by ltGuillaume** [comment]
Unfortunately, whitelisting wit-edge.c10r.facebook.com didn't solve the issue for me. I always get the "captcha could not be solved" popup now. When trying to debug the add-on, there somehow wasn't anything in the console.

I should note that I'm using Waterfox 56 as my primary browser, so it could have something to do with Buster using newer API calls.

**Comment by dessant** [comment]
@ltGuillaume, Waterfox/Firefox 56 is no longer supported, but you could try [this](https://github.com/dessant/buster/issues/141) workaround, it helps sometimes.

**Comment by ltGuillaume** [comment]
@dessant Thanks, I think it's why I already had set `dom.promise_rejection_events.enabled` to `true`, but as you stated, it doesn't work anymore. I hadn't seen that comment before. Too bad... 😟
