### ISSUE TITLE
download websites

### ISSUE THREAD

**Issue by fez4prez** [dessant/buster#209]
hey mate great mod hahaha! wish I knew about it when you first started!! :o

quick question. on android app sites, apks are uploaded elsewhere. those upload file websites know your mod is in play and gives error saying too may requests or something try again later.

only recently started happening a week ago. on firefox android 78.0.1.

any ideas?
thanks

**Comment by dessant** [comment]
User input simulation is not available on Android, but you can follow some of the other tips below.
