### ISSUE TITLE
Use as API

### ISSUE THREAD

**Issue by duraki** [dessant/buster#21]
Great browser extension! The author work is fabulous.

It would be awesome if we could use `Buster` as a library or API interface. This would allow us to reuse the component in different ways.

Any plans for that?

**Comment by dessant** [comment]
Thanks, I'm happy you like the extension! Releasing it as a library is outside the scope of this project. Buster's goal is to help people pass challenges as they face them during browsing. A library would aid software automation in ways that would work against this goal.
