### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by headcreep** [dessant/buster#214]
Update ver 1.0.1 no longer works.  After it is solved and populates the field, the window disappears before verification and you are prompted to solve it again, result is a loop of unsolvable captcha

**System**

* OS android nougat
* OS version 7.1.1
* kiwi browser
* chromium 77.0.3865.92 (Official Build) (64-bit)

**Extension**

* Extension version 1.0.1

* User input simulation: [ no]

* Client app version: ?
* Client app installed successfully

**Bug description**

No errors
**Logs**

Browser:
```
// REPLACE WITH LOGS
```
Do not have root access, therefore cannot acquire log

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
You may have been temporarily blocked. Sadly there is not much the extension can do for you in that case, but it will likely go away in a couple of days.
