### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by MAZHAR108** [dessant/buster#216]
Try again later
Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page
![ERROR](https://user-images.githubusercontent.com/32946690/89160702-1bb35a80-d58f-11ea-834c-33e3009be04a.JPG)

**Comment by dessant** [comment]
The issue template you have deleted may help you.

**Comment by MAZHAR108** [comment]
The issue template you have deleted may help you.

CAN YOU HELP ME TO GUIDE AND REMOVE THE ISSUE RELATED TO SUCH ERRORS
