### ISSUE TITLE
Client app fails to install on Linux when the browser is installed using Snap or Flatpak

### ISSUE THREAD

**Issue by gitanopro** [dessant/buster#223]
**System**

Ubuntu
Version: 19.04
* Browser: Firefox
* Browser version: 80

**Extension**

* Extension version: 1.0.1

* Client app version: 0.3
* Client app installed successfully: no

**Bug description**
Error installing the latest version, after pressing install I get an error message that says: Something went wrong
The installation has failed. Check the browser console for more details, and open an issue on GitHub if this error persists., In app location I have this: /home/jose/.local/opt/buster and in the manifest: /home/jose/.mozilla/ native-messaging-hosts, this with previous versions did not happen to me, for Windows it is working, please help me to make this work

**Logs**

Browser:
```
[Exception... "Favicon at "http://127.0.0.1:44205/favicon.ico" failed to load."  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 215"  data: no] FaviconLoader.jsm:215:22
    onStopRequest resource:///modules/FaviconLoader.jsm:215

ExtensionError: No such native application org.buster.client ExtensionUtils.jsm:56:5
    ExtensionError resource://gre/modules/ExtensionUtils.jsm:56
    startupPromise resource://gre/modules/NativeMessaging.jsm:83


// REPLACE WITH LOGS
```

2020/08/31 02:18:49.607171 Starting setup (version: 0.3.0)
2020/08/31 02:18:49.806848 Loading setup page
2020/08/31 02:18:50.054672 Getting install location
2020/08/31 02:18:52.949326 Installing client
2020/08/31 02:18:55.620170 Installing client
2020/08/31 02:19:06.700473 Installing client
2020/08/31 02:20:01.781714 Installing client

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
> I have this: /home/jose/.local/opt/buster and in the manifest: /home/jose/.mozilla/ native-messaging-hosts

Is the space in the manifest path intentional? I have deleted your other issue, please don't open new ones when someone doesn't respond right away.

**Comment by gitanopro** [comment]
I have tried with and without space and it doesn't work

**Comment by dessant** [comment]
Is your Firefox profile at `/home/jose/.mozilla` or are you using a profile from a custom location? That space should not have been in the manifest path, try installing without modifying the default values.

**Comment by gitanopro** [comment]
I have not changed the profile path, I have tried to install with the user defaul, the one that is created with newly installed firefox and nothing

**Comment by dessant** [comment]
There should be a manifest file at `/home/jose/.mozilla/native-messaging-hosts/org.buster.client.json`. Did the installer successfully create the manifest? If yes, please share the contents of the file, and also check if there is an executable at `/home/jose/.local/opt/buster/buster-client` and make sure that the `Execute` checkbox is set for the executable in Properties > Permissions.

**Comment by gitanopro** [comment]
file content org.buster.client.json :
 {
  "name": "org.buster.client",
  "description": "Buster",
  "path": "/home/jose/.local/opt/buster/buster-client",
  "type": "stdio",
  "allowed_extensions": [
    "{e58d3966-3d76-4cd9-8552-1582fbc800c1}"
  ]
}

2.
the executable exists and has execution permissions

**Comment by dessant** [comment]
I'm not sure what went wrong, everything seems to be in place.

**Comment by dessant** [comment]
What is the path you see on the `about:support` page for `Profile Directory`?

**Comment by gitanopro** [comment]
the path shown is: /home/jose/snap/firefox/common/.mozilla/firefox/9266edcv.default

**Comment by dessant** [comment]
Ok, we've discovered the origin of the issue: Firefox is installed using a Snap package. It seems Snap and Flatpak packages break browser extensions that use Native Messaging because of file system isolation.

https://bugzilla.mozilla.org/show_bug.cgi?id=1462888
https://bugzilla.mozilla.org/show_bug.cgi?id=1621763

The easiest workaround is to install the browser from a traditional distro package, without Snap or Flatpak. If you don't want to lose your browsing data, you could either use Firefox Sync, or copy your Firefox profile folder to the default location.

**Comment by gitanopro** [comment]
I still have the same problem, but when uninstalling firefox and installing the logs they have changed

[Exception... "Favicon at "http://127.0.0.1:36239/favicon.ico" failed to load."  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 215"  data: no] FaviconLoader.jsm:215:22
    onStopRequest resource:///modules/FaviconLoader.jsm:215

2020/09/03 16:18:20.461835 Starting setup (version: 0.3.0)
2020/09/03 16:18:20.652070 Loading setup page
2020/09/03 16:18:21.036866 Getting install location
2020/09/03 16:18:28.707835 Closing setup (forced)

route profile: 

/root/.mozilla/firefox/6yiv7392.Default User

**Comment by dessant** [comment]
Now you're running the browser as root, the client app will only install if the browser and the installer are not executed with root.

**Comment by gitanopro** [comment]
can you give me instructions on how to do that? I have not understood you very well and I do not know how to do it

**Comment by dessant** [comment]
You can simply start the browser on Ubuntu from the app icon, and it will run as the current user instead of root. Same with the client app installer, just double-click on it after you've made it executable, and it should run as the current user.

I don't have enough information about your OS to understand what you're doing wrong, but this doesn't look like an extension bug at this point.

**Comment by gitanopro** [comment]
My current user is root, what you tell me is not working, I don't know what could be happening

**Comment by dessant** [comment]
Are you trying to install on a server? In any case, try asking around on an Ubuntu support forum if you have installed it on a regular PC, tell them that your current user is root and you'd like to use the default user created by Ubuntu, and they'll be able to help you.

**Comment by gitanopro** [comment]
I have installed it on a server, what should I do now?

**Comment by dessant** [comment]
The asking for help on the Ubuntu support forum.
