### ISSUE TITLE
not work while using adguard dns server

### ISSUE THREAD

**Issue by minutesinch** [dessant/buster#224]
**System**

* OS name: elementary os
* OS version:  5.1.7 Hera
* Browser name:  Firefox
* Browser version: 80

**Extension**

* Extension version: [e.g. 1.0.0]
1.0.1
* User input simulation: [e.g. yes, no]
no
* Client app version: [e.g. 1.0.0]
no i don't use user input simulation
* Client app installed successfully: [e.g. yes, no]
no i don't use user input simulation
**Bug description**

**Logs**

Browser:

14:08:33.307 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:08:33.307 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:08:33.307 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:08:33.307 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:08:33.307 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:08:33.307 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified

**Comment by dessant** [comment]
Please be more specific, what doesn't work? What are you seeing?

**Comment by minutesinch** [comment]
i cant solve captcha and buster return error and say open console also buster try work with voice

**Comment by dessant** [comment]
Test the extension again and share the entire log of the page, copy it from the current tab's console (Ctrl+Shift+K).

**Comment by minutesinch** [comment]
14:19:32.169 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:32.169 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:32.169 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:32.543 Cookie “” has been rejected as third-party. demo__ltr.css
14:19:32.836 Cookie “” has been rejected as third-party. css
14:19:32.868 Cookie “” has been rejected as third-party. recaptcha__en.js
14:19:33.013 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:33.013 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:33.013 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:33.037 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:33.037 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:33.037 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:33.037 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:33.037 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:33.037 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:33.038 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:33.038 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:33.038 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:33.743 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:33.743 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:33.744 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:33.752 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:33.752 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:33.752 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:33.755 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:33.755 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:33.755 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:33.925 Cookie “” has been rejected as third-party. recaptcha__en.js
14:19:33.931 Cookie “” has been rejected as third-party. styles__ltr.css
14:19:34.075 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:34.075 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:34.075 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:34.076 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:34.076 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:34.076 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:34.288 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:34.288 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:34.288 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:34.289 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:34.289 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:34.289 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:34.637 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:34.637 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:34.637 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:34.714 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:34.714 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:34.714 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:34.714 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:34.714 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:34.714 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:34.715 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:34.715 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:34.715 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:34.897 Cookie “” has been rejected as third-party. recaptcha__en.js
14:19:35.050 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:35.050 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:35.050 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:35.058 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:35.058 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:35.059 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:35.061 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:35.061 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:35.061 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:35.225 Cookie “” has been rejected as third-party. recaptcha__en.js
14:19:46.184 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:46.184 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:46.184 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:46.185 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
14:19:46.185 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
14:19:46.185 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
14:19:50.494 Error: NetworkError when attempting to fetch resource. 2 script.js:1:66419

**Comment by dessant** [comment]
Which IP address are you using from AdGuard? Here's a list: https://adguard.com/en/adguard-dns/overview.html#instruction

If you don't use AdGuard DNS, does the extension work?

**Comment by minutesinch** [comment]
176.103.130.130
176.103.130.131

 yes its work well without adguard dns

**Comment by dessant** [comment]
Are you able to otherwise manually solve a reCAPTCHA audio challenge by listening to the audio when AdGuard DNS is activated, or does manual solving also stop working?

**Comment by dessant** [comment]
If manual solving works, it's possible that you've discovered this issue: https://github.com/dessant/buster/issues/206

Some ad blockers are blocking https://api.wit.ai because it is a Facebook service, try contacting AdGuard to remove the host from their filter lists.

**Comment by dessant** [comment]
I've tried again with IBM Speech API too besides Wit Speech API and the AdGuard default DNS just works. I think there is some configuration option in your browser or in the extension that you have not shared.

I wanted to report the issue to AdGuard, but unfortunately I cannot reproduce it. In any case, this is not a bug in the extension.
