### ISSUE TITLE
Only solves every 3rd challenge

### ISSUE THREAD

**Issue by Ezy04** [dessant/buster#229]
Sometimes I have to click the reload button of the captcha like 10 times until the challenge finally gets solved,because clicking the buster icon simply keeps the text field empty. Also, sometimes the first time I click the buster icon the text field stays empty and then after a second click it works.

**Comment by dessant** [comment]
Also read this thread, if the error is "Something went wrong.": https://github.com/dessant/buster/issues/217

**Comment by Ezy04** [comment]
> Also read this thread, if the error is "Something went wrong.": #217

Indeed I had this 429 rate limit error, following the steps in this thread removed the error from the console but the problem stays. I also find these errors in the console:
![image](https://user-images.githubusercontent.com/71012306/92604913-5e183780-f2b1-11ea-894c-fa8ed6ef5589.png)
