### ISSUE TITLE
Error: Can't connect to Recaptcha

### ISSUE THREAD

**Issue by Joshua562** [dessant/buster#23]
Hello,

I started using the Busters extension for Firefox a while back, and it was working fine. However after a while I started getting an error now and then. Sometimes it worked, sometimes it didn't. Now I get the error all the time, the extension just doesn't work anymore. So what happens? I get on a website and they let me see the Google captcha. I click on the Buster icon and Buster fills in the words (that works). But then I get a popup notice (from the browser I think): "No contact (connection) with reCAPTCHA. Check your connection and try again." (I've translated it, since my notice is in Dutch). I've tried debugging it a bit. I've been messing with the options in Buster, I have deactivated several other extensions in Firefox to see if they broke Buster or not, I've disabled my VPN, and tried changing my browser language. However none of it seems to work.

![error-buster](https://user-images.githubusercontent.com/47474441/52519876-79990780-2c62-11e9-89be-d9726dd2cfef.png)

I hope you can fix this issue since I like using the Buster extension.

Joshua

**Comment by dessant** [comment]
The next release will have a native app that should help with this issue, subscribe to this thread for updates: https://github.com/dessant/buster/issues/2

**Comment by Joshua562** [comment]
Thank you. I'll keep an eye out for the next release.

**Comment by dessant** [comment]
The new option for user input simulation has been released, see this post for details: https://github.com/dessant/buster/issues/2#issuecomment-464597833

**Comment by Joshua562** [comment]
1. I updated to 0.4.0 but the same issue, as described in the opening topic, stil persists.

2. I'm reading something about a client: https://github.com/dessant/buster/issues/28. However, I can't find any files on my system. Do you have to install something beside the addon? If so, how?
