### ISSUE TITLE
hCaptcha image is not being solved

### ISSUE THREAD

**Issue by soysuva** [dessant/buster#232]
The extension doesn't solve hCaptcha's. I've tried it multiple times on the page that required it and it just doesn't work. All times I had to manually do it myself.

EDIT: please add hCaptcha to the extension.

**Comment by krisu5** [comment]
hCaptcha doesn't have audio challenge (yet), therefore it's impossible to implement Buster.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Issue is tracked at #319.
