### ISSUE TITLE
Something went wrong. Open the browser console for more details

### ISSUE THREAD

**Issue by ricardovix** [dessant/buster#235]
Hello Guys!

I'm a firefox user (version 81.0) and for some reason this extension is not working. 99% of the time I receive a "Something went wrong. Open the browser console for more details"

Do you know how to solve this?

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 81

* Extension version: 1.0.1

**Logs**

this.window.gBrowserInit is undefined ext-browser.js:1135
this.window.gBrowserInit is undefined ext-browser.js:1135
e is undefined h0-main.js:1
Unchecked lastError value: Error: An unexpected error occurred h0-main.js:1
    d moz-extension://32addd5f-77f5-43c4-8cd5-6714dd0092fe/h0-main.js:1
debuggee 'resource://devtools/shared/base-loader.js:289' would run builtin-modules.js:196:11
aBrowser is null PrivateBrowsingUtils.jsm:40
e is undefined h0-main.js:1
Unchecked lastError value: Error: Invalid window ID: 215 h0-main.js:1
debuggee 'resource://devtools/shared/base-loader.js:289' would run builtin-modules.js:196:11

**Comment by oturpe** [comment]
I have started to see the same, first seen on 2020-09-22 (though I do not use this extension every day or week). Error rate is much less than 99 & though, and configuration is different:

* OS name: Fedora Linux
* OS version: 32
* Browser name: Firefox
* Browser version: 80.0.1 (64-bit) (from Fedora repositories)
* Extension version: 1.0.1

I get the following log when starting Captcha Buster when it runs into error:
```
Error: API response: 429, {
  "code": "rate-limit",
  "error": "You have exceeded the limit of 60 requests per minute for your app"
} script.js:1:66419
Uncaught (in promise) Timeout
```

**Comment by dessant** [comment]
@ricardovix, the extension on the Opera add-ons site is outdated, install from the Chrome Web Store instead.

@oturpe, follow this comment to set up your own API key if the issue persists: https://github.com/dessant/buster/issues/217#issuecomment-675860000

**Comment by ricardovix** [comment]
> 
> 
> @ricardovix, the extension on the Opera add-ons site is outdated, install from the Chrome Web Store instead.
> 
> @oturpe, follow this comment to set up your own API key if the issue persists: [#217 (comment)](https://github.com/dessant/buster/issues/217#issuecomment-675860000)

Dessant, I use Firefox, so I cant install from Chrome Web Store. There isn't a way to fix the firefox extension?

**Comment by dessant** [comment]
Sorry @ricardovix, I've misread the issue. The error log you've shared appears to be for a different extension, it's possible that you'll find the real error by opening the console of the current page (Ctrl+Shift+K), though you're most likely seeing the error described in #217. The chrome and Firefox versions of the extension are both up to date.

If you end up creating your own API key, make sure to also install the client app, which will move your mouse for a better success rate.

https://github.com/dessant/buster/wiki/Inaccessible-reCAPTCHA-audio-challenge
