### ISSUE TITLE
steampowered.com not working

### ISSUE THREAD

**Issue by tw0f1sh** [dessant/buster#236]
* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 81.0

* Extension version: 1.0.1
* User input simulation: try with yes and no
* Client app version: v0.3.0
* Client app installed successfully: probably no (it dont work)

**Bug description**
I cant see the buster icon at the captcha window, on the recaptcha-demo page its working fine but not on steam.

Installed add-ons next to buster in Firefox (disabled them at testing):
- Adblock Plus
- Greasemonkey
- Noscript (everything allowed on steam page)

Steps to reproduce:
1. go to https://store.steampowered.com/join/
2. Click on the reCaptcha check box
3. there is no buster button at the bottom

Screenshot: https://www.xup.in/dl,38055909/Unbenannt.JPG/

reCaptcha on page info:
Steam using recaptcha enterprise idk maybe this is not supported by Buster?

**Logs**
No error in console

Client app:
nope

**Comment by dessant** [comment]
@tw0f1sh, thanks for the bug report! Indeed the extension did not support reCAPTCHA Enterprise, I'll release an update in the next few days.

**Comment by Horns666** [comment]
You still haven't released an update for reCAPTCHA Enterprise?


> @tw0f1sh, thanks for the bug report! Indeed the extension did not support reCAPTCHA Enterprise, I'll release an update in the next few days.

You still haven't released an update for reCAPTCHA Enterprise?
