### ISSUE TITLE
Solving Fails when captcha in popup

### ISSUE THREAD

**Issue by UltraBlackLinux** [dessant/buster#237]
**System**

* OS name: Manjaro
* OS version: 5.8.6-1
* Browser name: Firefox Nightly
* Browser version: 83.0a1

**Extension**

* Extension version: 1.0.1

* User input simulation: yes

* Client app version: I dont know lol. The date is 26.9.2020, auto update
* Client app installed successfully: yes

**Bug description**
Buster Fails to solve the Recaptcha, whenever that is located in a popup. An example is the popup in gitlab when editing an issue too frequently

**Logs**

Browser:
```
https://gist.github.com/UltraBlackLinux/73d77278c65f0a93fcdd382674de4d35
```

Client app:
```
https://gist.github.com/UltraBlackLinux/0daf82dcf8d2591f4a0ab1fd4f9ff87d
```

**Comment by dessant** [comment]
How does it fail exactly? What are you seeing?

**Comment by UltraBlackLinux** [comment]
I dont see anything, just the desktop notification that it failed. It doesnt even attempt to solve it.

**Comment by dessant** [comment]
Describe the steps you take and the exact error message you get.

**Comment by UltraBlackLinux** [comment]
1. Click on the captcha
2. Get the notif that sth went wrong
3. The logs dont say anything useful

**Comment by dessant** [comment]
I guess you mean you clicked on the captcha solver button. Does the mouse move in any direction before the error is shown, and does the error appear instantly after the click, or only after about 10 seconds?

When you open the extension's option page, is user input simulation turned on? Is the client app installation button still present on that page?

I'd like to try to reproduce the issue myself, but the reCAPTCHA on the GitLab signup page works, and I can't trigger any captcha while repeatedly editing an issue.

You could also check the console of the current tab (Ctrl+Shift+K) for an error message, there must be one somewhere if you get a notification.

**Comment by UltraBlackLinux** [comment]
If I rememer correctly, If I click on the solve button, it switches to audio, listens, then throws an error. As the log from above sais, there is litterally no error message at all. And yes, the script is still installed.

**Comment by dessant** [comment]
You see, that's a very different situation from the one you initially described, and it has nothing to do with the reCAPTCHA being in a popup, if the extension is able to navigate around in the challenge widget. Please be more specific next time you open a bug report, to avoid wasting everyone's time.

Again, the error is likely visible in the console of the current tab (Ctrl+Shift+K), and it's possible that you're seeing this issue: https://github.com/dessant/buster/issues/217

**Comment by UltraBlackLinux** [comment]
Bruh I looked at it again, and I remembered wrong: It just fails to find the recaptcha buttons it seems like. @dessant
