### ISSUE TITLE
Hcaptch Support

### ISSUE THREAD

**Issue by LukewarmCat** [dessant/buster#239]
**Is your feature request related to a problem? Please describe.**
I just have tons of hCaptcha captchas and I wanna solve them too.

**Describe the solution you'd like**
hCaptcha support

**Describe alternatives you've considered**
nothing

**Additional context**
hCaptcha is pretty much recaptcha reskinned afaik

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Issue is tracked at #319.
