### ISSUE TITLE
Cannot play in Firefox 

### ISSUE THREAD

**Issue by kazik56** [dessant/buster#24]
Clicking play doesn't play any audio. It sais that I should open console for more info. Here what is the console output after clicking "Play" button.
```
HTTP "Content-Type" of "audio/mpeg" is not supported. Load of media resource https://www.google.com/recaptcha/api2/payload?p=06AF6jDqW97TowmTiukDT5kv2zzztr87_G4_hT5qdS9e22mniMpALf39PRXOPg4oplJQJ5lozXhslvlDIRuMdbfXjwhlziPtw2InWb2X9GVryWqUZDaerZas2HyJVZUJ-nixvD9AxiTbogH2k6qEWO9Y1UDJfD51XqhaEyw7ZymQ7P65UDP6UFBao&k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0 failed. bframe
NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.
Cannot play media. No decoders for requested formats: audio/mpeg
```

**Comment by dessant** [comment]
This is not related to the extension, disable it and you should see the same error. You're probably missing a codec.

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility

> To avoid patent issues, support for MP3 is not built directly into Firefox. Instead it relies on support from the OS. Firefox supports this format on the following platforms: Windows Vista+ since Firefox 22.0, Android since Firefox 20.0, Firefox OS since Firefox 15.0, Linux since Firefox 26.0 (relies on GStreamer codecs) and OS X 10.7 since Firefox 35.0.

**Comment by kazik56** [comment]
Which format do I have to install?

**Comment by dessant** [comment]
A codec for MP3 support. Most operating systems come with the required codecs, but in some cases you may need to install a codec pack.
