### ISSUE TITLE
Why the extension isn't getting any updates on the chrome and edge webstore? it still says 1.0.1?

### ISSUE THREAD

**Issue by Droyk** [dessant/buster#243]
![image](https://user-images.githubusercontent.com/15848350/95785299-21e25780-0cf3-11eb-95e7-1d999d92b2fa.png)
![image](https://user-images.githubusercontent.com/15848350/95785387-4a6a5180-0cf3-11eb-8659-811f2831edf0.png)

**Comment by dessant** [comment]
It takes a couple of days for the extension to get reviewed, the latest version is already live for Firefox and Opera.

**Comment by Droyk** [comment]
fast reply! thankyou!
