### ISSUE TITLE
Client app with "Navigate with keyboard" disabled does not work in Firefox Fission windows

### ISSUE THREAD

**Issue by CrendKing** [dessant/buster#245]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 83.0a1 nightly

**Extension**

* Extension version: 1.1.0

* User input simulation: Yes

* Client app version: Latest
* Client app installed successfully: Yes

**Bug description**

Firefox nightly allows user to enable Fission, which is equivalent to Chrome's site isolation. With Fission enabled, web pages and addons are in different processes. Now with the client app and navigate with mouse (the default option), every time I click the buster icon in recaptcha, I get the error message in console:
```
Error: No frame found with frameId: <integer>
```
Workarounds are either

1. Navigate with keyboard
2. Only use Buster in Non-Fission windows

Both solution have drawbacks. Current default keyboard press delay (300ms) is slow (strongly suggest to decrease to something like 50 - 100ms), so 1 is relatively inefficient. 2 sacrifices security just for one addon. And you have to anticipate captcha ahead of time.

Any chance to make Buster compatible with Fission?

**Comment by dessant** [comment]
Thanks for the detailed bug report! There may be a chance... :yum:

**Comment by CrendKing** [comment]
Hi. Any update on this issue? Now Fission can be enabled even in Firefox 87 Beta, it would be so nice if we could enjoy the convenience from Buster and privacy from Fission.
