### ISSUE TITLE
App not working in Ubuntu

### ISSUE THREAD

**Issue by taunnt** [dessant/buster#246]
For the life of me can't get the app to work. I install it will load after a while it always says failed. Can you make it where you can just put in where the app is located and it will do the rest? It's failed in Firefox and in Chrome. Is there a magical trick I'm missing or is it the app?

**Comment by dessant** [comment]
I'm guessing the browsers were installed using snap packages, right?

**Comment by dessant** [comment]
Or maybe you use Wayland? It's hard to tell because you have not described the exact steps you take and how the extension reacts to them.

The istallation guide mentions some of the limitations of the client app on Linux: https://github.com/dessant/buster/wiki/Installing-the-client-app
