### ISSUE TITLE
api for bister

### ISSUE THREAD

**Issue by erxxsu** [dessant/buster#248]
hi i have google cloud platform with 300 usd 
but i dont know how can i make an api for buster plz help or teach that in youtube

**Comment by dessant** [comment]
You can add the API key from the extension's options, by selecting `Google Cloud Speech API` under `Speech service`. You don't need a Google Cloud account with funds, the free tier of the API is enough for solving challenges as you browse the web.

**Comment by dessant** [comment]
We don't have a guide on how to get the API key from Google Cloud, but you could follow the guide below to get an API key from Wit.ai instead.

https://github.com/dessant/buster/wiki/Configuring-Wit.ai
