### ISSUE TITLE
Notification when audio can not be obtained from reCAPTCHA

### ISSUE THREAD

**Issue by Klapkaak078** [dessant/buster#249]
**Is your feature request related to a problem? Please describe.**
Sometimes the extension does not get the audio file, probably the google server does not respond to the request, so you have to reload the captcha to obtain the audio file to the extension.

**Describe the solution you'd like**
Give a notification, so that we as the end user know what is going on.

**Describe alternatives you've considered**

**Additional context**

**Comment by dessant** [comment]
What is the error you currently see in the UI and the browser console when the audio cannot be obtained?
