### ISSUE TITLE
Error: doesn't work in Firefox 66.0b7

### ISSUE THREAD

**Issue by RigoSex** [dessant/buster#25]
Message window pop out: 

> No Internet connection. Check your connection and try again.

But i can see that captcha solve is working:
![default](https://user-images.githubusercontent.com/19224346/52873597-73be8d00-3160-11e9-9ec6-947643ecf474.png)
Dev-Guy, help us all...

**Comment by dessant** [comment]
This will be fixed in the next release, follow this thread for updates: https://github.com/dessant/buster/issues/2
