### ISSUE TITLE
Buster not worrking

### ISSUE THREAD

**Issue by Hirrochi** [dessant/buster#250]
He Fill out the template below with the requested information. -->

* OS name:  Windows
* OS version: 10
* Browser name: Both, mainly Fiirefox
* Browser version: 82.0 64bit

**Extension**
Buster: Captcha Solver for Humans

* Extension version: [e.g. 1.1.0]
* User input simulation:no
* Client app installed successfully: yes

**Bug description**
Ii go to try it in https://www.google.com/recaptcha/api2/demo or otherr websites but nothiing ever happens.
No interactiion, no call to API, nothing.

I am usiing IBM Working APII. client app I try to install but also with that nothing happens.

**Comment by dessant** [comment]
Do you manually click on the extension button or using a script?

**Comment by Hirrochi** [comment]
I dont have any extension button on firefox, on chrome if I click the menu with options appeparrs.

Thank youu for your help.

**Comment by dessant** [comment]
I'm not sure what's the issue on your end, but at least the yellow extension button should appear on Firefox in the reCAPTCHA challenge widget, like in [this](https://camo.githubusercontent.com/91158c1be4bfc236972e157d167e1d080befd551/68747470733a2f2f692e696d6775722e636f6d2f685471654e347a2e706e67) image.

It's possible that you have changed some options in about:config that broke the extension, try installing it in a fresh Firefox profile.

Once you make the extension button appear in the challenge widget, let me know if there's any other issue with the extension.
