### ISSUE TITLE
Button disappeared

### ISSUE THREAD

**Issue by Hirrochi** [dessant/buster#251]
OS name: Windows
    OS version: 10
    Browser name: Both, mainly Fiirefox
    Browser version: 82.0 64bit

Extension
Buster: Captcha Solver for Humans
    Extension version: [e.g. 1.1.0]
    User input simulation:no
    Client app installed successfully: yes

Button was there for llong time and suddenly has disappeared. 
I have reboot and all kind of try but is no longer there in the captcha.

**Comment by dessant** [comment]
See my answer on your previous issue here: https://github.com/dessant/buster/issues/250#issuecomment-721067673
