### ISSUE TITLE
[Request] Option to deactivate Windows-Notification on error

### ISSUE THREAD

**Issue by Aequita** [dessant/buster#253]
**Is your feature request related to a problem? Please describe.**
Not a real "problem", but if one tries to keep the notification and (1)s in ones digital life sorted - the constant notifications when the challenge could not be solved are tiresome.

**Describe the solution you'd like**
A "Disable notifications"-Option

**Comment by dessant** [comment]
There are different error notifications in the extension that let you know about issues and the actions you can take, and disabling them would lead to confusion and the extension could appear to do nothing and be broken.

Isn't the main issue that you have to manually clear the notification? We could clear the notification automatically after a couple of seconds.

**Comment by Aequita** [comment]
> Isn't the main issue that you have to manually clear the notification?
Yes, yes it is :)

Maybe my request was written badly, as I didn't intend to request a "Disable all error notifications"- but rather a "Disable 'Captcha could not be recognized' notifications"-option.
If this type notification can be made temporary - that would be great too!
