### ISSUE TITLE
Building extension in mac

### ISSUE THREAD

**Issue by kmtun** [dessant/buster#259]
Hello,

How can I build this extension in mac?

I see there is wiki for https://github.com/dessant/buster/wiki/Building-the-extension-on-Ubuntu and window only

I installed node version 12.18.4 and ran npm i but ran into problem

npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated js-select@0.6.0: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated jetpack-id@1.0.0: Jetpack extensions are no longer supported by Firefox. Use web-ext instead to build a WebExtension.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code 1
npm ERR! Command failed: git checkout ^0.2.6
npm ERR! error: pathspec '^0.2.6' did not match any file(s) known to git
npm ERR! 

npm ERR! A complete log of this run can be found in:

**Comment by dessant** [comment]
You could adapt the Ubuntu guide to build on macOS.
