### ISSUE TITLE
How to Remove Buster Client from Linux

### ISSUE THREAD

**Issue by spectrumgamer75** [dessant/buster#260]
Hello,
I wanted to uninstall the buster client for linux from my system. 
Running Zorin OS 15.3, based on Ubuntu.

Thanks.

**Comment by dessant** [comment]
The executable is placed in the `~/.local/opt/buster` folder by default, and the manifest file is in your browser config folder, these are the default paths:

https://github.com/dessant/buster-client/blob/d9f73868464a0208ecd61f06600592f343730105/cmd/setup/main.go#L109-L118

Removing these files undoes the changes the installer has made.

**Comment by spectrumgamer75** [comment]
Thanks, it worked :+1:
