### ISSUE TITLE
Client app does not support Apple M1 chip on macOS

### ISSUE THREAD

**Issue by unbeatable-101** [dessant/buster#261]
**System**

* OS name: macOS
* OS version: 11.1
* Browser name: Firefox
* Browser version: 85.0b4

**Extension**

* Extension version: 1.1.0

* User input simulation: yes

**Bug description**

In the wiki there are instructions for installing on macOS, but the extension page moz-extension://ccf46b12-7cce-4d65-be2b-e2c7e48c44ac/src/options/index.html says otherwise.

**Comment by dessant** [comment]
Are you using a device with the M1 CPU?

**Comment by unbeatable-101** [comment]
Yes

**Comment by dessant** [comment]
The M1 chip is not yet supported by the client app, you could try running the amd64 installer using Rosetta 2, and see if the installation succeeds.

https://github.com/dessant/buster-client/releases/download/v0.3.0/buster-client-setup-v0.3.0-macos-amd64

**Comment by unbeatable-101** [comment]
The client installs and works.

**Comment by dessant** [comment]
Sounds great! Did you have to do anything that is not documented in the wiki to make it work, besides downloading directly rather than going to the extension's options?

**Comment by unbeatable-101** [comment]
Nope, followed the wiki just fine.

**Comment by dessant** [comment]
Ok, so it should be enough to serve the amd64 binary for arm64 users, until things are set up to distribute native arm64 installers. I'll update the extension's options to show M1 devices as compatible.
