### ISSUE TITLE
Buster Can't solve captchas

### ISSUE THREAD

**Issue by unbeatable-101** [dessant/buster#262]
**System**

* OS name: macOS
* OS version: 11.1
* Browser name: Firefox
* Browser version: 85.0b4

**Extension**

* Extension version: 1.1.0

* User input simulation: yes

* Client app version: How do I check?
* Client app installed successfully: yes

**Bug description**

Buster won't solve the captcha.

This is probably an about:config tweak I have, I'll check later but do you know of any that would cause this?

**Logs**

Browser:
```
01:36:58.279 Error: AudioContext is not defined script.js:1:22667
01:36:58.282 Error: AudioContext is not defined undefined
01:36:59.000 Cannot play media. No decoders for requested formats: audio/mpeg bframe
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
Maybe you've disabled the Web Audio API (dom.webaudio.enabled preference in about:config) or some other anti-fingerprinting option interferes.

See this comment and thread if you've hardened the browser using about:config: https://github.com/dessant/buster/issues/230#issuecomment-690268154
