### ISSUE TITLE
Support hCaptcha

### ISSUE THREAD

**Issue by leodoi3** [dessant/buster#265]
Is it possible to support these kinds of captchas? 

![image](https://user-images.githubusercontent.com/46114199/103838062-542cf800-5049-11eb-8d15-661a073c0438.png)
![image](https://user-images.githubusercontent.com/46114199/103838075-5c853300-5049-11eb-9223-4335b0c09e60.png)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Issue is tracked at #319.
