### ISSUE TITLE
VirusTotal: 3 detections for Trojan/Malware/Worm on Client App for Windows executable

### ISSUE THREAD

**Issue by tmattel** [dessant/buster#269]
See VirusTotal URL.. Please advise!

https://www.virustotal.com/gui/file/d841c7507d6b8459c86f58bafe02b68bedb19ac4e64d7391ed1352dc2909c2af/detection

**Comment by dessant** [comment]
It's probably a false positive, the binary is built by GitHub, and the source code is open source, so you should be able to recreate the installer if you have any concerns regarding the published one.

https://github.com/dessant/buster-client/
https://github.com/dessant/buster-client/blob/master/.github/workflows/ci.yml

**Comment by tmattel** [comment]
Thank you!
