### ISSUE TITLE
Simulated user input moves the mouse incorrectly

### ISSUE THREAD

**Issue by jkcclemens** [dessant/buster#27]
Whenever I click on the button that Buster adds when simulated user input is enabled, the mouse moves to one edge of the screen instead of wherever it's supposed to go.

If it's important, I had to build the client binary and installer myself, since the distributed version uses a very old version of libpng that I couldn't install on my system (libpng12 vs libpng16).

**Comment by dessant** [comment]
Are you on X11 or Wayland?

**Comment by jkcclemens** [comment]
X11

**Comment by dessant** [comment]
I'm not sure what causes the sideways movement, please run this in your browser console: `window.devicePixelRatio`. Which distro and version are you using? Is your desktop environment scaled up or is your monitor HDPI? I could try recreating your env in a VM to reproduce the bug.

I'll drop the robotgo dependency entirely at some point (which requires libpng) and call system APIs directly.

**Comment by jkcclemens** [comment]
I figured it had to do with scaling. Yes, monitor is HiDPI. `window.devicePixelRatio` is 1, but GNOME is scaled to 200%. I'm using Ubuntu 18.10 (cosmic) and Firefox 67.0a1 (2019-02-11).

**Comment by dessant** [comment]
Btw, until the mouse issue is solved, you could navigate with Shift+Tab to the extension button and press Enter. It opts for keyboard navigation if the user initiates the solving with a keyboard.

**Comment by dessant** [comment]
Ugh, so it looks like Firefox does not report OS scaling properly. I have only accounted for window.devicePixelRatio to handle scaling.

**Comment by jkcclemens** [comment]
For what it's worth, Firefox *does* report pixel ratio properly, but I have the `privacy.resistFingerprinting` option enabled, which makes it report 1.

**Comment by dessant** [comment]
Oo of :joy_cat:

**Comment by dessant** [comment]
Thanks for testing! I did not know `resistFingerprinting` can also spoof `devicePixelRatio`.

**Comment by jkcclemens** [comment]
No problem. Although, when I turned off `resistFingerprinting`, the mouse still didn't end up in the right spot (it went in the inverse direction, I think), and I'm a little boggled at that.

**Comment by dessant** [comment]
Please do a test with OS scaling set to 1, let's see if the last issue is entirely because of scaling.

**Comment by jkcclemens** [comment]
Works as intended with the OS scaling set to 1.

**Comment by dessant** [comment]
Thanks a bunch for your time, I'll try to reproduce and fix the bug.

**Comment by dessant** [comment]
The fix was published on AMO, please let me know if there are other issues related to scaling.

**Comment by Bluscream** [comment]
I have the same problem, my curser just moves down indefinitly until it reaches the bottom of the screen

**Comment by dessant** [comment]
@Bluscream, which version of the extension are you using? Please share more details about your environment.

**Comment by Bluscream** [comment]
I am using the version from the mozilla store in firefox quantum, what else do you need? I can give it here once im back on my pc

**Comment by dessant** [comment]
@Bluscream, please open a new issue, the bug report template will list all the needed information, also include your display type, and whether you are using display scaling, or if you are zooming the web page.

**Comment by Bluscream** [comment]
Okay thanks

**Comment by dessant** [comment]
@Bluscream, it's also possible that the browser does not report the correct scale, it may happen if you have enabled privacy.resistFingerprinting, or a privacy extension.

**Comment by Bluscream** [comment]
I use a lot of privacy settings/addons. So people using that cant use the client?

**Comment by dessant** [comment]
It really depends on the extensions and specific settings you use, and also your os scaling and page zooming. Let me know if you figure out which extension and setting is interfering with Buster.

**Comment by Bluscream** [comment]
The problen with that is that i have no idea. I use them to not have to think about that Kinda stuff. I could dump everything out for you.

**Comment by Bluscream** [comment]
# Extensions
<table>
        <thead>
          <tr>
            <th data-l10n-id="extensions-name">Name</th>
            <th data-l10n-id="extensions-version">Version</th>
            <th data-l10n-id="extensions-enabled">Enabled</th>
            <th data-l10n-id="extensions-id">ID</th>
          </tr>
        </thead>
        <tbody id="extensions-tbody">
        <tr><td>Absolute Enable Right Click &amp; Copy</td><td>1.3.8</td><td>true</td><td>{9350bc42-47fb-4598-ae0f-825e3dd9ceba}</td></tr><tr><td>AdGuard AdBlocker</td><td>2.10.17</td><td>true</td><td>adguardadblocker@adguard.com</td></tr><tr><td>Auto Reload Tab</td><td>0.5</td><td>true</td><td>{0ed335eb-9779-4d7f-b9d8-7ec2e96a1f43}</td></tr><tr><td>Buster: Captcha Solver for Humans</td><td>0.4.1</td><td>true</td><td>{e58d3966-3d76-4cd9-8552-1582fbc800c1}</td></tr><tr><td>CanvasBlocker</td><td>0.5.8</td><td>true</td><td>CanvasBlocker@kkapsner.de</td></tr><tr><td>Chrome Store Foxified</td><td>3.4</td><td>true</td><td>Chrome-Store-Foxified@jetpack</td></tr><tr><td>CoderStats link for Github Coders</td><td>2.0.0</td><td>true</td><td>jid1-HAA0sgdoxNv9aA@jetpack</td></tr><tr><td>Dark Reader</td><td>4.7.6</td><td>true</td><td>addon@darkreader.org</td></tr><tr><td>Feedbro</td><td>3.39.0</td><td>true</td><td>{a9c2ad37-e940-4892-8dce-cd73c6cbbc0c}</td></tr><tr><td>File Icon for GitHub, GitLab and Bitbucket</td><td>0.8.1</td><td>true</td><td>{85860b32-02a8-431a-b2b1-40fbd64c9c69}</td></tr><tr><td>Friendly GitHub</td><td>18.9.13.2209</td><td>true</td><td>{073711a2-ea6d-49f2-98b6-0d7ea340c06f}</td></tr><tr><td>GitHub Issue Hoister</td><td>0.1.0</td><td>true</td><td>{f72823f3-f1b7-4c5f-b708-a1a8a24700f6}</td></tr><tr><td>Github Repo Size</td><td>1.3.0</td><td>true</td><td>github-repo-size@mattelrah.com</td></tr><tr><td>Google images view image button</td><td>1.3</td><td>true</td><td>google_images_view_image_button@mail.com</td></tr><tr><td>Google Translator for Firefox</td><td>3.0.3.3</td><td>true</td><td>translator@zoli.bod</td></tr><tr><td>HTTPS Everywhere</td><td>2019.1.31</td><td>true</td><td>https-everywhere@eff.org</td></tr><tr><td>Open in Browser</td><td>2.8</td><td>true</td><td>openinbrowser@www.spasche.net</td></tr><tr><td>QR Code Generator</td><td>3.0.0</td><td>true</td><td>jid0-RwTySlpoKU14fw7yw2AflOAihhA@jetpack</td></tr><tr><td>Remove Cookie for Google Account Chooser</td><td>2.0</td><td>true</td><td>jid1-Rm4h1P3jB1IL4w@jetpack</td></tr><tr><td>Shodan</td><td>0.3.2</td><td>true</td><td>jid1-AWt6ex5aPvWtTg@jetpack</td></tr><tr><td>Snap Links</td><td>3.1.5</td><td>true</td><td>snaplinks@snaplinks.mozdev.org</td></tr><tr><td>Stylus</td><td>1.5.2</td><td>true</td><td>{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}</td></tr><tr><td>uMatrix</td><td>1.3.16</td><td>true</td><td>uMatrix@raymondhill.net</td></tr><tr><td>View Page Archive &amp; Cache</td><td>1.5.3</td><td>true</td><td>{d07ccf11-c0cd-4938-a265-2a4d6ad01189}</td></tr><tr><td>Violentmonkey</td><td>2.10.1</td><td>true</td><td>{aecec67f-0d10-4fa7-b7c7-609a2db280cf}</td></tr><tr><td>Wappalyzer</td><td>5.7.3</td><td>true</td><td>wappalyzer@crunchlabz.com</td></tr><tr><td>Wayback Machine</td><td>1.8.6</td><td>true</td><td>wayback_machine@mozilla.org</td></tr><tr><td>Web Developer</td><td>2.0.1</td><td>true</td><td>{c45c406e-ab73-11d8-be73-000a95be3b12}</td></tr><tr><td>Wide GitHub</td><td>1.0.1</td><td>true</td><td>{72742915-c83b-4485-9023-b55dc5a1e730}</td></tr><tr><td>Advanced GitHub Notifier</td><td>1.4.6</td><td>false</td><td>{8d4b86c5-64bf-4780-b029-0112386735ab}</td></tr><tr><td>GitHub Canned Responses</td><td>1.0.8</td><td>false</td><td>github-canned-responses@example</td></tr><tr><td>GitHub Notifier</td><td>1.3.2</td><td>false</td><td>{0906178a-2043-4d0c-a099-bd6a4d00945e}</td></tr><tr><td>GitHub with a cape</td><td>1.4.5</td><td>false</td><td>{38834a56-84c1-4489-8160-97192066217d}</td></tr><tr><td>New Tab Override</td><td>14.2.0</td><td>false</td><td>newtaboverride@agenedia.com</td></tr><tr><td>OkayFreedom</td><td>1.6.2</td><td>false</td><td>{DB981CCA-088E-4731-A4A2-2FE218703C0E}</td></tr><tr><td>Refined GitHub</td><td>19.2.27.1835</td><td>false</td><td>{a4c4eda4-fb84-4a84-b4a1-f7c1cbf2a1ad}</td></tr></tbody>
      </table>

# Settings

<table class="prefs-table">
     <thead class="no-copy">
   <th class="name" data-l10n-id="modified-prefs-name">Name</th>

    <th class="value" data-l10n-id="modified-prefs-value">Value</th>
  </thead>

 <tbody id="prefs-tbody">
 <tr><td class="pref-name">accessibility.force_disabled</td><td class="pref-value">1</td></tr><tr><td class="pref-name">accessibility.typeaheadfind.flashBar</td><td class="pref-value">0</td></tr><tr><td class="pref-name">browser.cache.disk.capacity</td><td class="pref-value">1048576</td></tr><tr><td class="pref-name">browser.cache.disk.filesystem_reported</td><td class="pref-value">1</td></tr><tr><td class="pref-name">browser.cache.disk.smart_size.first_run</td><td class="pref-value">false</td></tr><tr><td class="pref-name">browser.display.document_color_use</td><td class="pref-value">1</td></tr><tr><td class="pref-name">browser.download.useDownloadDir</td><td class="pref-value">false</td></tr><tr><td class="pref-name">browser.sessionstore.upgradeBackup.latestBuildID</td><td class="pref-value">20190228180200</td></tr><tr><td class="pref-name">browser.startup.homepage_override.buildID</td><td class="pref-value">20190228180200</td></tr><tr><td class="pref-name">browser.startup.homepage_override.mstone</td><td class="pref-value">66.0</td></tr><tr><td class="pref-name">browser.urlbar.placeholderName</td><td class="pref-value">Google</td></tr><tr><td class="pref-name">browser.urlbar.timesBeforeHidingSuggestionsHint</td><td class="pref-value">0</td></tr><tr><td class="pref-name">dom.push.userAgentID</td><td class="pref-value">03f6a33f95154a6b89edd8d42487c99a</td></tr><tr><td class="pref-name">extensions.lastAppVersion</td><td class="pref-value">66.0</td></tr><tr><td class="pref-name">font.internaluseonly.changed</td><td class="pref-value">false</td></tr><tr><td class="pref-name">gfx.canvas.skiagl.dynamic-cache</td><td class="pref-value">false</td></tr><tr><td class="pref-name">layers.mlgpu.sanity-test-failed</td><td class="pref-value">false</td></tr><tr><td class="pref-name">media.gmp-gmpopenh264.abi</td><td class="pref-value">x86_64-msvc-x64</td></tr><tr><td class="pref-name">media.gmp-gmpopenh264.lastUpdate</td><td class="pref-value">1549966397</td></tr><tr><td class="pref-name">media.gmp-gmpopenh264.version</td><td class="pref-value">1.7.1</td></tr><tr><td class="pref-name">media.gmp-manager.buildID</td><td class="pref-value">20190228180200</td></tr><tr><td class="pref-name">media.gmp-manager.lastCheck</td><td class="pref-value">1551528011</td></tr><tr><td class="pref-name">media.gmp-widevinecdm.abi</td><td class="pref-value">x86_64-msvc-x64</td></tr><tr><td class="pref-name">media.gmp-widevinecdm.lastUpdate</td><td class="pref-value">1549966399</td></tr><tr><td class="pref-name">media.gmp-widevinecdm.version</td><td class="pref-value">4.10.1146.0</td></tr><tr><td class="pref-name">media.gmp.storage.version.observed</td><td class="pref-value">1</td></tr><tr><td class="pref-name">media.hardware-video-decoding.failed</td><td class="pref-value">false</td></tr><tr><td class="pref-name">network.cookie.cookieBehavior</td><td class="pref-value">3</td></tr><tr><td class="pref-name">network.dns.disablePrefetch</td><td class="pref-value">true</td></tr><tr><td class="pref-name">network.http.speculative-parallel-limit</td><td class="pref-value">0</td></tr><tr><td class="pref-name">network.predictor.cleaned-up</td><td class="pref-value">true</td></tr><tr><td class="pref-name">network.predictor.enabled</td><td class="pref-value">false</td></tr><tr><td class="pref-name">network.prefetch-next</td><td class="pref-value">false</td></tr><tr><td class="pref-name">places.database.lastMaintenance</td><td class="pref-value">1551328301</td></tr><tr><td class="pref-name">places.history.expiration.transient_current_max_pages</td><td class="pref-value">129775</td></tr><tr><td class="pref-name">plugin.disable_full_page_plugin_for_types</td><td class="pref-value">application/pdf</td></tr><tr><td class="pref-name">privacy.cpd.cache</td><td class="pref-value">false</td></tr><tr><td class="pref-name">privacy.cpd.cookies</td><td class="pref-value">false</td></tr><tr><td class="pref-name">privacy.cpd.downloads</td><td class="pref-value">false</td></tr><tr><td class="pref-name">privacy.cpd.formdata</td><td class="pref-value">false</td></tr><tr><td class="pref-name">privacy.cpd.history</td><td class="pref-value">false</td></tr><tr><td class="pref-name">privacy.donottrackheader.enabled</td><td class="pref-value">true</td></tr><tr><td class="pref-name">privacy.resistFingerprinting</td><td class="pref-value">true</td></tr><tr><td class="pref-name">privacy.sanitize.pending</td><td class="pref-value">[{"id":"newtab-container","itemsToClear":[],"options":{}}]</td></tr><tr><td class="pref-name">security.enterprise_roots.enabled</td><td class="pref-value">true</td></tr><tr><td class="pref-name">security.mixed_content.block_active_content</td><td class="pref-value">false</td></tr><tr><td class="pref-name">security.mixed_content.upgrade_display_content</td><td class="pref-value">true</td></tr><tr><td class="pref-name">security.sandbox.content.tempDirSuffix</td><td class="pref-value">{e705a2a7-1cd7-4e31-8b56-0d147135c68c}</td></tr><tr><td class="pref-name">security.sandbox.plugin.tempDirSuffix</td><td class="pref-value">{f9794e45-32a8-44af-98e9-82f081c0cde1}</td></tr><tr><td class="pref-name">services.sync.declinedEngines</td><td class="pref-value"></td></tr><tr><td class="pref-name">services.sync.engine.bookmarks.validation.lastTime</td><td class="pref-value">1549978761</td></tr><tr><td class="pref-name">services.sync.engine.passwords.validation.lastTime</td><td class="pref-value">1549978761</td></tr><tr><td class="pref-name">services.sync.engine.prefs.modified</td><td class="pref-value">false</td></tr><tr><td class="pref-name">services.sync.lastPing</td><td class="pref-value">1551587310</td></tr><tr><td class="pref-name">services.sync.lastSync</td><td class="pref-value">Sun Mar 03 2019 07:14:45 GMT+0000 (Coordinated Universal Time)</td></tr><tr><td class="pref-name">signon.importedFromSqlite</td><td class="pref-value">true</td></tr><tr><td class="pref-name">storage.vacuum.last.index</td><td class="pref-value">1</td></tr><tr><td class="pref-name">storage.vacuum.last.places.sqlite</td><td class="pref-value">1549966565</td></tr><tr><td class="pref-name">ui.osk.debug.keyboardDisplayReason</td><td class="pref-value">IKPOS: Touch screen not found.</td></tr></tbody>
      </table>

**Comment by s73b4n** [comment]
Hello dessant, just to inform that today I try the new user input simulation feature but is not working properly for me. I figured out the reason is because I have my desktop scaled to 125%. I tried in the console with window.devicePixelRatio and is showing 1.25, hope it helps.
I would thank you a lot if you could fix this, you have done an amazing work. btw im using chrome on w10.

**Comment by dessant** [comment]
@s73b4n, are you using Firefox with privacy.resistFingerprinting set to true?

**Comment by dessant** [comment]
@s73b4n, please open a new issue and fill out the issue template with all the requested details, that should help with reproducing the bug.

**Comment by s73b4n** [comment]
ok, will do it so, thanks for the fast reply.
