### ISSUE TITLE
Cant install on brave, ubuntu 20.10 

### ISSUE THREAD

**Issue by diogo098** [dessant/buster#276]
**System**

* OS name: [ Ubuntu]
* OS version: [20.10]
* Browser name: [Brave]
* Browser version: [Versão 1.22.70 Chromium: 89.0.4389.105 (Versão oficial) 64 bits]

**Bug description**

I wanted to install the client but there is only a message saying something went wrong.
I do believe is something about the container part of ubuntu apps or something im still knew to this, anyways i will just keep this here maybe is something else.
Thank you so much for your work!

**Logs**  From browser console
:33267/favicon.ico:1 Failed to load resource: net::ERR_EMPTY_RESPONSE
script.js:1 Error: Attempting to use a disconnected port object
DevTools failed to load SourceMap: Could not load content for chrome-extension://ghlpgemofagjcipoafdennlineckfjan/src/manifest.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://ghlpgemofagjcipoafdennlineckfjan/src/commons-ui/script.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://ghlpgemofagjcipoafdennlineckfjan/src/setup/script.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://ghlpgemofagjcipoafdennlineckfjan/src/setup/style.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://ghlpgemofagjcipoafdennlineckfjan/src/commons-ui/style.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by diogo098** [comment]
I wanted to install the client but the only message is something went wrong.
Maybe is something about the container apps on ubuntu, idk im still knew to this, anyway thank you so much for your work :)
You are awesome!

**Comment by dessant** [comment]
Was Brave installed from a snap package? Browsers installed from snap and flatpak packages don't support native messaging, so the client app installation will fail.

**Comment by diogo098** [comment]
i installed from the brave repo, but how can i be sure if i dont have a snap /flat package installed ?

**Comment by diogo098** [comment]
All right now i inderstand sorry for the noob question turns out ubuntu install the package as a snap, in a sandbox
https://i.imgur.com/Ve4LM7T.png
