### ISSUE TITLE
Removal Instructions for Buster Client

### ISSUE THREAD

**Issue by OJE9** [dessant/buster#28]
I would feel a bit better knowing where the installer put the files on my system. 
From what I can see its the NativeMessaging key in the Registry and some files in AppData\Local?
Could you maybe add some removal instructions to the Buster Client page?

_P.S I love 0.4.0. Single letter solution typing and mouse click automation was the exact features I was waiting for._

**Comment by dessant** [comment]
Yes, on Windows both the binary and the manifest are saved to `AppData\Local\buster` or a different location you have set during installation. Deleting that folder and the registry key undos all changes made by the installer.

The registry key can be deleted with this command if you installed with Firefox:
```
reg delete HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\org.buster.client
```

The client also saves a log file named `buster-client-log.txt` in the TMP folder of the operating system. This file is overwritten every time the client is started to send user input and solve a challenge, and contains data about the received commands, see [this](https://github.com/dessant/buster-client/blob/master/cmd/client/main.go#L49) module for details.

I agree that this needs to be documented, thanks for bringing up the topic.

**Comment by Gitoffthelawn** [comment]
Can you add that excellent information to the README, or a file that the README references?

I haven't installed the new client because I'm still trying to understand it further.

The changelog indicates:

> A new option for user input simulation has been added. A client app enables Buster to send native user input to the browser and helps lower the occurrence of difficult challenges and temporary blocks. Follow the instructions to install the app for Windows, Linux or macOS after enabling the feature from the options page. Requires a new permission: nativeMessaging.

4 Questions:

1. Why does sending native user input to the browser help lower the occurrence of difficult challenges and temp blocks?

2. Also, if I'm reading correctly, it sounds like Firefox can now install executables from third-party developers on the user's system.  Is that correct?

3. If so, how can the user inspect the executable before installing it on their system?

4. Can you add manual installation instructions for those who don't want an extension modifying their system (outside of the Firefox profile)?

Thanks again for Buster!

**Comment by dessant** [comment]
Yes, I'll add this information to the relevant places.

>1. Why does sending native user input to the browser help lower the occurrence of difficult challenges and temp blocks?

The extension needs to navigate in the challenge iframe and perform the steps a user would do while solving the challenge. The only way to send real user input events is from outside the browser, it cannot be done in the context of the extension using JS.

When user input simulation is not enabled the extension navigates using untrusted events created with JS, which is trivial to detect and could trigger a temporary block. By enabling user input simulation and installing the client app, it becomes less likely for the extension will trigger a temporary block or reduce your trust score and cause harder visual challenges to be shown.

>2. Also, if I'm reading correctly, it sounds like Firefox can now install executables from third-party developers on the user's system.  Is that correct?

No, browsers do not install executables offered by extension developers. Extensions tipically show a download link from where you have to download the executable, then run it if it happens to be an installer, or place it in the correct location, create a manifest, and edit the registry. The end result is that the extension will be able to start this executable and communicate with it. You can learn more about this from the [native messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) docs.

>3. If so, how can the user inspect the executable before installing it on their system?

If you would like to build the binary yourself, set up Go and run `make installer` after cloning this repo: https://github.com/dessant/buster-client
The installer will be placed in the `dist` folder, which then you can run.

>4. Can you add manual installation instructions for those who don't want an extension modifying their system (outside of the Firefox profile)?

The extension does not modify your system, the installer you run does. The steps taken by the installer are detailed in the native messaging docs, and the source code for the installer is in the buster-client repository.

**Comment by Gitoffthelawn** [comment]
> The extension needs to navigate in the challenge iframe and perform the steps a user would do...

Great explanation.  Thanks!  Maybe cut and paste into the readme!

> ...You can learn more about this from the [native messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) docs.

On my list of stuff to read!

> If you would like to build the binary yourself, set up Go and run `make installer` after cloning this repo: https://github.com/dessant/buster-client

There it is!  Thanks.  I searched all over this repo for it, without knowing there was a separate repo.  Perhaps add a link to that repo in this repo's readme just like the client repo's readme links to this repo (try saying that 10 times fast!).

> The extension does not modify your system, the installer you run does. The steps taken by the installer are detailed in the native messaging docs, and the source code for the installer is in the buster-client repository.

With few exceptions, I never run installers.  If it's just a few steps, would it be easy for you to document what the installer actually changes in the target system?  I guess if you do that, it would make sense to provide the executable for the client itself in that repo's *releases* section, given that the installer doesn't seem to be something that can easily be unpacked (if it can be, please correct me).

Thanks again for your great answers, and this great project. :+1: 

The number of installed users is steadily increasing, which tells us how much people hate dealing with Google's Recaptcha.

**Comment by AlexaCollins** [comment]
there is a script for Tampermonkey?

**Comment by dessant** [comment]
@AlexaCollins, Buster cannot be implemented properly as a user script, because user scripts do not have access to some of the the browser APIs the extension needs.

**Comment by shortenjukebox** [comment]
I’m having the opposite problem on macOS: What am I supposed to do with the file I download from [buster-client/releases](https://github.com/dessant/buster-client/releases)? It doesn’t have a file extension.

**Comment by dessant** [comment]
@shortenjukebox, make the binary executable if it does not launch, then you can double click on it.
```
chmod +x buster-client-setup-v0.2.0-macos-amd64
```

**Comment by dessant** [comment]
Thr next release will likely contain an unistaller and a wiki with removal instructions.

**Comment by Gitoffthelawn** [comment]
@dessant Thank you! :)

**Comment by luisantunes8500** [comment]
> Yes, on Windows both the binary and the manifest are saved to `AppData\Local\buster` or a different location you have set during installation. Deleting that folder and the registry key undos all changes made by the installer.
> 
> The registry key can be deleted with this command if you installed with Firefox:
> 
> ```
> reg delete HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\org.buster.client
> ```
> 
> The client also saves a log file named `buster-client-log.txt` in the TMP folder of the operating system. This file is overwritten every time the client is started to send user input and solve a challenge, and contains data about the received commands, see [this](https://github.com/dessant/buster-client/blob/master/cmd/client/main.go#L49) module for details.
> 
> I agree that this needs to be documented, thanks for bringing up the topic.

Great work Sebastian
The extension works quite well for me, but I tried every possible way to install the client and it was impossible for me, the same error constantly

[Something went wrong]
[Error: setup must be run without administrative rights]

Win 7 with administrator account and active UAC.
I want to uninstall the client but AppData\Local\buster doesn't exist and I don't have any registry entry. Where is it installed?

**Comment by dessant** [comment]
@luisantunes8500, the setup was aborted before changes were made by the installer, there is nothing to uninstall. Try installing with a user that does not have administrator rights by default, a UAC prompt should appear if you try to install Firefix for example. For more details regarding that error, see this thread: https://github.com/dessant/buster/issues/39

**Comment by imjustd** [comment]
What about Linux uninstallation?

**Comment by phocks** [comment]
Also after Linux uninstall

**Comment by Ceekzs** [comment]
Install Driver Booster by iObit (uncheck third party programs), check the drivers you need in the list, especially the xBox one I guess, install, it should take 5 to 15 mins, reboot, you're done. Worked fine for me.

https://www.iobit.com/en/driver-booster.php

**Comment by injust** [comment]
> Thr next release will likely contain an unistaller and a wiki with removal instructions.

@dessant Sorry to necro such an old issue, but I couldn't find an uninstaller or removal instructions.

Do you have steps for uninstallation for Chrome on macOS? I already removed `~/.local/opt/buster/`, but I'm not sure if there is anything else I need to do.

**Comment by dessant** [comment]
Yes, those two are the files the installer saves to storage, and the manifest location depends on the browser you use.

https://github.com/dessant/buster-client/blob/d4a7880c8eb5196110052d0bdad8c8dd003a8ad8/cmd/setup/main.go#L136
