### ISSUE TITLE
Try Again Later

### ISSUE THREAD

**Issue by xibaxd** [dessant/buster#280]
Hello, I am having this issue where I can't do the recaptcha, even when I try to click manually. Is there anything that I can do to fix this problem? It's happening on Microsoft Edge and Chrome.

Follow the error: Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page.

**Comment by namer707** [comment]
Thanks, I'll be back in a bit!
Hello, this message is used to notify you that it got in my inbox.
If you want to get a hold of me quicker text +1 (845) 444-1639 to ping me.  I'll be back in a few minutes!

If you've seen this before contact me and I'll fix it, or if I haven't yet replied please contact +1 (845) 444-1639.

Thank you and have a nice day,
Benjamin Case

**Comment by xibaxd** [comment]
Hi,

Thank you for contacting me back, I will wait for a possible solution of this issue.

Best,
Eric
________________________________
