### ISSUE TITLE
No Auto click on Buster Icon

### ISSUE THREAD

**Issue by DocMAX** [dessant/buster#281]
**System**
Windows and Linux

**Extension**
v1.1.1 + latest Client

**Bug description**
Integrated into Jdownloader it does click on the initial Captcha Banner, then I have to click manually on the Buster icon in the next window, then it continues with auto-click till the end. Why is it not clicking on the Buster icon?

**Comment by dessant** [comment]
What do you mean by "Integrated into Jdownloader"? Is the extension installed when you install Jdownloader, or have you manually installed Buster yourself?

**Comment by flashcp2003** [comment]
不支持chrome吗?应用商店显示不兼容！

**Comment by dessant** [comment]
@flashcp2003, use a newer Chrome version, the extension is compatible with Chrome 76 and later.
