### ISSUE TITLE
Can I increase the verification code support for some websites?

### ISSUE THREAD

**Issue by lyjhyjyes** [dessant/buster#283]
Hello, my English is not very good, I used machine translation. Can you increase the verification code cracking of websites, foe example zhenbuka.com/bilibili.com/bukaivip.com/bbs.talkop.com/52pojie.cn/right.com.cn/mail@qq.com,these websites are very popular in Chinese. Thank you for your dedication

**Comment by dessant** [comment]
Hi @lyjhyjyes! Unfortunately this extension only supports reCAPTCHA audio challenges, but other challenge types may be implemented in the future. It would be helpful to know what are the most popular reCAPTCHA alternatives in China that also have an audio challenge, please share some direct links to these challenges if you can, and I'll test them in the future.

**Comment by lyjhyjyes** [comment]
> Hi @lyjhyjyes! Unfortunately this extension only supports reCAPTCHA audio challenges, but other challenge types may be implemented in the future. It would be helpful to know what are the most popular reCAPTCHA alternatives in China that also have an audio challenge, please share some direct links to these challenges if you can, and I'll test them in the future.

thanks
