### ISSUE TITLE
It clicks on the top bottom option instead of activating audio

### ISSUE THREAD

**Issue by Project-Magenta** [dessant/buster#284]
**System**

* OS name: [e.g. Windows, Ubuntu] Windows
* OS version: [e.g. 10] 10
* Browser name: [e.g. Chrome, Firefox] Opera GX
* Browser version: [e.g. 60] Chromium ver 73.0.3856.438

**Extension**

* Extension version: [e.g. 1.0.0]

* User input simulation: [e.g. yes, no] yes

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

When I click the buster button with user input fake on, it moves my mouse to the bottom left option instead of clicking on audio challenge button.

**Logs**

Browser:
```
there wasn't an error.
```

Client app:
```
2021/04/22 17:35:51.863869 Starting client (version: 0.3.0)
2021/04/22 17:35:51.863869 Receiving message
2021/04/22 17:35:51.863869 Processing message
2021/04/22 17:35:51.863869 Command: ping
2021/04/22 17:35:51.863869 Sending response
2021/04/22 17:35:51.863869 Receiving message
2021/04/22 17:35:51.884330 Processing message
2021/04/22 17:35:51.884330 Command: moveMouse
2021/04/22 17:35:51.884330 X: 175, Y: 665
2021/04/22 17:35:51.897018 Sending response
2021/04/22 17:35:51.897018 Receiving message
2021/04/22 17:35:52.005919 Processing message
2021/04/22 17:35:52.005919 Command: clickMouse
2021/04/22 17:35:52.029924 Sending response
2021/04/22 17:35:52.029924 Receiving message
```

**Comment by dessant** [comment]
Have you installed the extension from Opera add-ons of the Chrome Web Store?

**Comment by Project-Magenta** [comment]
Web Store

**Comment by Project-Magenta** [comment]
Ok so i used opera store one and works! Thanks
