### ISSUE TITLE
Erreur - Appli / Extension Buster Captcha Solver for humans ne fonctionne plus !

### ISSUE THREAD

**Issue by KickTac** [dessant/buster#285]
Bonjour, je rencontre une difficulté concernant l'utilisation de l'extension "Captcha solver for humans" qui ne fonctionne plus depuis une semaine alors que je n'ai rien changé à la configuration.

Je suis par conséquent contraint de répondre à tous les captchas malgré l'installation de cette appli. J'ai changé de navigateur (je suis sur Chrome et je suis passé sur Mozilla) mais le même problème subsiste. Est-ce que quelqu'un peut me venir en aide ? Je ne sais pas si j'ai ouvert cet incident au bon endroit, dans le doute, veuillez m'en excuser par avance.

Merci à tous les cracks et experts qui pourront gentiment me proposer une solution pour remédier au problème

Bien cordialement

Frantz

![bitmoji](https://sdk.bitmoji.com/render/panel/8f176416-342d-4744-ad16-4ab17c2d8bee-609d3ef1-4bed-4506-bd27-3b6d76d88395-v1.png?transparent=1&palette=1&width=246)

**Comment by dessant** [comment]
Hi Frantz! I don't have enough details to figure out what is the issue on your end, but I think it could help to install the client app and enable the simulation of user interactions, visit the extension's options to get started.

Salut Frantz! Je n'ai pas assez de détails pour déterminer quel est le problème de votre côté, mais je pense que cela pourrait aider à installer l'application cliente et à activer la simulation des interactions des utilisateurs, visitez les options de l'extension pour commencer.

**Comment by KickTac** [comment]
Hello Dessant, first of all thank you for answering me, it's really very kind; due to the language barrier, I am not sure I understood your recommendation. I checked the options of the "Captcha solver for humans" extension: even changing a parameter, unfortunately, captchas keep appearing ...

I am unable to attach an attachment, it's definitely very complicated for me: /

______________________

Bonjour Dessant, tout d'abord merci de m'avoir répondu, c'est vraiment très aimable ; à cause de la barrière de la langue, je ne suis pas certain d'avoir compris votre recommandation. J'ai vérifié les options de l'extension "Captcha solver for humans" : même en changeant un paramètre, malheureusement, les captchas continuent d'apparaître...

Je ne parviens pas à rattacher une pièce jointe, décidément, c'est très compliqué pour moi :/
