### ISSUE TITLE
Failed to fetch console log (something went wrong)

### ISSUE THREAD

**Issue by JoshSchreuder** [dessant/buster#288]
**System**

* OS name: [e.g. Windows, Ubuntu] **Windows**
* OS version: [e.g. 10] **21H1 19043**
* Browser name: [e.g. Chrome, Firefox] **Edge Chromium**
* Browser version: [e.g. 60]  **90.0.818.46**

**Extension**

* Extension version: [e.g. 1.0.0] **1.1.0**

* User input simulation: [e.g. yes, no] **No**

* Client app version: [e.g. 1.0.0] 
* Client app installed successfully: [e.g. yes, no]

**Bug description**

* Open https://www.google.com/recaptcha/api2/demo
* Click Recaptcha
* Click solve button
* Toast notification popup shows something went wrong

I have tried running in fresh window with no other extensions, turning off DNS blocking etc.
This was working as of roughly 2-3 weeks ago but stopped randomly. Might be the Edge 90 update though I think it was also broken earlier than that.

Requests:
![image](https://user-images.githubusercontent.com/681706/116163663-861eb300-a73b-11eb-97ec-3b7bcd0dae37.png)

**Logs**

Browser:
```
Error: Failed to fetch
script.js:formatted:814 Uncaught (in promise) Error: Failed to fetch
    at g (script.js:formatted:814)
g @ script.js:formatted:814
```

![image](https://user-images.githubusercontent.com/681706/116163716-a0589100-a73b-11eb-8b42-5096833918ca.png)

Client app:
```
N/A
```

**Comment by dessant** [comment]
I can't reproduce this issue on Edge 90.0.818.51, maybe some other extension or browser setting is interfering, please let me know if you find a way to reliably trigger the error with a fresh Edge profile.

**Comment by JoshSchreuder** [comment]
Indeed, seems to be working now for me. Weird, anyway, thanks for having a look. Will let you know if I can repro.
