### ISSUE TITLE
automatically clicking on the buster icon after clicking the captcha?

### ISSUE THREAD

**Issue by Manodragon** [dessant/buster#29]
Hello all/@dessant! Basically I have no idea about developing apps and writing code but I was wondering:
Is it possible to activate buster automatically after clicking on the captcha?

**Comment by dessant** [comment]
It would be possible, but it is not a desired feature for this project because it would become easier to abuse the extension. Clicking on the extension button is required to solve a challenge.

**Comment by Manodragon** [comment]
P.S. Thank you for your work!
