### ISSUE TITLE
Cannot compile on Wayland: xkbcommon-x11.h missing

### ISSUE THREAD

**Issue by raffaem** [dessant/buster#295]
**System**

* OS name: Fedora Workstation
* OS version: 34
* Browser name: Firefox
* Browser version: 88.0.1 (64-bit)

**Extension**

* Extension version: 1.2.0

* User input simulation: No, app doesn't compile

* Client app version: git master
* Client app installed successfully: no

**Bug description**

```
$ make -C ..
make: Entering directory '/home/raffaele/bin/buster-client'
Building client (version: 0.3.0, os: linux, arch: amd64)
# github.com/robotn/gohook
In file included from ./event/pub.h:20,
                 from ./event/goEvent.h:18,
                 from ../../go/pkg/mod/github.com/robotn/gohook@v0.0.0-20200205143957-aea663e2b531/hook.go:22:
./event/../hook/x11/input_c.h:40:10: fatal error: xkbcommon/xkbcommon-x11.h: No such file or directory
   40 | #include <xkbcommon/xkbcommon-x11.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:37: build] Error 2
make: Leaving directory '/home/raffaele/bin/buster-client'
```

It may be related to the fact that I am using Wayland and so don't have the X11 subsystem. Is it supposed to compile on Wayland?

**Logs**

Browser:

Logs are empty

Client app: App doesn't compile

EDIT: Updated error message after having installed `libxkbcommon-devel`

**Comment by dessant** [comment]
I use these dependencies to compile the client app on Ubuntu 18.04: https://github.com/dessant/buster-client/blob/8822d4c601a2395d76d8064f69edf2d6095e6047/.github/workflows/ci.yml#L81

**Comment by raffaem** [comment]
> I use these dependencies to compile the client app on Ubuntu 18.04: https://github.com/dessant/buster-client/blob/8822d4c601a2395d76d8064f69edf2d6095e6047/.github/workflows/ci.yml#L81

And these dependencies contain the X11 server (`libx11-dev`).

So I'm not sure about your answer or why you closed the bug report.

I report that I cannot compile the application on Wayland, and you basically answered "well, I use X11 not Wayland".

Anyway it looks like you don't use X11 directly but through `robotn/gohook`, so I opened an issue there also.
