### ISSUE TITLE
Support for captcha from Solve Media

### ISSUE THREAD

**Issue by skanga** [dessant/buster#297]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

The captcha from Solve media also includes an audio version. So it may be possible to add that.
Support for this would be a terrific and useful addition to Buster.

**Describe alternatives you've considered**

**Additional context**

**Comment by bmn001** [comment]
This has been requested and declined in the past as Solve Media was considered to be not evil enough:
https://github.com/dessant/buster/issues/101

I would like to see it added as well.

**Comment by dessant** [comment]
Issue is tracked at https://github.com/dessant/buster/issues/318.
