### ISSUE TITLE
Buster icon grayed out

### ISSUE THREAD

**Issue by cdhans** [dessant/buster#298]
I install from Opera extensions but icon on address bar and Buster listing in drop down list which opens when clicking extensions icon are both grayed out.  Allow access to search page results is checked.  What is missing?  What does Buster want to see that is not present?

Opera 77.0.4054.64
W10

**Comment by dessant** [comment]
You should see a clickable extension button in the reCAPTCHA widget, the button in the toolbar has no function in solving the challenge, it is only put there by the browser.
