### ISSUE TITLE
Buster The Amount

### ISSUE THREAD

**Issue by Hantk33** [dessant/buster#299]
**System**

* OS name: [Windows]
* OS version: [10]
* Browser name: [Crypto Browser]
* Browser version: [1]

**Extension**

* Extension version: [1.0.0]

* User input simulation: [yes]

* Client app version: [1.0.0]
* Client app installed successfully: [yes]

**Bug description**
Buster informs that the amount has already been exceeded, I would like to know how to fix this error

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
You mean the API quota has been exceeded? That can happen sometimes when you use the default speech service, depending on how many users are simultaneously accessing the extension.

You should use your own API key to avoid the issue: https://github.com/dessant/buster/wiki/Configuring-Wit.ai
