### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by babyrig** [dessant/buster#3]
@dessant as requested (I don't know much but if you can tell me the steps may I can be more helpful)

1 - I got this error "Something went wrong" first here in my desktop but after some adjusting in noscript or something like that I got no more errors but not solving either with Firefox and depend on Firefox version I can't add or select the API DEMO or KEY, don't show anything.

2 - I have tried with Firefox in a linux Ubuntu 16.04 vnc connection and got the message in the console about sound then I searched and followed the steps to install unrestricted software to have media/audio player (but I don't think will have sound anyway) it's necessary to have a sound device ? But after have installed I don't have anymore the message about no media but I don't got anything else. (need to test with Opera since the Opera so far worked in other environment fine)

3 - Via RDP connected to windows machine tried with firefox no success but worked with Opera without issues (most the times I have the blocked messages but when enable opera vpn works fine)

4 - Now with another browser Waterfox in windows(RDP session) and checking the console the last message displays:

TypeError: Not enough arguments to OfflineAudioContext.

and with the pop-up of Something went wrong

If you tell me with steps to do I can test more.

![captcha_addon1](https://user-images.githubusercontent.com/38074298/49608741-907c5e80-f980-11e8-8910-a3a9873b6745.JPG)

**Comment by dessant** [comment]
Thanks for the bug report! It looks like older browser versions do not accept and object with parameters for OfflineAudioContext, I'll release a fix for that.

Could you test with the latest version of Firefox, or at least version 57, and the DEMO service on your local PC?

**Comment by babyrig** [comment]
> Thanks for the bug report! It looks like older browser versions do not accept an object with parameters for OfflineAudioContext, I'll release a fix for that.
> 
> Could you test with the latest version of Firefox, or at least version 57, and the DEMO service on your local PC?

I have confirmed now with Opera (Version:57.0.3098.91) worked fine in Ubuntu (System:Ubuntu 16.04.5 LTS (x86_64; Unknown) via vnc in the first attempt, it's really cool :)

Still can't confirm on your request in a new Firefox version here on local pc due maybe I am a robot and google don't let me try even in the demo recaptcha :( 

But so far worked fine with opera in private mode (allowed the addon on private mode too) here in the local pc.

So there is any restrictions/incompatibility with old Firefox versions prior to 53 ?

Any tips/ideas on how often I can request/test the captcha to not be flagged as robot ? (yes changed ip, private mode, clean cookies and stuff nothing help)

**Comment by dessant** [comment]
> So there is any restrictions/incompatibility with old Firefox versions prior to 53?
Yes, even after the fix, Firefox versions before 53 will not be supported. The current release of the extension should work with Firefox 57+, but I'm not using vnc/rdp, so that is not tested or supported.

Not sure how to get around the block, other than the things you already tried.

Thanks for testing, I'll release a fix for the OfflineAudioContext bug.

**Comment by babyrig** [comment]
> It sounds like you want to solve an unhealthy amount of captchas

I think is more by my ip been flagged before as dirty ones I will keep trying to change (dynamic pppoe) but looks like keep worst at every change. Anyways I hope for the update for firefox.

And about the chrome version waiting be released by the review team soon to see if works better :)

**Comment by dessant** [comment]
Version 0.1.1 was published for Firefox, that should lfix the internal error on Waterfox.

**Comment by babyrig** [comment]
> Version 0.1.1 was published for Firefox, that should fix the internal error on Waterfox.

working confirmed 100%. Thank you

![captcha_addon2](https://user-images.githubusercontent.com/38074298/49617451-c2e78500-f99b-11e8-9956-b843f3a0e86e.JPG)

**Comment by dessant** [comment]
Great! Thanks for your tests!

**Comment by erxxsu** [comment]
hi i have latest version of chrome and latest version of buster extention but i give something went wrong error
