### ISSUE TITLE
Can you explain the (new) required permissions?

### ISSUE THREAD

**Issue by coaxial** [dessant/buster#30]
The addon updated yesterday and is asking for new permissions on Firefox (exchange messages with other programs, access navigation info)

Can you explain what these are for? It would help increase confidence in the addon and encourage people to install it.

**Comment by dessant** [comment]
The new features they enable are listed in the release notes for 0.4.0 on AMO: https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-solver/versions/

> - A new option for user input simulation has been added. A client app enables Buster to send native user input to the browser and helps lower the occurrence of difficult challenges and temporary blocks. Follow the instructions to install the app for Windows, Linux or macOS after enabling the feature from the options page. Requires a new permission: nativeMessaging.
> - A reload button is shown when the challenge is temporarily blocked. This button resets the CAPTCHA widget without reloading the entire page. Requires a new permission: webNavigation.

**Comment by coaxial** [comment]
Thank you

**Comment by horusra** [comment]
Where is this client app? Follow what instructions?????

**Comment by dessant** [comment]
Details about the required permissions and the client app have been added to the extension listing.

https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-solver/
