### ISSUE TITLE
reCAPTCHA network error occurs half the times 

### ISSUE THREAD

**Issue by aerdnar** [dessant/buster#300]
> You may experience a temporary block when trying to solve a reCAPTCHA audio challenge.
> This error is outside the control of the extension, and should not be reported as a bug.
> Visit the wiki to learn more about the issue.
> 
> https://github.com/dessant/buster/wiki/Inaccessible-reCAPTCHA-audio-challenge

On Firefox I'm always able to solve audio challenge manually without get this error (tried 20 times on https://patrickhlauke.github.io/recaptcha/) but using buster "network/unknown error" occurs half the times, maybe they are timing how fast you are typing and solving the challenge detecting when you are a user or not. 
On Chromium based browsers there is the temporary block but what happen on Firefox can demonstrate that they are detecting buster extension in some way. 

**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 89

**Extension**

* Extension version: 1.2.0

* User input simulation: no 

**Bug description**

![immagine](https://user-images.githubusercontent.com/26771443/122636024-5c548d80-d0e7-11eb-9922-3bfa2ef0568b.png)
![immagine](https://user-images.githubusercontent.com/26771443/122636040-6aa2a980-d0e7-11eb-99d5-868ce9c8494d.png)

**Comment by dessant** [comment]
As the wiki article you linked to suggests, install the client app.
