### ISSUE TITLE
Could not move extension directory into profile.

### ISSUE THREAD

**Issue by soumik2012** [dessant/buster#301]
**System**

* OS name:  Windows,
* OS version:  10
* Browser name:  Chrome
* Browser version: 60

**Extension**

* Extension version: 1.2.0

* User input simulation: [e.g. yes, no]

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: NO

**Bug description**

**Logs**

Browser:
![image](https://user-images.githubusercontent.com/66599363/125037209-79122e80-e0b1-11eb-8662-ffe8b0f8121d.png)

**Comment by namer707** [comment]
Thanks, I'll be back in a bit!Hello, this message is used to notify you that it got in my inbox.
If you want to get a hold of me quicker text +1 (845) 444-1639 to ping me.  I'll be back in a few minutes!

If you've seen this before contact me and I'll fix it, or if I haven't yet replied please contact +1 (845) 444-1639.

Thank you and have a nice day,
Benjamin Case

**Comment by dessant** [comment]
The extension is only supported on Chrome 76 or newer.

**Comment by soumik2012** [comment]
@dessant 
![image](https://user-images.githubusercontent.com/66599363/125040944-d4462000-e0b5-11eb-97e6-15ddf9923455.png)
see my version is above 76 still not supporting

**Comment by soumik2012** [comment]
@dessant could you explain

**Comment by dessant** [comment]
I thought you use Chrome 60 because that's what you have said in the bug report. The error you see is a Chrome bug that I cannot help you with.

https://windowsreport.com/chrome-could-not-move-extension-directory-into-profile/

**Comment by soumik2012** [comment]
actually, I have downloaded another extension it's not showing me the error but if downloaded you it's give me the error.

**Comment by soumik2012** [comment]
> actually, I have downloaded another extension it's not showing me the error but if downloaded you it's give me the error.

@dessant
