### ISSUE TITLE
could not move extension directory into profile 

### ISSUE THREAD

**Issue by soumik2012** [dessant/buster#302]
**System**

* OS name:  Windows,
* OS version:  10
* Browser name:  Chrome
* Browser version: 94 

**Extension**

* Extension version: 1.2.0

* User input simulation: [e.g. yes, no]

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: NO

**Bug description**

**Logs**

Browser:
![image](https://user-images.githubusercontent.com/66599363/125037209-79122e80-e0b1-11eb-8662-ffe8b0f8121d.png)

**Comment by dessant** [comment]
See my reply here: https://github.com/dessant/buster/issues/301#issuecomment-876981990
