### ISSUE TITLE
Buster has stopped working (API response: 400)

### ISSUE THREAD

**Issue by aak830117** [dessant/buster#303]
Error: API response: 400, {
  "code": "no-auth",
  "error": "Bad auth, check token/params"
}

Thanks for your extension.
I supposed there's something wrong on your api.
I got this error since a few hours ago.

**Comment by dessant** [comment]
I've just checked, and my Facebook account has simply disappeared. Does Facebook delete accounts without any notification?

The default speech service is using API keys from Wit.ai, which requires a Facebook account. If someone has an account and would like to share Wit.ai API keys to publish with the extension, please let me know. It would help a lot, because the extension will not work by default for anyone until working API keys are supplied.

There is a workaround though, you can switch to a different speech service, or continue using Wit.ai by setting up your own apps. Here is a guide for configuring Wit.ai:

https://github.com/dessant/buster/wiki/Configuring-Wit.ai

**Comment by lamtonylam** [comment]
Problem happening for me too

**Comment by aak830117** [comment]
> I've just checked, and my Facebook account has simply disappeared. Does Facebook delete accounts without any notification?
> 
> The default speech service is using API keys from Wit.ai, which requires a Facebook account. If someone has an account and would like to share Wit.ai API keys to publish with the extension, please let me know. It would help a lot, because the extension will not work by default for anyone until working API keys are supplied.
> 
> There is a workaround though, you can switch to a different speech service, or continue using Wit.ai by setting up your own apps. Here is a guide for configuring Wit.ai:
> 
> https://github.com/dessant/buster/wiki/Configuring-Wit.ai

Thanks for your help.

**Comment by sidni8106** [comment]
Hello dessant. Thanks for your help.

**Comment by GiveDaData** [comment]
Thank you for the update.

Is there any way we could change the default API key through modifying the extension files locally?
So that when opening the browser with the buster for the first time, it would have our own API key.

**Comment by DarthGigi** [comment]
So how would it take to get a new API? Is there any ETA?

**Comment by tacohitbox** [comment]
> If someone has an account and would like to share Wit.ai API keys to publish with the extension, please let me know. 

``FRKMPCAFH32RLWFKWSOAB75PML3ELHLL`` for English

**Comment by StrangePeanut** [comment]
I keep getting `Cannot contact reCAPTCHA. Check your connection and try again.` using IBM Watson on Firefox. Things work fine on Edge. Is this related?

**Comment by xCreeperYT** [comment]
> 
> 
> > If someone has an account and would like to share Wit.ai API keys to publish with the extension, please let me know.
> 
> `FRKMPCAFH32RLWFKWSOAB75PML3ELHLL` for English

Thanks! Works fine with that API key.

**Comment by NextDev65** [comment]
> I've just checked, and my Facebook account has simply disappeared. Does Facebook delete accounts without any notification?

https://webapps.stackexchange.com/questions/14017/facebook-account-got-deleted-for-no-reason-without-warning-or-notification

**Comment by enerage** [comment]
Can we add the provided key from tacohitbox as a default one, please?

**Comment by dessant** [comment]
@tacohitbox, thanks for sharing the key, it must have helped a lot of users!

**Comment by dessant** [comment]
The issue was solved in the latest update, though the recommendation remains the same: please use your own API keys whenever possible, the default speech service is rate limited and can break at any time.

https://github.com/dessant/buster/wiki/Configuring-Wit.ai

**Comment by dessant** [comment]
Here's a guide for configuring IBM Watson: https://github.com/dessant/buster/wiki/Configuring-IBM-Watson-Speech-to-Text
