### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by rakleed** [dessant/buster#309]
**Is your feature request related to a problem? Please describe.**
At night or in dark rooms, it is frustrating to use the extension settings due to the bright white background.

**Describe the solution you'd like**
Please add a dark theme. And make the default sync the extension theme with the system theme.

**Describe alternatives you've considered**

**Additional context**
More details: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by neo-neo1** [comment]
This would be nice. I use dark theme everywhere so this sticks out

**Comment by dessant** [comment]
<img width="295" src="https://user-images.githubusercontent.com/7513068/207506371-687839c4-ec15-4743-aa96-b9b2971b73b5.png">

**Comment by dessant** [comment]
Dark mode support will arrive in the next release.

**Comment by rakleed** [comment]
@dessant if the dark theme is selected and I reload the options, a white background appears for a fraction of a second, which is very annoying.

**Comment by dessant** [comment]
@rakleed, thanks for letting me know, version 2.0.1 should fix the issue.
