### ISSUE TITLE
Can't add the extension to Chrome

### ISSUE THREAD

**Issue by kaiohpj** [dessant/buster#31]
When I try to add it as developer, the browser says that the manifest is missing or can't be reading.

**Comment by dessant** [comment]
Are you trying to install from the GitHub repository?

**Comment by kaiohpj** [comment]
Yes, i just downloaded it from here and tried to install manually

**Comment by dessant** [comment]
You're very eager to try out the new release. :yum: I'll publish it for Chrome too in a couple of days, I just need to sort out a couple of things.

Until then, you can build the extension for Chrome by following one of these guides:
https://github.com/dessant/buster/wiki/Building-the-extension-on-Ubuntu
https://github.com/dessant/buster/wiki/Building-the-extension-on-Windows
