### ISSUE TITLE
Support For Pale Moon

### ISSUE THREAD

**Issue by noellarkin** [dessant/buster#311]
Hi! First of all, thank you so much for this, ReCaptcha makes browsing the internet hell for anyone with a VPN, your plugin saves me so much time :)
So I recently shifted to the Pale Moon browser (it's a fork of the classic pre-quantum Firefox) and was wondering if you would consider making a port of your plugin for Pale Moon (which would allow it to be used by all other similar XUL based browsers like Basilisk, MyPal, Centaury etc)
Thanks!

**Comment by dessant** [comment]
The extension needs to be completely rewritten to support the XUL API, which is unlikely to happen, unless someone will pay for it. If anyone would like to sponsor the development and maintenance of a port, feel free to contact me.
