### ISSUE TITLE
Ransomware warning in Microsoft Defender

### ISSUE THREAD

**Issue by forenta** [dessant/buster#312]
Name: buster-client-setup-v0.3.0-windows-386.exe
Größe: 11807744 Bytes (11 MiB)
CRC32: 75DC17C5
CRC64: BA2B5DCCF2B584B9
SHA256: 69E75B16F90C0DB5DF22E9EB6C7285D3ABF58A1716DDE4A748D62FC11EA9F2A5
SHA1: A95F5BFCD7369544779D09E458BDD885725ED3B6
BLAKE2sp: 3E2B147A770E21FDF7DB2695588CA6658C191D0A0B86976BF28C97C1DDBCE106

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Ransom%3aWin32%2fBlocker&threatid=2147742143

**Comment by dessant** [comment]
Probably a false positive, you could add it to the exclusion list.

https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26
