### ISSUE TITLE
Could you add these functions to the typing and verify button?

### ISSUE THREAD

**Issue by kriztpow** [dessant/buster#32]
Hello friend, it would be good that at the time of writing the answer to the challenge it is done from letter to letter as if a human were the one that was typing.

example: if the answer to the audio is -> your love is my love, that it is written -> y, then o, then u, then r, then space, then l, then o, then v, then e .. .

A very good function is that when you click on the button verify, that it is not in a specific time, but that it is different in each click and in a different point of the box simulating the click of a human.

I do not know if you understand me and excuse my bad English! is an online translator's english

**Comment by dessant** [comment]
If you are using Firefox this feature is already available, go to the extension's options and enable user input simulation, then follow the instructions to install a client app. For Chrome it will be released next week.
