### ISSUE TITLE
Error: API response: 400

### ISSUE THREAD

**Issue by longvosongvo123** [dessant/buster#326]
script.js:formatted:814 Uncaught (in promise) Error: API response: 400, {
  "code": "no-auth",
  "error": "Bad auth, check token/params"
}

**Comment by dessant** [comment]
There is an ongoing service disruption at Wit.ai, they estimate that it will be fixed today. As a workaround, you could switch to a different speech recognition service.

**Comment by mohammad708090** [comment]
Unfortunately, the speech system is also inactive and does not work at all
> There is an ongoing service disruption at Wit.ai, they estimate that it will be fixed today. As a workaround, you could switch to a different speech recognition service from the extension's options.

**Comment by mohammad708090** [comment]
The problem has not been solved yet
> There is an ongoing service disruption at Wit.ai, they estimate that it will be fixed today. As a workaround, you could switch to a different speech recognition service from the extension's options.

**Comment by mohammad708090** [comment]
The problem has not been solved yet

**Comment by dessant** [comment]
Please don't spam this issue with your update requests, visit https://wit.ai instead. There's a popup about the service disruption on the main page, follow the links and ask Facebook employees directly when will they solve the issue.

In the meantime, you can always switch to a different speech recognition service from the extension's options, there are guides linked on how to get an API key for each service.

**Comment by dessant** [comment]
Verison 1.3.1 has been published with a workaround. It's possible that the Wit.ai team will mess up things again as they restore the broken API keys, let me know if the error reappears in the next few days.
