### ISSUE TITLE
All browser extensions locked after installation. How to uninstall?

### ISSUE THREAD

**Issue by ChristopherusColumbus** [dessant/buster#333]
**System**
* OS name: MacOS
* OS version: 10.15.7
* Browser name: LibreWolf, Iridium
* Browser version: (94.01), (2021.12)

**Extension**
Buster Client on MacOS.

* Extension version: 1.3.1
* User input simulation: yes
* Client app version: v0.3.0
* Client app installed successfully: yes

**Bug description**
I installed the browser extension some time ago. Because I sometimes an error I also installed the Client App today (following the installation guide for MacOS). Directly after installation I started to experience a problem that I cannot disable/enable other extensions in my browser anymore. All are stuck. 
If I remove the 'buster' folder from /Users/myusername/.local/opt/ it works again in LibreWolf but not in Iridium..
How to uninstall the client app properly? 

**Logs**
I cannot find any buster-client-log logfiles on MacOS.

**Comment by dessant** [comment]
In addition to the `.local/opt/buster` folder, the client app installer creates a manifest file on macOS, the path of which depends on the browser, and it can be edited during the installation process. The manifest for Chrome would be in the ` /Users/myusername/Library/Application Support/Google/Chrome/NativeMessagingHosts` folder by default. When you use an alternative browser, this is the path you have to edit during installation for it to be successful.

https://github.com/dessant/buster-client/blob/8822d4c601a2395d76d8064f69edf2d6095e6047/cmd/setup/main.go#L126-L150

An extension or manifest file should not be able to affect the state of other extensions, you should report the bug to the maintainers of these browsers.

**Comment by chriscapisce** [comment]
Thanks @dessant, you are right. It was something about the browsers functionality that I didn't expect.
