### ISSUE TITLE
Can't click on button

### ISSUE THREAD

**Issue by M-Zubair10** [dessant/buster#334]
Hello, I use selenium to bypass bot verification. I managed to click I am not a robot then there is a button named solver-captcha something like that in inspect element and i copied the XPATH of that but my script failed to click it can you tell why?

**Comment by dessant** [comment]
This extension is not the solution you're looking for.

**Comment by M-Zubair10** [comment]
How to activate it?
Using the buster button on the bottom of the captcha is there any hotkey or
you might set it for me

**Comment by M-Zubair10** [comment]
??

**Comment by dessant** [comment]
I think I have been clear that this project should not be used for automation. You are clearly looking for a solution to solve a large number of challanges a day, and you want to abuse the extension. You have been banned.
