### ISSUE TITLE
Something went wrong The installation has failed. Check the browser console for more details, and open an issue on GitHub if this error persists.

### ISSUE THREAD

**Issue by JuanConti01** [dessant/buster#336]
**System**

* Operating system name: [Windowsu]
* OS version: [10]
* Browser name: [Chrome]
* Browser Version: [Version 98.0.4758.82 (Official Build) (64-bit)]

**Extension**

* Extension version: [1.3.1]

**Error description**

**Records**

 CHROME
"DevTools could not load source map: Could not load content from chrome-extension://bfnaelmomeimhlpmgjnjophhpkkoljpa/content_script/inpage.js.map: HTTP Error: status code 404, net::ERR_UNKNOWN_URL_SCHEME"

`

**Comment by jin8864** [comment]
I also ran into the same issue. Anybody?

**Comment by dessant** [comment]
You could set the antivirus to ignore the installer, or disable it for the duration of the installation.
