### ISSUE TITLE
buster captcha solver for humans (The extension is not working)

### ISSUE THREAD

**Issue by MoatazNassar** [dessant/buster#338]
hello
The extension is not working, I tried to delete it and install it again and use other versions of the browser, but the same problem does not work
The extension version is 1.3.1 Is there a solution?

**Comment by egorjo** [comment]
Hello, the extension is not working. When will it work?

**Comment by MoatazNassar** [comment]
The extension needs to be updated and I am not the developer, so you have to wait for the developer's response

> Hello, the extension is not working. When will it work?

**Comment by lovaxi** [comment]
Have same problem, wait for the developer

**Comment by lovaxi** [comment]
I used the wit.ai, and get a null response.

**Comment by MoatazNassar** [comment]
> I used the wit.ai, and get a null response.
what do you mean wit.ai 🤔 ?

**Comment by lovaxi** [comment]
> > I used the wit.ai, and get a null response.
> > what do you mean wit.ai 🤔 ?

I used the wit.ai to recognize audio. And in F12 window it shows null response.

**Comment by MoatazNassar** [comment]
> What is the operating system you are working on?

**Comment by MoatazNassar** [comment]
The add-on has returned to work, however, we need the developer to update it

**Comment by lovaxi** [comment]
> > What is the operating system you are working on?

Linux

**Comment by lovaxi** [comment]
> The add-on has returned to work, however, we need the developer to update it

Acutally it works again. Thanks for attention.

**Comment by MoatazNassar** [comment]
> > The add-on has returned to work, however, we need the developer to update it
> 
> Acutally it works again. Thanks for attention.

Yes, it works, but it may be interrupted again at any moment, so it must be updated from the developer, we will wait for the developer's response

**Comment by dessant** [comment]
Wit.ai had an outage, there is nothing to update.

**Comment by MoatazNassar** [comment]
> 

What is the reason, is the update stopped forever?

**Comment by Program-true** [comment]
bonjours j'ai un petit soucis avec l'application, aucune interaction avec le captcha , je suis sur google chrome, quelqu'un pourrais m'aidez ?
