### ISSUE TITLE
I also got "something went wrong, check your browser console" Chrome.

### ISSUE THREAD

**Issue by mojo22088** [dessant/buster#34]
Please. Help me, Look screenshots. Thats console of Google Chrome
![ejrdbtu2efi](https://user-images.githubusercontent.com/48070142/53522576-b894dd00-3aeb-11e9-99fe-3d37e3716719.jpg)

**Comment by dessant** [comment]
The default speech recognition service seems to be unavailable. Visit the options of the extension and select the "Wit Speech API (demo)" speech service.

**Comment by mojo22088** [comment]
Thanks bro!
