### ISSUE TITLE
Can not see Buster button in CAPTCHA window

### ISSUE THREAD

**Issue by jnobile91** [dessant/buster#342]
**System**
* OS name: Windows
* OS version: 10
* Browser name: Chrome
* Browser version: 100.0.4896.60

**Extension**
* Extension version: 1.3.1
* User input simulation: Can't find this setting

**Bug description**
I am unable to view the Buster button on the CAPTCHA window. The extension appears to be loaded correctly, but there is no visible button to solve the CAPTCHA Screenshot here: https://imgur.com/8z1K01B

**Logs**
Browser:
```
Nothing in console.
```

**Comment by dessant** [comment]
I have just tested with the same browser and the extension button is at the bottom of the challenge popup. Have you refreshed the page after installing the extension?

**Comment by jnobile91** [comment]
Yes, I have tried to refresh. Still unable to see any Buster button in the challenge window.

**Comment by dessant** [comment]
Were the extension settings changed to limit site access, or is there a different extension installed that could interfere? It's also possible that Google is testing a change, but that should have caused more bug reports by now.

![screenshot](https://user-images.githubusercontent.com/7513068/162249263-bb186626-fc09-4dc3-ad8b-84da04d2c2fc.png)

**Comment by jnobile91** [comment]
I disabled all other extensions (Only had Google Drive active) and still receiving the same issue.

![image](https://user-images.githubusercontent.com/61030579/162261161-83c4e9a1-250b-4b32-bf8d-a70707a16e7f.png)

**Comment by jnobile91** [comment]
I also just had a few coworkers test this using the same version of Chrome and Buster. Looks like they are also having the same issue. I know Chrome recently updated to version 100 a few days ago. Is it possible that this version is preventing it from loading correctly?

**Comment by jnobile91** [comment]
I just installed the extension and attempted to get this working on the existing version of Chrome (v100). I don't believe there is any browser monitoring software running, but I can confirm with IT perhaps. I'm not able to view any error log either, since I don't believe it is initializing at all.

Thank you so much for your help to this point. Sincerely appreciate it!

**Comment by BenjaminDaSilva** [comment]
Same issue here on Win10 / Chromium Edge 100.0.1185.39

**Comment by jnobile91** [comment]
Any suggestions?

**Comment by BenjaminDaSilva** [comment]
So it's working here in Google Chrome 100.0.4896.127 (Official Build) (32-bit) now - for wti.ai (managed) apparently the quota is used up, but I've created a free IBM Watson speech to text account and with that it works just fine.

The "Solve" Button is still not shown in Chromium Edge 100.0.1185.50 (Official Build) (64-Bit) though. Maybe a 32bit vs 64bit thing?
![image](https://user-images.githubusercontent.com/60874902/165244653-45ca3657-28e5-4971-8ce7-df8ef6580f03.png)

**Comment by dessant** [comment]
If it isn't a browser bug, one possibility could be that the challenge is served from a different host that is not known to the content script. Please open the challenge popup, then paste this in the page console (Ctrl+Shift+J) and share the output:

```js
document.querySelectorAll('iframe').forEach(item => console.log(item.src))
```

Also check if the target element of the extension button is reachable. Switch the current frame in the console from `top` to the frame name that ends with `(bframe)` while the challenge popup is still open, then run this command:

```js
document.querySelector('#recaptcha-help-button')
```
![Screenshot](https://user-images.githubusercontent.com/7513068/165302510-9721243b-4e95-4d87-ba20-37f0dbacdcf1.png)



You could also go to `chrome://extensions/?id=mpbjkejclgfgadiemmefgebjfooflfhl`, turn on `Developer mode` and `Collect errors`, then restart the browser, open the challenge popup and revisit the extension page. Any error in the background script should be shown in the console when you click on `Inspect views src/background/index.html`.

**Comment by yejinson** [comment]
> If it isn't a browser bug, one possibility could be that the challenge is served from a different host that is not known to the content script. Please open the challenge popup, then paste this in the page console (Ctrl+Shift+J) and share the output:
> 
> ```js
> document.querySelectorAll('iframe').forEach(item => console.log(item.src))
> ```
> 
> Also check if the target element of the extension button is reachable. Switch the current frame in the console from `top` to the frame name that ends with `(bframe)` while the challenge popup is still open, then run this command:
> 
> ```js
> document.querySelector('#recaptcha-help-button')
> ```
> 
> ![Screenshot](https://user-images.githubusercontent.com/7513068/165302510-9721243b-4e95-4d87-ba20-37f0dbacdcf1.png)
> 
> You could also go to `chrome://extensions/?id=mpbjkejclgfgadiemmefgebjfooflfhl`, turn on `Developer mode` and `Collect errors`, then restart the browser, open the challenge popup and revisit the extension page. Any error in the background script should be shown in the console when you click on `Inspect views src/background/index.html`.

I didn't understand these content, the extension will report an error in chrome101, although there is no error in the old version, but still can't see the buster button, it should be that CAPTCHA should be upgraded, please follow up and release a new version, thank you for your hard work.
<img src='https://s2.loli.net/2022/04/30/AmJ83HZXg2kLUot.png' title='quicker_7e8d78de-6dfe-4905-b2d5-2eac42d39d1c.png' />

**Comment by BenjaminDaSilva** [comment]
![image](https://user-images.githubusercontent.com/60874902/167849096-060cb1ea-307d-46fd-86dd-e231723b2c11.png)

**Comment by BenjaminDaSilva** [comment]
The demo above is maybe not the best example, also doesn't work in Chrome. The following one works in chrome but not in Chromium Edge:
![image](https://user-images.githubusercontent.com/60874902/167852612-fcac01e6-734f-40b8-93d8-72fe354ad648.png)
![image](https://user-images.githubusercontent.com/60874902/167852633-e19741fd-d494-4a6b-a287-a6b787d45b05.png)

**Comment by tjengbudi** [comment]
hello,
my problem is related to this, however i can show. but i cannot click it with my python program. 
![image](https://user-images.githubusercontent.com/3039807/177036152-2450132e-0cd7-4b0b-8d84-7c0f622b63ce.png)

#shadow-root <= what is this used for? any chance to ger rid about this?
if not how to access it by xpath? css_selector? i cannot found by id

**Comment by dessant** [comment]
@tjengbudi, don't use this extension in your scripts.

**Comment by dessant** [comment]
I can't reproduce the issue after several attempts since the bug report was opened, if someone finds a way to reproduce the issue and get some error logs, please let me know.
