### ISSUE TITLE
the setup is broken (for me)

### ISSUE THREAD

**Issue by mmfs37** [dessant/buster#343]
* User input simulation: Not sure? idk how it works here screenshot
![image](https://user-images.githubusercontent.com/100991030/166109927-139e557a-9b8b-4c62-a148-c57a25411f48.png)

* Client app version: [e.g. 0.3.0]
* Client app installed successfully: [e.g. not really no]

**Bug description**

**Logs**
Browser:
```
setup:1 Unchecked runtime.lastError: The message port closed before a response was received.
:50530/favicon.ico:1          Failed to load resource: net::ERR_EMPTY_RESPONSE
```
![image](https://user-images.githubusercontent.com/100991030/166110023-5dfbd3a3-df4b-459c-917f-2b15e397816d.png)

**Comment by dessant** [comment]
Is that the release version of Brave?

**Comment by mmfs37** [comment]
![image](https://user-images.githubusercontent.com/100991030/166110769-309adb43-3247-4e12-bfa8-7a70bd1fab4e.png)
It's the most up-to-date official built that I could install via the settings menu

**Comment by dessant** [comment]
I have just tested it and the client app is installed in Brave on Windows. Have you pressed the INSTALL APP button? :smile:

**Comment by mmfs37** [comment]
yep thats the problem. I can't. The website does not respond. I try to press the install button and nothing happens. I try to change the file directory, it does not even let me click into the file trajectory. The complete website acts like an image and not interactable.

**Comment by dessant** [comment]
Ok, that's too paranormal for me. Please create a screen recording of the entire installation process, beginning with double clicking the client app installer. Attempt to click the install button and the input in the video, then open the console of the page so we can see if there is any error after the clicks, then navigate to the Elements tab of the developer tools that is before the Console tab. Follow the instructions closely. You can attach an mp4 file here in a comment or upload it anywhere else, such as Dropbox.

If the first image is an actual screenshot of your screen and you haven't edited in the app installation widget on the right, there is nothing I can do and your browser may be corrupted or the video driver is acting up. The app installer should open an entirely new tab during installation.

**Comment by mmfs37** [comment]
gonna do it, (via gif format but should be equally good) sadly you won't be able to see the clicks. My video recording program can't show mouse-clicks

**Comment by dessant** [comment]
It's also possible that a browser extension is messing with your clicks, Vimium might be a good candidate. You could disable all the other extensions an restart the browser, then attempt to install again.

**Comment by mmfs37** [comment]
got vimium installed lemme check. 
Btw screen recording is to big Im gonna upload it 
https://imgur.com/a/gjERJx8

**Comment by mmfs37** [comment]
ok deactivated all extensions, now added buster again, refreshed and it worked. 
Should have checked that myself, stupid mistake from my side. Sorry for disturbing.

never had problems with clicking buttons with my current extensions, but I added today bout 5-6 new ones so maybe that's the problem. I am gonna figure the rest out

thank you for your help

**Comment by dessant** [comment]
I'm glad you could make it work, make sure to test which extension was causing the issue and let the developers know.
