### ISSUE TITLE
can you please add opera gx support :(

### ISSUE THREAD

**Issue by Ezekiel-Game** [dessant/buster#349]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I need support for opera gx since I use it (yes yes it's not as popular as chrome)  but can u please add support 👍

**Comment by dessant** [comment]
The extension should work with all Chromium forks. From where did you install the extension? Please also describe what doesn't work.

**Comment by Ezekiel-Game** [comment]
> The extension should work with all Chromium forks. From where did you install the extension? Please also describe what doesn't work.

the icon doesn't pop up also already gave it all the permissions it needs also downloaded from chrome store

**Comment by dessant** [comment]
On which site are you testing? Please share an URL and describe how to reach the reCAPTCHA popup so we can test the same thing.

**Comment by Ezekiel-Game** [comment]
woah i feel like an idiot if only there was an IQ booster thing but thank you the search page results worked

**Comment by Ezekiel-Game** [comment]
1 thing how do i use image solver instead of sound thingy solve

**Comment by dessant** [comment]
Don't sweat it, I was also staring at the missing button for a while as I was testing, wondering if this is a bug. :yum: 

The extension does not support object recognition, so it can only solve the audio challenge for now.

**Comment by Ezekiel-Game** [comment]
ohh ok lol im still new to coding and computer stuff

**Comment by CodeArtificial** [comment]
I have a question, how can I download Buster client on opera gx? Specifically, what is the manifest location I need to input into the installation page? 

![image](https://user-images.githubusercontent.com/56638985/197423415-d7d8c9bd-45c9-4d59-97a6-def5bb78f204.png)
