### ISSUE TITLE
in chrome store, the version still stays at 0.3.0?   ==?

### ISSUE THREAD

**Issue by huitc** [dessant/buster#35]
can you take the time to upload it? ^^''
pls and thx!! (^W^)))))))))))))))

**Comment by huitc** [comment]
and.. firefox version has been updated to 0.4.1................

**Comment by dessant** [comment]
Firefox gets features early as I'm sorting out some bugs around the client app. The Chrome Web Store listing will be updated when these bugs are fixed.

**Comment by huitc** [comment]
okay~!!!😃

**Comment by huitc** [comment]
nice~!
