### ISSUE TITLE
the extension is crashing for me.

### ISSUE THREAD

**Issue by rorsbkkkfeskdfkae** [dessant/buster#351]
**System**

* OS name: Windows
* OS version: 11
* Browser name: Chromium
* Browser version: 102.0.5005.115

**Extension**

* Extension version: 1.3.1

* User input simulation: no

* Client app version: 0.3.0
* Client app installed successfully: yes

**Bug description**

**Logs**

script.js:1 Uncaught (in promise) Error: Extension context invalidated.
    at script.js:1:7343
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (script.js:1:7026)
    at Object.apply (script.js:1:6455)
    at Object.get (script.js:1:13375)
    at async script.js:1:21318

Client app:

2022/06/19 11:51:34.705324 Starting client (version: 0.3.0)
2022/06/19 11:51:34.705324 Receiving message
2022/06/19 11:51:34.705324 Processing message
2022/06/19 11:51:34.705324 Command: ping
2022/06/19 11:51:34.705324 Sending response
2022/06/19 11:51:34.705324 Receiving message
2022/06/19 11:51:34.706320 Closing client

link of the error and usage: https://youtu.be/TcAl9AKDQ8k

**Comment by rorsbkkkfeskdfkae** [comment]
need help asap.

**Comment by rorsbkkkfeskdfkae** [comment]
+ downloaded from google extension store. reinstalled the buster client app. still doesnt fix the issue

**Comment by dessant** [comment]
The extension works with Chromium. You're using a browser called Incogniton, most likely to sidestep abuse prevention mechanisms on websites.

> Incogniton - Anti-Detect Browser for Multi-Account Management

> Are you tired of working on multiple devices?
> Try our anti detection browser now!

**Comment by rorsbkkkfeskdfkae** [comment]
is it working on incogniton then? or not

**Comment by rorsbkkkfeskdfkae** [comment]
its true, im using multiple devices but the extension is very useful and i really want to have it on all my incogniton profiles.

**Comment by dessant** [comment]
It should work, but I don't know much about this browser. Based on what you shared it looks like a browser bug introduced while attempting to obfuscate the browser's fingerprint. You should contact the maintainer of the browser.

**Comment by rorsbkkkfeskdfkae** [comment]
> It should work, but I don't know much about this browser. Based on what you shared it looks like a browser bug introduced while attempting to obfuscate the browser's fingerprint. You should contact the maintainer of the browser.

should i reinstall the browser? or just ask the maintainer.

**Comment by rorsbkkkfeskdfkae** [comment]
because maybe the browser is dead or something.

**Comment by dessant** [comment]
I think you should contact the browser maintainer to debug the issue.

**Comment by rorsbkkkfeskdfkae** [comment]
alright, thanks for help. have a wonderful day.

**Comment by rorsbkkkfeskdfkae** [comment]
> I think you should contact the browser maintainer to debug the issue.

this is so weird i still cant understand. i click play the video message and it stops. with the simulation user interactions
