### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rorsbkkkfeskdfkae** [dessant/buster#353]
**Is your feature request related to a problem? Please describe.**

Yes. it is. its like a **question**

**Describe the solution you'd like**

Is it possible for the extension to work on incogniton browser or its impossible?

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by dessant** [comment]
See my comment here: https://github.com/dessant/buster/issues/351#issuecomment-1159723753
