### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rorsbkkkfeskdfkae** [dessant/buster#355]
After how long time will the "Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit [our help page](https://developers.google.com/recaptcha/docs/faq#my-computer-or-network-may-be-sending-automated-queries)." recaptcha error go away? after how many days if anybody know. or will it go away before thursday?

**Comment by dessant** [comment]
https://github.com/dessant/buster/wiki/Inaccessible-reCAPTCHA-audio-challenge
