### ISSUE TITLE
Not working in site : https://www.seedr.cc/

### ISSUE THREAD

**Issue by debadattagadanayak** [dessant/buster#359]
**System**

* OS name: [Windows]
* OS version: [11]
* Browser name: [Chrome]
* Browser version: [104.0.5112.81 ]

Unable to resolve the captcha in site : https://www.seedr.cc/

Please find the screenshot:
<img width="858" alt="seedr" src="https://user-images.githubusercontent.com/38793151/184585567-83e23349-1265-4ded-848a-63a0ffeba8fb.png">

**Comment by dessant** [comment]
https://github.com/dessant/buster/issues/319
