### ISSUE TITLE
Install app on Linux Mint Firefox

### ISSUE THREAD

**Issue by zer0de** [dessant/buster#36]
**System**

* OS name: [Linux Mint]
* Browser name: [Firefox]
* Browser version: [65.0.1 (64-Bit)]

**Extension**

* Extension version: [0.4.1]

* User input simulation: [yes]

* Client app version: [0.1.0]
* Client app installed successfully: [no]

**Bug description**

Install of Client failed, Manifest path doesn't shown. manuel add ends in error.

Something went wrong
The installation has failed. Check the browser console for more details, and open an issue on GitHub if this error persists.

![grafik](https://user-images.githubusercontent.com/23240348/53586985-99e52380-3b89-11e9-88ca-f90636f33097.png)

**Logs**

Browser:
```
/js/button.dd024c345fc26f7c7a8d9938b67e5d3d.js". oAfeP2P:1:1
Promise resolved after context unloaded
preload.js:374
Content Security Policy: 'x-frame-options' wird wegen 'frame-ancestors'-Direktive ignoriert.
Error: WebExtension context not found! ExtensionParent.jsm:1038:13
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src").
18:1:1
Content Security Policy: 'x-frame-options' wird wegen 'frame-ancestors'-Direktive ignoriert.
Error: WebExtension context not found! ExtensionParent.jsm:1038:13
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src").
new:1:1
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.github.com/_private/browser/stats. (Grund: Berechtigung/Credential wird nicht unterstützt, wenn die CORS-Kopfzeile 'Access-Control-Allow-Origin' auf '*' gesetzt ist).[Weitere Informationen]
[Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen2]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 134"  data: no]
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://avatars2.githubusercontent.com/favicon.ico blockiert ("default-src").
about:devtools-toolbox : Unable to run script because scripts are blocked internally. 
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
The manifest must be at a specific location on Linux, it depends on the browser. I've left the field customizable in case someone uses a forked browser and needs to customize that path. Installing with the default manifest location should work on Firefox, you'll also need to have libpng12 installed, if there is a different error.
