### ISSUE TITLE
Hi, How can i get more quota for this extention inorder to avoid "exceed quota" every time. Is there any paid subscription ?

### ISSUE THREAD

**Issue by nemo3345** [dessant/buster#365]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dessant** [comment]
You can switch to a different speech recognition service from the extension's options, you'll find a link there on how to get an API key.

**Comment by nemo3345** [comment]
Hi, Thank you for your reply. However, i am not sure how to change different speech recognition service and i dont find any link to get API key ....can you specify how to do it ? appreciate your help.
