### ISSUE TITLE
Chromium: Site access permission `On all sites` is too extensive

### ISSUE THREAD

**Issue by keks24** [dessant/buster#366]
**Is your feature request related to a problem? Please describe.**
The site access permission `On all sites` of the extension is too extensive and should be restricted.

**Describe the solution you'd like**
Since the `speech services` is limited to a static list, it would make sense to hardcode the site access permisson `On specific sites` with pre-defined websites.

The user can then decide, which website should be accessable by the extension.

The following entries are sufficient for the speech service `Wit.at (managed)`:
```no-highlight
https://api.wit.ai/*
https://wit.ai/*
https://www.google.com/*
```

You can test them [on the Google ReCAPTCHA demo page](https://www.google.com/recaptcha/api2/demo).

All other specific websites of the other `speech services` need to be determined.

**Describe alternatives you've considered**
The site access permission `On click` could be used, but it requires clicking on the extension and reloading the website. This is not user friendly and the extension then has access to any websites.

The [Wiki](https://github.com/dessant/buster/wiki) could be used to give the above instrucitons.

**Additional context**
_Buster extension_
![20220902-004743_screenshot](https://user-images.githubusercontent.com/13721064/188025786-dbcbbd6c-2370-426f-8983-b007200dffc0.png)

_Hardcoded example: Chromium Web Store_
![20220902-010034_screenshot](https://user-images.githubusercontent.com/13721064/188026718-903efcad-cb04-451b-9d05-c65e9cf9b333.png)

**Comment by devnoname120** [comment]
@keks24 Did you consider making a pull request?

**Comment by keks24** [comment]
I did, but my programming skills may not be sufficient enough to make changes. I do not know where to start.

**Comment by dessant** [comment]
There are aspects of the extension that require access to web pages, even when they aren't in the active tab. The permission system will likely be reworked when we migrate to Manifest V3.
