### ISSUE TITLE
Can't install client app on FireDragon

### ISSUE THREAD

**Issue by Hate9** [dessant/buster#367]
**System**
* OS name: EndeavourOS
* OS version: N/A
* Browser name: FireDragon
* Browser version: 103.0.2

**Extension**
* Extension version: 1.3.2
* User input simulation: attempting to install
* Client app version: 0.3.0
* Client app installed successfully: no

**Bug description**
Follow the client setup as instructed.

**Logs**
Browser:
`Error: Attempt to postMessage on disconnected port`

**Comment by dessant** [comment]
FireDragon probably stores the browser profile in a custom location in your home directory, edit the manifest location during the installation.
