### ISSUE TITLE
Can not install at mozilla nightly android

### ISSUE THREAD

**Issue by HirumaDaichi** [dessant/buster#369]
**System**

* OS name: [e.g. Windows, Ubuntu]
* OS version: [e.g. 10]
* Browser name: [e.g. Chrome, Firefox]
* Browser version: [e.g. 60]

**Extension**

* Extension version: [e.g. 1.0.0]

* User input simulation: [e.g. yes, no]

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by HirumaDaichi** [comment]
I cant install on mozilla firefox nightly

**Comment by dessant** [comment]
https://github.com/dessant/buster/issues/252
