### ISSUE TITLE
Some sites of Solves reCAPTCHA don't work

### ISSUE THREAD

**Issue by trans9488** [dessant/buster#37]
Some sites of Solves reCAPTCHA don't work

Step 1: First test 2captcha.com
https://2captcha.com When login choose reCAPTCHA
show error message: Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page

Step 2: Test new site in the same browser right away 
https://patrickhlauke.github.io/recaptcha/
But it work will.

Test at the same ip address and the same browser.

**Comment by huitc** [comment]
This is normal, isn't it?

**Comment by dessant** [comment]
Make sure to enable user input simulation, it should also be available for Chrome in a couple of days. for more details about the issue, see this thread: https://github.com/dessant/buster/issues/2#issuecomment-465170785

**Comment by huitc** [comment]
`ctrl + f5`
or
refresh cookie

**Comment by d4k0** [comment]
I've got the same problem on some sites (including the first one). I'm using Firefox 65.0.2 with Buster 0.5.1 on Windows 10. Buster client 0.2.0 was installed today and it seems to work (I tried it on the second site), but on the first site I still get the automated queries message.

Here is another site that shows this message to me:

https://sndeep.info/en

Simply enter a random number and click "Show info".

Or is it possible that a site can disable the audio challenge? I just noticed that I get the same message when I want to solve the audio challenge by myself.

**Comment by dessant** [comment]
Yes, sites can adjust the security preference, which in turn may cause the audio challenge to be blocked if you're connecting from a network neighbourhood that Google considers suspicious.

**Comment by angelfire76** [comment]
> 
> 
> Yes, sites can adjust the security preference, which in turn may cause the audio challenge to be blocked if you're connecting from a network neighbourhood that Google considers suspicious.

Is there any solution to bypass it? After a month of error-free usage, since 2 weeks it's impossible to use Buster at any websites. I've tried it in different browsers, after a couple of uses google blocks them too.
