### ISSUE TITLE
No menu buttons on Firefox/Waterfox

### ISSUE THREAD

**Issue by LightShaft** [dessant/buster#370]
Hi,

I am trying to start using Waterfox as my main browser (coming from Vivaldi, Manifest v3 stuff)
Buster Captcha does not seem to have any menu button available so I don't have any way to set up my Google Cloud API
I've tried with Firefox, same thing.
I know there's the toolbar menu where I should be able to just grab the icon and put it anywhere I want, but there isn't. It's just not there, there's nothing. Obviously, I've made sure it's enabled, I've disabled and enabled it, doesn't do much.
So in case it's a bug only a dev could fix, I figured it would be better for me to report that, if it's coming from me then I would need a hand because right now ... I'm clueless. Thanks a lot

**Comment by dessant** [comment]
Firefox differs from Chrome in this regard, extensions which do not set up a toolbar button will have no icon there in Firefox. Go to about:addons and open the extension's options from the three-dot menu of the extension.

**Comment by dessant** [comment]
Btw, Waterfox has been bought by an ad company, you'll be much better off with Firefox.

**Comment by dessant** [comment]
@LightShaft, is this your review on AMO?

https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-solver/reviews/1804280/

**Comment by LightShaft** [comment]
Nope, I haven't done any
Thanks for your help I did managed to setup the thing properly
Also, Waterfox suits me as I've been using Startpage too for a long while, I'm ready to switch whenever System1 fucks up anything tho (too much setup to have a decent profile with Firefox in my opinion)

**Comment by LightShaft** [comment]
Just put 5 stars on the page to help, thanks again for your work and your help
