### ISSUE TITLE
Manifest v3

### ISSUE THREAD

**Issue by arjun44** [dessant/buster#371]
**Is your feature request related to a problem? Please describe.**
Manifest v2 will be phased out in 2023 for Chromium based browsers, and will be deprecated.

**Describe the solution you'd like**
The solution I would like would be an update to Manifest v3 if possible.

**Describe alternatives you've considered**
There really isn't any other alternative unless you want to drop support for Chromium based browsers, which IMHO isn't a good idea.

**Additional context**
N/A

**Comment by dessant** [comment]
The extension will continue to function past January 2023, manifest versions should not concern you as a user.
