### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by jakbin** [dessant/buster#381]
May dependencies recognize as vulnerable. Please update dependencies for safer use.

**Comment by dessant** [comment]
All packages that provide code which lands in the extension are usually kept updated, and there are no vulnerabilities in those dependencies at the moment. Developer dependencies may sometimes not be immediately updated when the reported vulnerability is not malicious and the update would break the build process, but that doesn't affect the safety of the extension.

```sh
npm i --omit=dev

up to date, audited 59 packages in 2s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
