### ISSUE TITLE
Have trouble installing client app for more than one browser.

### ISSUE THREAD

**Issue by jritt0** [dessant/buster#388]
**System**

* OS name: [e.g. Windows, Ubuntu] Windows 
* OS version: [e.g. 10] 10
* Browser name: [e.g. Chrome, Firefox] Chrome/ Firefox/ Edge
* Browser version: [e.g. 60] current

**Extension**

* Extension version: [e.g. 1.0.0] 2.0.1

* User input simulation: [e.g. yes, no] yes

* Client app version: [e.g. 1.0.0] 0.3.0
* Client app installed successfully: [e.g. yes, no] yes and no

**Bug description**
 I have a need to use the ext on multiple browsers.The issue I run in to is this- the first browser I install the client app for works great. I double click on the eve and 
then Windows will ask me what to open the file with and I just choose whichever browser I want, let's say Edge.. The client app will run and a window will open in said browser pointing to the options page for the extension. The web page for the extensions options will also change slightly, which is also indicative of the successful installation of the client app for that specific browser. 
So then if I hypothetically attempt to install the client app for Chrome for example...even if I  redownload the app using Chrome and also initiate the opening of the client exe through Chromes file explorer- aka the Download button, the app will continue to open up in Edge. Also, The page for the extensions options when opened in Chrome never changes the way it should after a successful install. Now, I have figured out to get Buster working on all four Browsers...but I cannot figure out how I did it. Sometimes I do but usually I am unable to remember what my solution was. I have searched for an extension which would allow a browser to run an executable, apparently there used be one for Chrome- but it doesn't seem to be available any longer. 
The fact that I cannot be the only one to use buster on multiple browsers yet I have never seen another complaint like mine, leads me to believe this may not be an issue at all. The issue maybe that I'm a moron. I am a big fan of your extension and would really welcome some help with this. Please, and thank you.

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```
[buster-client-log.txt](https://github.com/dessant/buster/files/11072642/buster-client-log.txt)

**Comment by dessant** [comment]
At the end of a successful installation the installer which serves the page is shut down, so you have to launch the installer again for every new browser, then copy over the new URL which was opened in Edge to your target browser.

**Comment by jritt0** [comment]
Yes, copying the url from edge worked perfectly. Thanks for helping me with this, it was really beginning to frustrate me.
