### ISSUE TITLE
Why it is impossible to install the Buster Client from the account with administrative rights?

### ISSUE THREAD

**Issue by sn260591** [dessant/buster#39]
I got "Error: setup must be run without administrative rights" in the console.

**Comment by dessant** [comment]
The client app doesn't need administrative rights to function, and running it as root would cause bugs during updates that would require considerable development time to handle.

**Comment by sn260591** [comment]
Because of this, the client app will not work on Windows with disabled UAC.

**Comment by dessant** [comment]
I did not think about that, thanks for sharing!

**Comment by dessant** [comment]
@sn260591, I have set UAC to never notify from User Account Control Settings on Windows 10 1809, and the client app was successfully installed.

Share more details about your system, and the exact way you disabled UAC. It's best if you open a new issue and follow the issue template closely.

**Comment by sn260591** [comment]
Did you restart the computer to apply the changes? I use Windows 7 and disable UAC in the same way as you. If UAC is enabled, the client app installs without problems.

**Comment by dessant** [comment]
Yes, I have restarted after disabling UAC. The bug could be specific to Windows 7, but I don't have an installation ready to test. Turn on UAC just while you install the client, and disable automatic client app updates from the extension's options. It will ask you to install the new app whenever there is an update in the future.

What is your exact Windows 7 version and OS build?

https://www.howtogeek.com/236195/how-to-find-out-which-build-and-version-of-windows-10-you-have/

**Comment by sn260591** [comment]
My OS build is 7601.
As I understand it, win7 and win10 have different behavior with UAC turned off: win7 gives admin rights to all running applications. This can be checked by running the bat file:
```
@echo off
AT > NUL
if %errorlevel% equ 0 (echo you are Administrator) else (echo you are NOT Administrator)
pause
```

**Comment by dessant** [comment]
I'll keep this issue in mind, though I'm not sure it will be fixed in the near future, unless someone submits a pull request, and Windows 7 will stop being supported by Microsoft in January 2020. I'd advise you to either do the suggested workarund to update Buster in the future, or turn on UAC for good, because it's an important security feature that does not intrude too much.

**Comment by jingyu9575** [comment]
FYI the UAC slider does different things in Win7 and Win10. In Win10, the bottom option means "Never notify", but in Win7 it means "Off". 

It is possible to turn off UAC in Win10 truly (like in Win7): run `secpol.msc`, navigate to Local Policies -> Security Options, set "User Account Control: Run all administrators in Admin Approval Mode" to "Disabled" and restart.
