### ISSUE TITLE
Incorrect mouse movement with user input simulation feature enabled

### ISSUE THREAD

**Issue by s73b4n** [dessant/buster#40]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Chrome
* Browser version: Versión 72.0.3626.121 (Build oficial) (64 bits)

**Extension**

* Extension version: 0.5.0

* User input simulation: yes

* Client app version: 0.2.0
* Client app installed successfully: yes

**Bug description**

The input user simulation feature is not working properly on my computer running with a w10 desktop scaled to 125%. I figured it out thanks to another clossed issue it was something related with the scaling, so I got my desktop to normal 100% displayed and then the feature did it right. I didnt notice any error in browser console, only strange mouse movements within the taskbar.

**Logs**

Browser:
```
No errors displayed
```

Client app:
```
No errors displayed
```

**Comment by dessant** [comment]
@s73b4n, I'll release a fix today, but it will take a couple of days until it is approved on the Chrome Web Store. As a workaround, if you navigate to the extension button with the keyboard and press enter, the client app will continue using keyboard navigation.

**Comment by s73b4n** [comment]
thank you very much @dessant, I just tried the fix released and now it's working properly. Have a good day.

**Comment by vlldk** [comment]
Hi,
I have the same problem - I've set my scaling to 200% in Windows and it doesn't click properly. When the scaling is set to 100% or 125% it clicks correctly. 
I'm on Firefox btw.
