### ISSUE TITLE
Unable to use buster after a while getting api quoted completed error

### ISSUE THREAD

**Issue by karthikkulkarni20** [dessant/buster#403]
"Getting API quoted completed "popup when I am extensively using buster extension to solve captcha.
I am ready to pay for the tool let me know how to use paid version as my limit is more

**Comment by whol-hoopa** [comment]
there is a wiki for configuring Google cloud, IBM watson, Microsoft Azure and Wit.ai. You can get one of their paid subscriptions and configure your buster.
https://github.com/dessant/buster/wiki/Configuring-IBM-Watson-Speech-to-Text

**Comment by dessant** [comment]
All of the supported speech recognition services have a free tier, and as @whol-hoopa said, the wiki has guides for all of them.

https://github.com/dessant/buster/wiki#guides
