### ISSUE TITLE
Setting load challenge in English will lead to the API loading failed.

### ISSUE THREAD

**Issue by Mishasama** [dessant/buster#407]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Chrome
* Browser version: 125

**Extension**

* Extension version: 3.1.0

* User input simulation: no

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

## English ON
![image](https://github.com/dessant/buster/assets/54498172/cbaf0e21-a808-4011-ac21-06de76575569)
![image](https://github.com/dessant/buster/assets/54498172/15ea8d48-a74f-415c-9c7e-1525b9895f2e)
![image](https://github.com/dessant/buster/assets/54498172/5f0170e2-fa07-490c-9e6f-6c6743d5e592)
## English OFF
![image](https://github.com/dessant/buster/assets/54498172/95f93f47-0d52-46f2-a4cd-9aa4558f52aa)
![image](https://github.com/dessant/buster/assets/54498172/14d1850a-86b4-4294-92fc-d27647336091)

It looks the proxy used to fetch English challenge was failed.
**Logs**

![image](https://github.com/dessant/buster/assets/54498172/9a2194f8-6483-4903-8ea2-0c259f22a38d)
Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
I'm guessing you have also installed the same extension as this user: https://github.com/dessant/buster/issues/406#issuecomment-2151948606

There is nothing to fix regarding this issue in Buster. The extension you have installed is using a language code that is not documented by Google and redirects reCAPTCHA v2 widget requests, so the two extensions keep redirecting the same request until the browser shows an error. The correct locale code for US English is "en" according to the docs, but that extension attempts to set the "en-US" locale and redirects the request. They should use only documented laguage codes to set the reCAPTCHA widget locale.

> Language Codes
> English (US) * 	en


https://developers.google.com/recaptcha/docs/display#config

https://developers.google.com/recaptcha/docs/language
