### ISSUE TITLE
Solve captchas without any manual clicks

### ISSUE THREAD

**Issue by marcorroma** [dessant/buster#409]
Hi, I use Buster with Wit.ai with API (It's awesome!). I would like to know if it is possible to somehow avoid clicking on the Buster icon to solve the captcha. So it would be functional if Buster automatically tried to solve the captcha, at least on the first try or even on the first and second tries. To automate captcha solving.
I tried via script via Chrome console but it seems not possible.
Do you have any ideas for this problem?
Thanks for your work!

**Comment by eldepor** [comment]
> @marcorroma, full automation and scripting are not within the scope of this project due to the potential for misuse. The solver must always be manually started from the extension button.

wtf just do it
