### ISSUE TITLE
button recognition error

### ISSUE THREAD

**Issue by mojo2208** [dessant/buster#41]
**System**

* OS name: Windows
* OS version: 7
* Browser name: Chrome, Firefox
* Browser version: 72.0.3626.121

**Extension**

* Extension version: 0.5.0

* User input simulation: no

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: no

**Bug description**

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by mojo2208** [comment]
My imacros does not recognize the "solve captcha" button. The button is pressed but nothing happens. What could be the problem? Help me please(

**Comment by dessant** [comment]
@mojo2208, that is the intended behavior. The extension button will accept only native user input events, preferably initiated by a person, not a script.

**Comment by mojo2208** [comment]
previously everything was fine. Has this innovation come with the latest update?

**Comment by dessant** [comment]
@mojo2208, yes.
