### ISSUE TITLE
"This extension requires Chromium version 123.0 or greater."

### ISSUE THREAD

**Issue by LoganDark** [dessant/buster#411]
**System**

* OS name: Windows
* OS version: 11 23H2 Build 25931.1000
* Browser name: Ungoogled Chromium
* Browser version: 118.0.5993.88

**Extension**

* Extension version: 3.1.0
* User input simulation: N/A
* Client app version: 0.3.0
* Client app installed successfully: yes

**Bug description**

The Chrome Web Store says the extension is "not compatible" with my chrome version (with no further information). When attempting to load the extension from unpacked, I get an error that says "This extension requires Chromium version 123.0 or greater."

Chrome 123 was released less than 5 months ago.

**Logs**

N/A

**Comment by LoganDark** [comment]
Simply changing the minimum version specified in the manifest to 118 seems to allow the extension to be installed and function correctly so I'm not sure why the requirement is so recent by default.

**Comment by dessant** [comment]
The extension *does* use some recently introduced browser APIs, and there are other bugs impacting the extension in Chrome that made it necessary to update the oldest supported browser version when we migrated to Manifest V3, and those bugs may not be immediately apparent to you during a simple test.

**Comment by LoganDark** [comment]
Eh whatever, I've since updated my browser anyway.
