### ISSUE TITLE
Buster icon not showing on some captchas recently 

### ISSUE THREAD

**Issue by eldepor** [dessant/buster#427]
The buster icon to click and solve the captcha is not showing in some captchas, I noticed it today, before it was working perfectly. I'm using Firefox. Thanks. 

![imagen](https://github.com/user-attachments/assets/f03ee808-5f9b-41c7-a13f-4ba328336948)
![imagen](https://github.com/user-attachments/assets/c37a51f1-ac8e-46b3-bcbe-5d12cbbd2786)

**Comment by Raul1738** [comment]
Please fix

**Comment by eldepor** [comment]
can you please FIX the extension? its working only 5% of the captchas

**Comment by eldepor** [comment]
ok the issue was the site was http instead of https, with https the extension works
