### ISSUE TITLE
Why removed the ability to work with the imacro?

### ISSUE THREAD

**Issue by mojo2208** [dessant/buster#44]
**System**

* OS name: [e.g. Windows, Ubuntu]
* OS version: [e.g. 10]
* Browser name: [e.g. Chrome, Firefox]
* Browser version: [e.g. 60]

**Extension**

* Extension version: [e.g. 1.0.0]

* User input simulation: [e.g. yes, no]

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by mojo2208** [comment]
Return this function please.

**Comment by dessant** [comment]
@mojo2208, what are you using the imacro for exactly?

**Comment by mojo2208** [comment]
There is a lot of routine work that one wants to do automated. And thanks to you, this opportunity could live. People in any case use your creation for good.

**Comment by mojo2208** [comment]
if you really are in the process of developing the functionality and possibilities of your expansion, believe me - this is a huge plus for all users.

**Comment by dessant** [comment]
Unfortunately this extension is not meant to be integrated into automated workflows, its only goal is to help people get past challenges and have an easier time getting access to web services.

Encouraging integration into scripts would hurt this goal, that is why future versions may begin to detect environments that are tipically used for automation, such as headless browsers, and refuse to work in them.

**Comment by mojo2208** [comment]
your intentions are correct, but where are the scripts? If your extension helps people, then let it help everyone.

**Comment by dessant** [comment]
@mojo2208, we have to suffer these challenges because of scripts to begin with, I'm sure you understand how little sense would it make to support them.

I will allow integration with known accessibility tools, if somebody comes forward with an issue caused by recent updates, but otherwise do not expect this project to support scripting.

**Comment by mojo2208** [comment]
It would be very cool if it were possible to use the script. The last word is yours! thanks!

**Comment by jackdancoke** [comment]
Is there a way to integrate your captcha solver with imacros?
