### ISSUE TITLE
Doesn't seem to work anymore.

### ISSUE THREAD

**Issue by CForChrisProooo** [dessant/buster#47]
![Capture](https://user-images.githubusercontent.com/39370376/54663272-6e23e080-4b2c-11e9-9c3f-03913abf9da4.PNG)
![Untitled](https://user-images.githubusercontent.com/39370376/54663197-27ce8180-4b2c-11e9-81b2-6365e911e1d4.png)
Gives me an error message every time.

**Comment by dessant** [comment]
The default speech service does not work at the moment, switch to the "Wit Speech API (demo)" service from the extension's options.

**Comment by rainbowjose** [comment]
IBM services not working too.

**Comment by dessant** [comment]
The default speech service has resumed working shortly after this issue was opened.

@rainbowjose, if you have issues with other speech services, open a different bug report and fill out the issue template.
