### ISSUE TITLE
Addon on Mobile Firefox

### ISSUE THREAD

**Issue by XDavidXtreme** [dessant/buster#48]
Well, I managed to download the addon for Firefox on mobile, but it seems that it is not fully compatible. Do you know if there is a way to make Buster compatible with mobile at the moment? Or if you could do a version of this addon for mobile?

**Comment by dessant** [comment]
By fully compatible you mean supporting the client app? The extension sould work with the default settings on Android, but user input simulation is not supported because Firefox for Android has no support for native messaging.

**Comment by XDavidXtreme** [comment]
It will say "Something went wrong. Open the browser console" but when I open it the only thing it says is "TypeError: d is undefined", I am not joking, the whole addon doesn't work because of that. Do you know any solution?

**Comment by dessant** [comment]
You'll have to open a bug report and fill out the issue template with all the requested data.
