### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Noruas29** [dessant/buster#49]
I'm on Linux (Solus) and I don't know how to install buster-client on it.... is it a pkg ? a sh ? a script ? etc... No doc to know it.

**Comment by dessant** [comment]
It's just an executable that you have to run to start the installer. Visit the extension's options and enable user input simulation, a download button will appear for the client app. This step is mentioned in the description of the extension listing.

**Comment by Noruas29** [comment]
All options are already activated... I already downloaded it... but after ???????

**Comment by dessant** [comment]
Run the installer you have downloaded.

**Comment by Noruas29** [comment]
How ???? no extension... what format is it ?

**Comment by dessant** [comment]
It is an executable, follow this thread if you'd like to learn how to run executables on Linux: https://askubuntu.com/questions/484718/how-to-make-a-file-executable

**Comment by Noruas29** [comment]
OK, it's an .sh

**Comment by Noruas29** [comment]
Is it possible to have an option to autocheck the yellow icon to automatically lauch Buster when we arrive on reCAPTCHA windows ?
