### ISSUE TITLE
In Firefox beta 65.0b3 (64 bit),  it is "inoperative" because the favicon is lost (it does not exist anywhere).

### ISSUE THREAD

**Issue by Shitennouji** [dessant/buster#5]
In Firefox beta 65.0b3 (64 bit), "Buster: Captcha Solver for Humans 0.2.0" is displayed in Addons Manager, but it is "inoperative" because the favicon is lost (it does not exist anywhere).

Incidentally,
In Brave 0.58.11 Chromium: 71.0.3578.80（Official Build beta 64 bit） and Iridium Browser  2018.4（Official Build 64 bit）, it was displayed normally, and we were able to confirm the function.
Post script,
Vivaldi 2.1.1337.51 (Stable channel 64-bit) is also "inoperative" like Firefox beta.

**Comment by Shitennouji** [comment]
1, the result of Ctrl + Shift + J, 
Error while detaching the browsing context target front: Connection closed, pending request to server1.conn1.parentProcessTarget1, type detach failed.
Besides, I tried Tor Browser, Waterfox, but it is the same result.
Tor Browser 8.0.4 (based on Mozilla Firefox 60.4.0esr) (64-bit)
Waterfox 56.2.5 (64 bit)
To their Browser, it has been made "FingerPrinting measures" that Tor Project is recommended. The cause of the error seems to be derived from it.
FingerPrinting measures,
https://www.torproject.org/projects/torbrowser/design/#fingerprinting-linkability

2, Sample Form with ReCAPTCHA （ https://www.google.com/recaptcha/api2/demo ） has been tested, the following error message will be displayed.
Try again later
Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page

**Comment by dessant** [comment]
Ok, so when you said you didn't see the extension button, did you see the visual challange, or did it show "Your computer or network may be sending automated queries." the whole time? If is shows the visual challenge, please post a screenshot.

**Comment by Shitennouji** [comment]
For console logs, it was sent by E-MAIL.

**Comment by dessant** [comment]
Please post the new logs here on GitHub when you reproduce the original issue again. The screenshot and the logs must be from the same test.

**Comment by dessant** [comment]
I have tested the extension with Firefox 65.0b4 and Vivaldi 2.2.1388.34 on Windows, the button was in the footer of the captcha widget, as expected. Maybe you're using an extension or security software that blocks the extension from running in the tab. Let me know if you find a way to reproduce the issue.
