### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by perdolka** [dessant/buster#53]
**System**

* OS name: Windows 10 x64
* OS version:  1809
* Browser name: Firefox
* Browser version: 60.6.1esr (x64)

**Extension**
Buster: Captcha Solver for Humans

* Extension version: 0.5.2

* User input simulation: no

* Client app version: _

* Client app installed successfully: Client app not installed

What versions of the engine did I use?

WIT demo and WIT + API

**Bug description**
0.5.2 doesn't works on some sites (captcha doesn't show up).
For example, on 2ch.hk

**Logs**
Browser:
any errors in the log

**Comment by SebTota** [comment]
Where do you see a captcha on this website? I just checked the website and there is no captcha, at-least not on the main page. There is no hidden captcha either. Can you specify what page your having issues with?

**Comment by perdolka** [comment]
captcha appears when you send a post.

**Comment by SebTota** [comment]
It works for me when connecting from a US IP address. 
https://ibb.co/Jzv1yDt

Try going into the settings of the extension and changing the "Load challenge in english" slider.

**Comment by dessant** [comment]
@perdolka, I'm sorry but I still can't reproduce the bug based on the details you have shared, just like with your previous issue. You could ask a friend to reproduce the error for you based only on the data you share with them, It may help you to figure out what details are missing from the bug report.

Please only open a new issue if you are certain that we can reproduce the error just by following the steps you share.

**Comment by perdolka** [comment]
@dessant @SebTota

My bad, i forgot to say it first. 
To access 2ch.hk i need to use a VPN addon
In my case it's Browsec VPN 3.22.3

When I switch off the option "Load challenge in English" a captcha appeared, finally.
But it still doesn't work.

**Wit Speech API (demo)** error message: 

> Something went wrong. Open the browser
> console for more details.

Browser console error:
```
Error: API response: 400, {
  "error" : "Speech recognition is not enabled for language: Ukrainian",
  "code" : "bad-request"
}
```

**Wit Speech API** error message: 

> API key missing. Visit the options page to
> configure the service.

I tried it with Server Access Token and Client Access Token for Russian Language and Timezone and got a same error.
WIT settings:
https://user-images.githubusercontent.com/24720263/55726274-0e787100-5a18-11e9-8e1a-9fa85cf4dd70.png
Also I tried English settings. Same errors.

Browser console error:
any errors

So, as you see here: _Speech recognition is not enabled for language: Ukrainian_ my browser and system language is Ukrainian but I'm using VPN for 2ch.hk.

What I did next:
I changed the WIT acc language settings and Default Timezone to Ukrainian and re-generated a new keys.
It helped to fix a 'wrong key' error message, finally.
Now **Wit Speech API** got the same errors as **Wit Speech API (demo)** : 
> Something went wrong. Open the browser
> console for more details.
and 
```
Error: API response: 400, {
  "error" : "Speech recognition is not enabled for language: Ukrainian",
  "code" : "bad-request"
}
```
:/

**Comment by dessant** [comment]
@perdolka, then it appears Wit does not properly support Ukrainian. Your best bet is to load challenges in english and try to make that work with Wit. Find out what happens exactly and what error is shown in the console when loading challenges in english is enabled.

**Comment by SebTota** [comment]
Might be a dumb thing to mention, but make sure you have English as one if your saved languages in chrome. I had an issue with that when I was trying g to load the challenge in a different tlanguge.

**Comment by perdolka** [comment]
@dessant 
> Find out what happens exactly and what error is shown in the console when loading challenges in English is enabled.

```
LoginRecipes:getRecipes: falling back to a synchronous message for: "https://2ch.hk"  
LoginRecipes.jsm:243
close  sharkey.js:4571:7
```

`Fatal async error:  <unavailable>  event-utils.js:174:11`

```
Timeout  recaptcha__uk.js:602:384
uG.prototype.V9/< https://www.gstatic.com/recaptcha/api2/v1554100419869/recaptcha__uk.js:602:384
```

**Comment by perdolka** [comment]
So, any ideas?
