### ISSUE TITLE
automated queries

### ISSUE THREAD

**Issue by burakataoglu** [dessant/buster#56]
I know u not guarantee anything.

I tried that plugin x3 times and getting (whole day) :
Your computer or network may be sending automated queries.

also I tried own speech API key.
no change.

any idea for that?

**Comment by dessant** [comment]
Switching between speech recognition services will not make a difference for this issue.

Make sure to enable user input simulation from the extension's options and install the client app to reduce the chance of a temprorary block in the future. Though keep in mind that if you cannot access the audio challenge yourself by clicking on the headphone icon, there's not much the extension can do.

To get out of the current block you could try clearing your browsing data and changing your IP address. The block could also go away after a couple of days if you solve visual challenges as you encounter them while browsing the web.

**Comment by simonred343434** [comment]
Will this problem disappear when installing 1 virtual server or not?

**Comment by dessant** [comment]
@simonred343434 this browser extension is not meant to be used on virtual servers.
