### ISSUE TITLE
"This page is not redirecting properly"

### ISSUE THREAD

**Issue by AMihail1** [dessant/buster#57]
**System**

* OS name: Windows
* OS version: 10
* Browser name: FireFox
* Browser version: 66.03

**Extension**

* Extension version: Latest
* User input simulation: No
* Client app version: Latest
* Client app installed successfully: Yes

**Bug description**
Google reCAPTCHA frame showing "This page is not redirecting properly", I can bypass this bug with Smart Referer and Skip Redirect off (potentially uBlock Origin interefering also) - what settings in these extensions would cause this to happen?

Even with those all off, reCAPTCHA still showing "automated traffic, try again" dialogue with Buster installed **with ghacks user.js** 

Similar discussions going on over at the ghacks user.js github, would be nice to get to the bottom of this, reCAPTCHA almost unusable atm.

**Comment by dessant** [comment]
Do you see the same error if you disable Buster?

**Comment by AMihail1** [comment]
No - Buster has to be enabled, however, I have narrowed it down to an extension called Clear URLS, it works fine with it disabled and the aforementioned enabled.

ghacks user.js is still interfering with audio CAPTCHAs however - dom.webaudio.enabled;false isn't fixing it.

**Comment by dessant** [comment]
It sounds like there is not much I can do regarding this issue, and the bug is likely caused by a third-party extension or profile change.

**Comment by AMihail1** [comment]
Nice one.
