### ISSUE TITLE
error: "Try again later" when hitting checkbox

### ISSUE THREAD

**Issue by facetoface10101980** [dessant/buster#59]
I guess you are aware about this already?

**System**

* OS name: Window
* OS version: 10
* Browser name: Firefox
* Browser version: 60.0

**Extension**

* Extension version: 0.5.2
* User input simulation: yes

* Client app version:  not displayed
* Client app installed successfully: yes

**Bug description**
error message when hitting checkbox:
Try again later
Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page

What can i do?  How can i bypass that? Is it possible?
**Logs**

<!--
If there was an error, open the browser console (Ctrl+Shift+J)
and share its recent output.

**Comment by dessant** [comment]
This comment may help, but keep in mind that there is not much I can do, this is how reCAPTCHA works: https://github.com/dessant/buster/issues/56#issuecomment-481655521
