### ISSUE TITLE
Cannot contact reCAPTCHA. Check your connection and try again

### ISSUE THREAD

**Issue by Meltd** [dessant/buster#60]
Cannot contact reCAPTCHA. Check your connection and try again.
Every time on firefox. But it seems captcha solves.
On opera everything works fine. 
I tried to disable every other addon too.
Any suggestions?

**Comment by dessant** [comment]
Enabling user input simulation from the extension's options and installing the client app may help. Though I don't have a way to reproduce the issue you're seeing.

**Comment by srlmitch** [comment]
I'm also having this issue as of last week (using firefox) whilst trying to post on 4channel.

It was working completely fine last month.
