### ISSUE TITLE
Error check console ...

### ISSUE THREAD

**Issue by AMihail1** [dessant/buster#61]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 66.03

* Extension version: Latest
* User input simulation: No

**Bug description**
After much tweaking and comparing settings with the guys over at the ghacks user.js git I've been able to get Buster to produce an error I've never seen before - in the the console it says "ReferenceError: AudioContext is not defined" - perhaps with a little more help we are closer to getting this addon to work with custom user.js?

**Logs**

[Nano] Nano Defender Activated :: patrickhlauke.github.io core.js:43:5
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
[Nano] Nano Defender Activated :: www.google.com core.js:43:5
[Nano] Excluded :: All Generically Applied Solutions
ReferenceError: AudioContext is not defined

**Comment by dessant** [comment]
I think you'd get the same error without installing this extension. Make sure that you can manually play and solve the audio challenge, then it will surely work with the extension too.

**Comment by AMihail1** [comment]
The audio plays with or without Buster installed - you're awfully quick to close these with 0.1% effort on your part.

**Comment by dessant** [comment]
You could make sure that the Web Audio API is enabled, though keep in mind that I have no easy way to debug your setup, nor time to fix issues caused by config changes that broke your browser profile. Firefox warns you about the possibility of breaking things when you visit about:config.
