### ISSUE TITLE
still not working

### ISSUE THREAD

**Issue by throwaway666** [dessant/buster#62]
freshly installed Captcha Buster using the new version from Firefox store. i click on the Buster button in the captcha window, and it opens a new tab compelling me to pick an API. no matter what i pick, i get compelled to download an app. when i try to install the buster client app file i get a new page saying 

"Something went wrong
The installation has failed. Check the browser console for more details, and open an issue on GitHub if this error persists."

this issue has been persisting for months and the app still isn't working.

**Comment by AMihail1** [comment]
Tbh the addon isn't working - developer can't shed any light whatsoever on `"Your computer or network may be sending automated queries."` bug.

**Comment by dessant** [comment]
@AMihail1, actually I did, several times, search is your friend. You are being banned indefinitely because of your abusive behavior.

**Comment by dessant** [comment]
@throwaway666, I'm sure you understand that there is no way for me to know what is the issue on your device without more information. I can't help you if you're not willing to put in the time to fill out the issue template *properly* with the requested data.

**Comment by dessant** [comment]
@throwaway666, I don't remember writing any code that compels people to do anything, nor code that opens a new tab with the extension's options, if you use the default settings. You will want to be extremely specific while you describe in your new issue how and in what environment you have installed the extension, and the steps you took to install the client app.
