### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by jmartin121** [dessant/buster#63]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 66.03

**Extension**
Buster

* Extension version: Latest

* User input simulation: No

**Bug description**
On a fresh Firefox profile, no other addons installed I am able to get Buster to work on https://www.google.com/recaptcha/api2/demo, listen to the CAPTCHA and type it out but when submitting it's spitting out the error `Cannot contact reCAPTCHA. Check your connection and try again.` which, afaik, means the CAPTCHA has not fully completed and resets me back to the beginning. Any ideas on whats going wrong here?

**Comment by dessant** [comment]
Try enabling user input simulation and install client app. Do you still get an error?

**Comment by dessant** [comment]
Let me know if the error persists.

**Comment by jmartin121** [comment]
User simulation did indeed fix it, but reCAPTCHA seems to think (as far as I can tell after testing *many* loops) that you are bot traffic if you click the audio symbol too quickly after opening the CAPTCHA ... is it possible for you to code in a delay to the automation?
