### ISSUE TITLE
User simulation for Android

### ISSUE THREAD

**Issue by hjyoung1** [dessant/buster#64]
I'm using kiwi browser it's chromium based browser for Android with chrome extension support. So far buster is working but many time i get " your computer or network maybe sending automated queries..." error i saw old issues it seems user input simulation app solves this. It would be great if you port that app for android too.

**Comment by dessant** [comment]
This is not yet possible because native messaging is not supported on Android.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/connectNative

**Comment by huitc** [comment]
if ok, pls support firefox (android ver.) too!!! (^W^))))
