### ISSUE TITLE
Can't download Buster Client App on MacOS

### ISSUE THREAD

**Issue by aktran777** [dessant/buster#66]
When I download the Buster client file buster-client-setup-v0.2.0-macos-amd64 on MacOS, I can't open the file at all. However, when I tried it on Windows, it works perfectly.

How would I go about opening the client file?

**Comment by dessant** [comment]
Open the terminal and make the downloaded binary executable:

```
# make file executable
chmod +x buster-client-setup-v0.2.0-macos-amd64
# run installer
./buster-client-setup-v0.2.0-macos-amd64
```

Once the file is executable, you should be able to launch it from the terminal, or by double clicking.

**Comment by aktran777** [comment]
Thanks a lot bro!

**Comment by holdit** [comment]
@dessant Shouldn't this info be on the extension, on the wiki or at least on buster-client repo?
