### ISSUE TITLE
Not working (well) with Waterfox

### ISSUE THREAD

**Issue by DocRockwell** [dessant/buster#67]
Windows 10
Waterfox 56.2.9 (64-bit)

**Extension**

* Extension version: 0.5.2
* User input simulation: no

**Bug description**
Buster fails the Captcha the majority of the time (probably 9/10 it fails) and yields the "Try again later....automatic queries..." message. Works flawlessly for me on Chrome.
Using Wit Speech Demo, tried changing the various english settings. Double checked that privacy.resistFingerprinting is disabled.

**Logs**
No error messages in the log.

**Comment by dessant** [comment]
You could try enabling user input simulation and intalling the client app. There is not too much this project can do regarding the automated queries error, Google is blocking people regardless of using the extension.

https://www.google.com/search?gws_rd=cr&gl=US&q=%22automated+queries%22+captcha
