### ISSUE TITLE
Browser (Brave) block 

### ISSUE THREAD

**Issue by DrTortue** [dessant/buster#70]
**System**
* OS name: Windows
* OS version: 10
* Browser name: Brave Chrominum
* Browser version: 0.63.48 
* Chromium version: 74.0.3729.108

**Extension**

* Extension version: 0.5.2
* User input simulation: Yes
* Speech service: Wit Speech API (Demo)
* Client app version: 0.5.2
* Client app installed successfully: Yes

**Bug description**
When I want to use your extension I have an error message in notification. I think my browser is blocking.

"Something went wrong. Open the browser console for more details.

**Logs**
Browser:
Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at script.js:1
    at e.exports (script.js:1)
    at script.js:1
    at async E (script.js:1)
    at www.google.com/recaptcha/api2/async chrome-extension:/mpbjkejclgfgadiemmefgebjfooflfhl/src/solve/script.js:1

**Comment by dessant** [comment]
Brave's shield blocks access for certain APIs, the only workaround is to disable it, see this thread for details: https://github.com/dessant/buster/issues/13

You should open an issue for Brave, they could apply fingerprinting protection only for websites, extensions are inherently trusted and should not be subject to the same limitations as websites.
