### ISSUE TITLE
[Buster-Client] Add support for Comodo IceDragon

### ISSUE THREAD

**Issue by paronos** [dessant/buster#75]
I'm able to get [buster-client](https://github.com/dessant/buster-client) working on [CD V73.0.3683.75](https://www.comodo.com/home/browsers-toolbars/browser.php)

However, the buster-client setup failed to install on [CID V64.0.4.15](https://www.comodo.com/home/browsers-toolbars/icedragon-browser.php)

OS: Win 7 64bit

![CID buster-client](https://user-images.githubusercontent.com/23290139/57868047-d04f4800-7834-11e9-8fd7-978da58ec26a.png)
[BrowserConsole log.txt](https://github.com/dessant/buster/files/3187888/BrowserConsole.log.txt)

**Comment by dessant** [comment]
There is a workaround for Comodo IceDragon, set the registry key manually before running the client app installer.

Open cmd and run this command, repalce `<user>` with your Windows username:
```
reg add "HKEY_CURRENT_USER\Software\ComodoGroup\NativeMessagingHosts\org.buster.client" /ve /d "C:\Users\<user>\AppData\Local\buster\manifest\firefox\org.buster.client.json" /f
```

**Comment by paronos** [comment]
Thanks for the fix! :+1:

**Comment by My1** [comment]
@dessant couldnt one instead of `C:\Users\<user>\AppData\Local` just use `%localappdata%`?

**Comment by dessant** [comment]
The issue will be fixed in the next version of the client app.

**Comment by dessant** [comment]
Fixed in https://github.com/dessant/buster-client/commit/5b8ace7c51bc227048e30c0de85a9ef7a64bc44e.
