### ISSUE TITLE
"Try again later"

### ISSUE THREAD

**Issue by renewablezip01** [dessant/buster#76]
I started getting this everytime i try to complete a captcha with Buster. http://prntscr.com/ns3hur
Is there any way to fix it or does the extension have to be updated since it is detected now?

Please help, thank you :)

**Comment by dessant** [comment]
Try enabling user input simulation and install the client app, you'll find details in the description of the extension listing. See also this comment: https://github.com/dessant/buster/issues/67#issuecomment-488612839
