### ISSUE TITLE
how to use microsoft azure speech to text api key option

### ISSUE THREAD

**Issue by saifkhan34** [dessant/buster#79]
Hi, Im Using This Wonderful extension chrome. now i want to use microsoft azure speech to text api key... please help how can i do this? i have also put microsoft azure speech to text key but it dont works maybe i dont know how to use... please some body help me....

**Comment by dessant** [comment]
Do you get any error? Open the browser console and share any recent errors that appear after trying to solve the challenge.

The default extension API should work fine and it does not require an API key, why do you need to use the Azure API?

**Comment by saifkhan34** [comment]
> Do you get any error? Open the browser console and share any recent errors that appear after trying to solve the challenge.
> 
> The default extension API should work fine and it does not require an API key, why do you need to use the Azure API?

Hello Thanks For Reply...
I Recieved This errors that appear after trying to solve the challenge.
using microsoft azure speech to text api key...
see screenshot
![mysss1](https://user-images.githubusercontent.com/51011502/58368499-58a1ad00-7f07-11e9-84bf-6634b4050e32.png)

and i know the default extension API works fine, but i also want to test or use other option, also ibm speach to text api option not working...
please check them and fixed error....

**Comment by dessant** [comment]
This is a breaking change in Chrome, the issue is tracked in https://github.com/dessant/buster/issues/81.
