### ISSUE TITLE
India GST website capcha

### ISSUE THREAD

**Issue by test2a** [dessant/buster#8]
Hello.
I just read about the addon on reddit and i am absolutely stoked by it. I tried it a couple of times and it just worked. 
Now, i am sure the addon works on recapcha only but can you try adding compatibility to https://gst.gov.in, 
the login page being https://services.gst.gov.in/services/login

This is an easier capcha because it only allows numbers and has audio support as well.

**Comment by dessant** [comment]
https://gst.gov.in does not load here. In any case, other captcha systems are outside of scope for now, but I'll consider adding it if that changes.
