### ISSUE TITLE
When I saw that it could read your history, I was a bit alarmed.

### ISSUE THREAD

**Issue by wolfy01** [dessant/buster#82]
I just wanted to know if this is actually true or google is making a mistake and saying it can read your history?

**Comment by dessant** [comment]
The permission is required by an extension API that lists iframes in the tab. The extension does not look at your history, though if you are concerned, it's best to verify changes yourself after releases.

https://developer.chrome.com/extensions/webNavigation#method-getAllFrames

**Comment by wolfy01** [comment]
Thanks, just wanted to make sure.
