### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by SwiftWinds** [dessant/buster#83]
When I click the buster icon, the circle animation appears for some time, and it stops. My mouse never moves, and eventually, the animation stops, and nothing happens.

However, if I click the audio button manually and focus on the text field, it types it in correctly.

Here are some images of the console: 

![image](https://user-images.githubusercontent.com/12981958/58682884-17eecd00-8327-11e9-8279-6d2c71b58422.png)

![image](https://user-images.githubusercontent.com/12981958/58682861-09a0b100-8327-11e9-8609-11e3f794f617.png)

Thank you for your help! Your extension is such a life saver and saved me so much hair pulling.

**Comment by SwiftWinds** [comment]
BTW, the link I was on was https://cpmlink.net/jVwFAQ#, but this bug seemed to affect all links.

**Comment by dessant** [comment]
@SwiftWinds, I can't reproduce the bug. Could you fill out the issue template in a new issue with all the details? I'm not even sure if you're using Chrome or a fork. The logs will also be important for the client app, you should have been also getting an error when the mouse doesn't move.

**Comment by dessant** [comment]
Please also check if `document.querySelector('audio#audio-source')` returns anything in the console tab, make sure to select the correct frame (bframe) before issuing the command.

![Screenshot from 2019-05-31 11-46-16](https://user-images.githubusercontent.com/7513068/58693717-0a265f80-839a-11e9-9e06-79355ee2b8e8.png)

**Comment by SwiftWinds** [comment]
OK. Thank you for the quick reply. I will do this as soon as I get home. For some reason, the new issue template did not appear when I made this issue.

**Comment by SwiftWinds** [comment]
Closed in favor of #85
