### ISSUE TITLE
Can't install client app in Waterfox

### ISSUE THREAD

**Issue by glyphsays** [dessant/buster#84]
**System**

* OS name: Windows
* OS version: 10, 1903
* Browser name: Waterfox 
* Browser version: 68.0a1

**Extension**

* Extension version: 0.5.3

* User input simulation: yes

* Client app version: 0.2.0
* Client app installed successfully: no

**Bug description**

**Logs**

Browser:
```
No such native application org.buster.client 2 NativeMessaging.jsm:99
[Nano] Nano Defender Activated :: 127.0.0.1 core.js:43:24
[Nano] Excluded :: All Generically Applied Solutions rules-common.js:231:28
[Exception... "Favicon at "http://127.0.0.1:51162/favicon.ico" failed to load."  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 192"  data: no] FaviconLoader.jsm:192:42
No such native application org.buster.client NativeMessaging.jsm:99
Error: Attempt to postMessage on disconnected port
```

Client app:
```
2019/05/31 04:45:58.440293 Starting client (version: 0.2.0)
2019/05/31 04:45:58.440293 Receiving message
2019/05/31 04:57:58.477972 Closing client (forced)

```

**Comment by dessant** [comment]
There is a workaround for Waterfox, set the registry key manually before running the client app installer.

Open cmd and run this command, replace `<user>` with your Windows username:
```
reg add "HKEY_CURRENT_USER\Software\Waterfox\NativeMessagingHosts\org.buster.client" /ve /d "C:\Users\<user>\AppData\Local\buster\manifest\firefox\org.buster.client.json" /f
```

**Comment by My1** [comment]
@dessant wouldnt %LOCALAPPDATA% also work instead of C:\Users\<user>\AppData\Local without the need to replace anything?

**Comment by drenex28** [comment]
hey sorry am i deaf yes ...i don't know about things how get fix it by first time here ...i hard think !!! not easy :(

**Comment by dessant** [comment]
@My1, I think you're right.

**Comment by dessant** [comment]
The issue will be fixed in the next version of the client app.

**Comment by dessant** [comment]
Fixed in https://github.com/dessant/buster-client/commit/5b8ace7c51bc227048e30c0de85a9ef7a64bc44e.
