### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by SwiftWinds** [dessant/buster#85]
**System**

* OS name: Windows x64
* OS version: 10 Build 1809
* Browser name: Chrome (Official)
* Browser version: 74.0.3729.169 (64-bit)

**Extension**

* Extension version: 0.5.3
* User input simulation: yes
* Client app version: 0.2.0
* Client app installed successfully: yes

**Bug description**

When I click the buster icon, the circle animation appears for some time, and it stops. My mouse never moves, and eventually, the animation stops, and nothing happens.

However, if I click the audio button manually and focus on the text field, it types it in correctly.

**Logs**

Browser:
```
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined
    at E (script.js:formatted:3799)
    at www.google.com/recaptcha/api2/async chrome-extension:/mpbjkejclgfgadiemmefgebjfooflfhl/src/solve/script.js:1
E @ script.js:formatted:3799
```

![image](https://user-images.githubusercontent.com/12981958/58754192-f7865600-847f-11e9-9ea1-8f153916d066.png)

![image](https://user-images.githubusercontent.com/12981958/58754196-243a6d80-8480-11e9-8d79-29c09eb3c1ab.png)
^^^ I ran Buster twice

> Please also check if document.querySelector('audio#audio-source') returns anything in the console tab, make sure to select the correct frame (bframe) before issuing the command.

` document.querySelector('audio#audio-source')` is null :/ (I have selected the bframe). 

> you should have been also getting an error when the mouse doesn't move.

I got a push notification the first time, saying something was wrong, but not the second.

Client app:
```
2019/06/01 22:10:15.106798 Starting client (version: 0.2.0)
2019/06/01 22:10:15.106798 Receiving message
2019/06/01 22:10:15.106798 Processing message
2019/06/01 22:10:15.106798 Command: ping
2019/06/01 22:10:15.106798 Sending response
2019/06/01 22:10:15.107795 Receiving message
2019/06/01 22:10:15.112782 Processing message
2019/06/01 22:10:15.112782 Command: moveMouse
2019/06/01 22:10:15.112782 X: 2390, Y: 929
2019/06/01 22:10:15.112782 Sending response
2019/06/01 22:10:15.112782 Receiving message
2019/06/01 22:10:15.223488 Processing message
2019/06/01 22:10:15.223488 Command: clickMouse
2019/06/01 22:10:15.248421 Sending response
2019/06/01 22:10:15.248421 Receiving message
2019/06/01 22:10:25.252309 Closing client
```

Thanks a lot for your help! 😊

**Comment by dessant** [comment]
Please also do this query in `bframe` after manually visiting the audio challenge: document.querySelector('audio')

Share a screenshot of the resulting element. I guess they are changing something in the widget layout and it is deployed to a subset of users only. Do you see the play button when you get this error?

**Comment by SwiftWinds** [comment]
![image](https://user-images.githubusercontent.com/12981958/58754408-2ef70180-8484-11e9-8777-d9b2dab75f6e.png)

Something interesting: this only happens when using the non-primary monitor. When on the primary monitor, Buster actually moves the cursor and everything works as expected. Perhaps it is related to #72?

**Comment by dessant** [comment]
Thanks for testing! You're right, this is #72.
