### ISSUE TITLE
Buster "Something went wrong, Open the browser console for more details."

### ISSUE THREAD

**Issue by picarica** [dessant/buster#87]
**System**

* OS name: Gentoo 
* OS version: 5.1.5 kernel
* Browser name: Waterfox
* Browser version: 56.2.10

**Extension**

* Extension version: 0.6.0

* User input simulation: Yes

**Bug description**

so everytime i use the buster my cursor goes to bottom right corner or somewhere else and then it throws the error in title, before this bug occured i did some edits in about:config and user.js 

this is the [guide](https://www.privacytools.io/browsers/#about_config) i used 

[and here is the user.js](https://send.firefox.com/download/c5b93d382bec77c3/#T1eBG-6kqntHdJxAvwvKoA)

**Logs**

Only this:
Browser:
```
1559668814300	addons.webextension.jid1-
Promise resolved after context unloaded
Extension error: TypeError: e is undefined moz-extension://ac45f1ba-8bc3-4ae9-b689-9ef3e9d7983a/h0-main.js 1
[[Exception stack
[537]/</<@moz-extension://ac45f1ba-8bc3-4ae9-b689-9ef3e9d7983a/h0-main.js:1:179755
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:63:129
runSafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:174:38
wrapPromise/</<@resource://gre/modules/ExtensionCommon.jsm:363:15
withLastError@resource://gre/modules/ExtensionCommon.jsm:301:14
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:357:11
]]
Extension error: TypeError: e is undefined moz-extension://ac45f1ba-8bc3-4ae9-b689-9ef3e9d7983a/h0-main.js 1
[[Exception stack
[537]/</<@moz-extension://ac45f1ba-8bc3-4ae9-b689-9ef3e9d7983a/h0-main.js:1:179755
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:63:129
runSafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:174:38
wrapPromise/</<@resource://gre/modules/ExtensionCommon.jsm:363:15
withLastError@resource://gre/modules/ExtensionCommon.jsm:301:14
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:357:11
]]

```
```

```

Client app:
```
2019/06/04 17:36:04.118068 Starting client (version: 0.2.0)
2019/06/04 17:36:04.118091 Receiving message
```

**Comment by dessant** [comment]
You must set privacy.resistFingerprinting to false, otherwise the browser does not report the correct display scale and the mouse is moved to an incorrect position.

I think this is a Firefox bug, you may try reporting it directly to them. The reasoning should be that extensions run trusted and privileged code, so they should not be lied to when resistFingerprinting is enabled. Extensions should be given correct data about their environment to function correctly.

**Comment by picarica** [comment]
thanks this is the reply i was looking for !
