### ISSUE TITLE
Error After First Request

### ISSUE THREAD

**Issue by tidre** [dessant/buster#88]
**System**
* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 67.0.1

**Extension**
* Extension version: 0.6.0

**Bug description**
After using 1x the BUSTER, no matter which site I try to use, it appears this error message below.
What can I do to get around this problem?

**Logs**
![Capturar](https://user-images.githubusercontent.com/17967697/58957412-f05c9200-8776-11e9-959c-f84efce7cd0d.PNG)

**Comment by dessant** [comment]
See this comment for details: https://github.com/dessant/buster/issues/56#issuecomment-481655521
