### ISSUE TITLE
Not working on Brave with macOS even with shields disabled

### ISSUE THREAD

**Issue by throwaway847462** [dessant/buster#90]
**System**

* OS name: MacOS
* OS version: Latest
* Browser name: Brave
* Browser version: Latest

**Extension**

* Extension version: 0.6.0

* User input simulation: yes

* Client app version: Latest
* Client app installed successfully: yes

**Bug description**
I have shields disabled in Brave but nothing happens when I click on the button, no error, no notification, nothing.
I have the Buster client installed (I think? It installed in the chrome folder
I also copied the org.buster.client.json in Brave-Software/NativeMessagingHosts/, not sure if that folder is even used)

Client app:
```
Can't find any logs on macOS for the client
```

**Comment by dessant** [comment]
Are you clicking the extension icon yourself manually with a mouse, or using some automation or accessibility software?

**Comment by throwaway847462** [comment]
I am clicking it myself
It loads for a few seconds, but then nothing happens

**Comment by dessant** [comment]
After a few seconds the loading animation stops? Could you open the console (Command+Option+J) for the page to check if there is any error?

I don't have a MacBook to test, you'll have to find some indication for the source of the issue.

The logs of the client app are saved in the buster-client-log.txt file in the temp folder of your OS, see if you can find it.

**Comment by throwaway847462** [comment]
Yes the animation stops and the normal icon comes back again
There are no errors in the console like stated above
I suspect that it has something to do with the client, here's the logs of the client:
```
2019/06/06 18:00:28.166533 Starting client (version: 0.2.0)
2019/06/06 18:00:28.166597 Receiving message
2019/06/06 18:00:28.166677 Processing message
2019/06/06 18:00:28.166686 Command: ping
2019/06/06 18:00:28.166690 Sending response
2019/06/06 18:00:28.166736 Receiving message
2019/06/06 18:00:28.168419 Closing client
```

**Comment by dessant** [comment]
The client log appears to be created by a check made by the installer, or when you opened the extension's options. Could you delete that log file and test the extension button again? The file should be recreated with new logs.

On the browser side, it's possible that the error happens in the background script, which is normally hidden by the browser. In Chrome, and likely Brave too, you can visit the extension's details and there is switch to start collecting errors. Restart the browser after turning it on, and do the test again, then visit the extension's details page. There should be a link to inspect the backgound script, and the console there should contain some logs.

**Comment by throwaway847462** [comment]
Logs:
```
2019/06/08 17:47:33.045470 Starting client (version: 0.2.0)
2019/06/08 17:47:33.045504 Receiving message
2019/06/08 17:47:33.045573 Processing message
2019/06/08 17:47:33.045582 Command: ping
2019/06/08 17:47:33.045586 Sending response
2019/06/08 17:47:33.045638 Receiving message
2019/06/08 17:47:33.058951 Processing message
2019/06/08 17:47:33.058981 Command: moveMouse
2019/06/08 17:47:33.058987 X: 1316, Y: 638
2019/06/08 17:47:33.230081 Sending response
2019/06/08 17:47:33.230137 Receiving message
2019/06/08 17:47:33.332489 Processing message
2019/06/08 17:47:33.332527 Command: clickMouse
2019/06/08 17:47:33.343330 Sending response
2019/06/08 17:47:33.343403 Receiving message
2019/06/08 17:47:54.883207 Processing message
2019/06/08 17:47:54.883248 Command: moveMouse
2019/06/08 17:47:54.883257 X: 1322, Y: 689
2019/06/08 17:47:54.976380 Sending response
2019/06/08 17:47:54.976459 Receiving message
2019/06/08 17:47:55.078197 Processing message
2019/06/08 17:47:55.078240 Command: clickMouse
2019/06/08 17:47:55.088366 Sending response
2019/06/08 17:47:55.088444 Receiving message
2019/06/08 17:47:55.302494 Processing message
2019/06/08 17:47:55.302529 Command: typeText
2019/06/08 17:47:55.302536 Data: customize design
2019/06/08 17:47:57.060275 Sending response
2019/06/08 17:47:57.060349 Receiving message
2019/06/08 17:47:57.066096 Processing message
2019/06/08 17:47:57.066133 Command: moveMouse
2019/06/08 17:47:57.066141 X: 1420, Y: 798
2019/06/08 17:47:57.385593 Sending response
2019/06/08 17:47:57.385658 Receiving message
2019/06/08 17:47:57.482906 Processing message
2019/06/08 17:47:57.482942 Command: clickMouse
2019/06/08 17:47:57.495421 Sending response
2019/06/08 17:47:57.495500 Receiving message
2019/06/08 17:47:57.497108 Closing client
```

I switched on the button to "Collect Errors" and restarted the browser

I couldn't find any "background script" option, only "Inspect views (src/background/index.html)".
The only error I could find is:
"Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of undefined"
which always happens if I click the button directly, without going to "audio" first

**Comment by dessant** [comment]
Thanks for the logs, you get that error because the audio source is not found since the app does not switch to the audio version, although it's strange that you did not get a notification about it.

It appears that the client app receives and processes all commands correctly, but [robotgo](https://github.com/go-vgo/robotgo) fails to move the mouse and type.

This is probably not related to Brave, if the mouse did not move *at all*, it should also fail with Firefox and Chrome.

Btw, are you using a single monitor?

**Comment by throwaway847462** [comment]
The "robotgo" hint did it for me.
On the mac, Apps needs to have "accessbility" access in order to control the mouse
(located in System Preferences > Security & Privacy > Privacy > Accessibility)
Allowed the Browser for access and now it works just fine!

Thank you, ticket can be closed!

**Comment by dessant** [comment]
@throwaway847462, thanks for finding the root of the issue! I wonder if accessibility access is disabled by default on some devices, other macOS users did not mention this before. In any case I'll make sure to include this information in the wiki.

**Comment by dessant** [comment]
Your findings are now included in the installation guide, thanks again for looking into it.

https://github.com/dessant/buster-client/wiki/Installing-the-client-app
