### ISSUE TITLE
Issues with Buster on Chrome (Mac OS)

### ISSUE THREAD

**Issue by grodid** [dessant/buster#91]
**System**

* OS name: [e.g. Windows, Ubuntu] MAC OS
* OS version: [e.g. 10] 10.13.6
* Browser name: [e.g. Chrome, Firefox] Chrome
* Browser version: [e.g. 60] 75

**Extension**

* Extension version: [e.g. 1.0.0] 0.6.0

* User input simulation: [e.g. yes, no] NO

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

 I have one question : is the captcha shown below (in French !)
supposed to be solved by Buster extension, please ?

![image](https://user-images.githubusercontent.com/3885121/59114239-0de05600-8947-11e9-9eda-ab9ad7ca0a4d.png)

 Please tell me if you need more info.

 Many Thanks,   Regards,   G.G.

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
No, only reCAPTCHA is supported.
