### ISSUE TITLE
Client not working

### ISSUE THREAD

**Issue by hockeymikey** [dessant/buster#93]
**System**
Waterfox 56.2.8
W7

**Extension**

* Extension version: [e.g. 1.0.0]
0.6.0
* User input simulation: [e.g. yes, no]
yes
* Client app version: [e.g. 1.0.0]
0.2.0
* Client app installed successfully: [e.g. yes, no]
yes

**Bug description**
I have user simulated input turned on but it doesn't work. Gives me an error box popping up in the bottom right hand corner telling me to check the logs. I have to use user input I assume because it doesn't work regardless ever ("Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page") Addon works fine on Firefox, not Waterfox.

**Logs**
Browser:
```
TypeError: s is undefined  script.js:1:57743
```
Client app:
```
2019/06/12 16:29:00.231087 Starting client (version: 0.2.0)
2019/06/12 16:29:00.231087 Receiving message
2019/06/12 16:29:00.231087 Processing message
2019/06/12 16:29:00.231087 Command: ping
2019/06/12 16:29:00.231087 Sending response
2019/06/12 16:29:00.231087 Receiving message
2019/06/12 16:29:00.284087 Processing message
2019/06/12 16:29:00.284087 Command: moveMouse
2019/06/12 16:29:00.284087 X: -1398, Y: 619
2019/06/12 16:29:00.284087 Sending response
2019/06/12 16:29:00.284087 Receiving message
2019/06/12 16:29:00.407087 Processing message
2019/06/12 16:29:00.407087 Command: clickMouse
2019/06/12 16:29:00.408087 Sending response
2019/06/12 16:29:00.408087 Receiving message
2019/06/12 16:29:10.434087 Closing client
```

**Comment by fnordson** [comment]
I have the same problem. 
It did not work even once since I installed it.

**Comment by dessant** [comment]
There is a workaround for Waterfox, set the registry key manually before running the client app installer.

Open cmd and run this command, replace `<user>` with your Windows username:
```
reg add "HKEY_CURRENT_USER\Software\Waterfox\NativeMessagingHosts\org.buster.client" /ve /d "C:\Users\<user>\AppData\Local\buster\manifest\firefox\org.buster.client.json" /f
```

**Comment by dessant** [comment]
Let's track this at https://github.com/dessant/buster/issues/84.

**Comment by dessant** [comment]
The above instructions should be used only if you get an error while installing the client app.

@hockeymikey, I have a hard time following how to reproduce the issue you're seeing. When your access to the audio challenge is blocked by Google, you should not see an error popup that asks you to check the logs. It's also possible that the client app logs you have shared were created when you tried the extension out with Firefox.

I'd suggest to delete everything from "C:\Users\<user>\AppData\Local\buster", the client app log file, and the Firefox registry key: "HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\org.buster.client". Then start over the installation, take note of what happens and share what you have observed, step by step.

**Comment by hockeymikey** [comment]
I tried all the steps and suggestions you put forward with no changes. I've tried it in a new Waterfox profile too and it does the same thing. I get that bugged out message and the mouse moves to the bottom left image and click. There is nothing special with the installation. I install the extension, then the Windows program. Nothing out of the ordinary.
