### ISSUE TITLE
Cannot install user client

### ISSUE THREAD

**Issue by jaffajarre1** [dessant/buster#95]
I went into Chrome options and tried to get natural user input by flipping the switch and it installed and asked for firewall permissions when it finished downloading but then nothing else happened and everytime I try to run a captcha it says I need to install the client app, but I though I already did when I flipped the switch and it downloaded that file?

Other than that I went onto your github repository but couldn't find any .exe file to install it.

Any help?

**Comment by dessant** [comment]
You have to run the installer after you have downloaded it.

https://github.com/dessant/buster-client/releases/download/v0.2.0/buster-client-setup-v0.2.0-windows-amd64.exe
