### ISSUE TITLE
Client won't install on MacOS

### ISSUE THREAD

**Issue by duoi** [dessant/buster#96]
**System**

* OS name: MacOS
* OS version: Mojave 10.14.5
* Browser name: Firefox
* Browser version: 67.0.3

**Extension**

* Extension version: 0.6.0

* User input simulation: Haven't gotten that far

* Client app version: https://github.com/dessant/buster-client/releases/download/v0.2.0/buster-client-setup-v0.2.0-macos-amd64
* Client app installed successfully: No

**Bug description**
Can't install

**Logs**

```
Error: cannot unpack client
```

**Comment by fitzha** [comment]
Same issue. There's no file extension on the image?

**Comment by dessant** [comment]
@duoi, please share the logs of the installer, they are saved in the temp directory in a file named `buster-client-setup-log.txt`. Please also share the exact path of the log file.

**Comment by dessant** [comment]
@fitzha, your have a different issue, the installer must be made executable, see this comment for details: https://github.com/dessant/buster/issues/66#issuecomment-488412971

**Comment by duoi** [comment]
@dessant can you be more specific about where it's located? I can't find anything like it.

**Comment by dessant** [comment]
@duoi, I don't have a device with macOS to test, but this might help in finding the temp folder: http://osxdaily.com/2018/08/17/where-temp-folder-mac-access/

**Comment by dessant** [comment]
Start over the installation process to make sure there is a log file, since the temp dir could have been cleared since the last time you tried.

**Comment by dessant** [comment]
I have no way to reproduce this bug for now, please share the setup logs if anyone encouters this issue again, and we'll reopen it.
