### ISSUE TITLE
Not working for captchas from JDownloader

### ISSUE THREAD

**Issue by MiMoHo** [dessant/buster#98]
**System**

* OS name: macOS X
* OS version: 10.14.6 Beta
* Browser: Firefox v67.0.4 and Brave v0.65.121 (Chromium v75.0.3770.100)

**Extension**
* Extension version: 0.6.0
* User input simulation: no

**Bug description**
I'm trying to use the plugin in combination with the download manager [JDownloader](http://jdownloader.org), however, I receive the following response when attempting to use Buster to solve ReCaptchas from JDownloader:
"Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page."
This issue comes up any time regardless of the browser or VPN connection enabled/disabled.

**Comment by dessant** [comment]
The audio challenge being blocked is a known issue and it's mostly outside the control of this project, see this comment for details: https://github.com/dessant/buster/issues/56#issuecomment-481655521.
