### ISSUE TITLE
been getting this all day

### ISSUE THREAD

**Issue by alidan** [dessant/buster#99]
![chrome_2019-06-30_14-56-40](https://user-images.githubusercontent.com/2681758/60401451-4b4f9200-9b47-11e9-9b42-6a3b75e54a66.png)

when I click to have it solved it goes straight to this.

**Comment by alidan** [comment]
Just tried this in the disenter browser, worked fine, chrome still is telling me to go eff myself though... not sure what's up.

**Comment by markreg** [comment]
Same error here as well in Chrome.

**Comment by alidan** [comment]
the problem seems to be a new captcha version that tracks if you are logged into google
if it sees you are logged in, not a bot
if you aren't logged in, do the test
if you are blocking domains, auto bot

for me it was ublock origins fanboy enhanced tracking filter and a combo filter that had fanboy in it too. 
I immediately thought this extension as it was the only thing I did that may come off as bot, thankfully its not the problem at all.

**Comment by dessant** [comment]
Make sure to also enable user input simulation, see this comment for details: https://github.com/dessant/buster/issues/56#issuecomment-481655521

**Comment by andrewjmetzger** [comment]
> for me it was ublock origin

Correct. More specifically, it's a script served from `https://www.google.com/js/bg/<random numbers and letters>.js`. If you globally allow that, you don't need to change any other filter lists (easylist etc.).

To allow reCaptcha v2 to function on any site, add the following line to My Rules inside uBlock Origin's settings:

    * https://www.google.com/js/bg/ script allow

Detailed steps:

1. Open uBlock Origin settings
2. Click the My Rules tab
3. Paste the above line into the Temporary Rules area on the right
4. Click Save
5. Click Commit
6. Reload the affected tab or tabs, and the Buster extension should work normally

**Comment by alidan** [comment]
thanks, that fixed it completely.
